import {languages,localeCode} from './locales.js';

export const blogCopy={
 en:{title:'Christmas ideas from the Elf Mailroom',description:'Thoughtful, practical ideas for writing to Santa, creating family traditions and making a printable Santa letter feel magical.',intro:'Simple ideas for making Christmas feel personal, cosy and full of wonder.',label:'From the mailroom',read:'Read the article',all:'Explore all Christmas ideas',back:'All Christmas ideas',related:'More from the mailroom',ctaTitle:'Ready to create their letter from Santa?',cta:'Create a Santa letter'},
 de:{title:'Weihnachtsideen aus der Wichtelpost',description:'Praktische Ideen für Briefe an den Weihnachtsmann, schöne Familientraditionen und einen zauberhaften Weihnachtsbrief zum Ausdrucken.',intro:'Einfache Ideen für ein persönliches, gemütliches Weihnachtsfest voller Staunen.',label:'Aus der Wichtelpost',read:'Artikel lesen',all:'Alle Weihnachtsideen entdecken',back:'Alle Weihnachtsideen',related:'Mehr aus der Wichtelpost',ctaTitle:'Bereit für den persönlichen Weihnachtsbrief?',cta:'Weihnachtsbrief gestalten'},
 es:{title:'Ideas de Navidad del correo de Papá Noel',description:'Ideas prácticas para escribir a Papá Noel, crear tradiciones familiares y convertir una carta imprimible en un momento mágico.',intro:'Ideas sencillas para vivir una Navidad personal, acogedora y llena de ilusión.',label:'Desde el correo navideño',read:'Leer el artículo',all:'Ver todas las ideas de Navidad',back:'Todas las ideas de Navidad',related:'Más ideas del correo',ctaTitle:'¿Todo listo para crear su carta de Papá Noel?',cta:'Crear una carta'},
 fr:{title:'Idées de Noël du courrier des lutins',description:'Des idées simples pour écrire au Père Noël, créer des traditions en famille et rendre une lettre à imprimer vraiment magique.',intro:'Des idées faciles pour un Noël personnel, chaleureux et merveilleux.',label:'Le carnet des lutins',read:'Lire l’article',all:'Découvrir toutes les idées de Noël',back:'Toutes les idées de Noël',related:'D’autres idées des lutins',ctaTitle:'Prêt à créer sa lettre du Père Noël ?',cta:'Créer une lettre'},
 pl:{title:'Świąteczne pomysły z poczty elfów',description:'Praktyczne pomysły na list do Mikołaja, rodzinne tradycje i wyjątkowe wręczenie listu od Mikołaja do wydrukowania.',intro:'Proste sposoby na osobiste, przytulne święta pełne dziecięcej radości.',label:'Z poczty elfów',read:'Czytaj artykuł',all:'Zobacz wszystkie świąteczne pomysły',back:'Wszystkie świąteczne pomysły',related:'Więcej z poczty elfów',ctaTitle:'Gotowi stworzyć osobisty list od Mikołaja?',cta:'Stwórz list od Mikołaja'}
};

export const blogArticles=[
 {
  slug:'how-to-write-a-letter-to-santa',date:'2026-09-21',readingMinutes:5,
  translations:{
   en:{title:'How to write a letter to Santa children will treasure',description:'A warm, simple guide to helping a child write to Santa—with prompts, an easy structure and ideas that keep the letter personal.',dek:'The best Santa letters sound like the child who wrote them. These gentle prompts make it easy to begin without taking over.',sections:[
    ['Begin with a little conversation',['Before paper and pencils appear, ask a few open questions: What made you laugh this year? What are you proud of? What would you like Santa to know? A conversation removes the pressure of a blank page and often produces the most memorable details.','Write down their exact words if they are too young to write. Their funny phrases and unexpected priorities are part of the keepsake.']],
    ['Use a simple four-part shape',['A Santa letter does not need to be long. Start with a greeting, share one or two moments from the year, add a wish, then finish with a question or kind message for Santa and the reindeer.','A useful opening is: “Dear Santa, this year I…” If they get stuck, try “Something I learned…”, “I was brave when…” or “At Christmas I hope…”.']],
    ['Make the wish list gentle',['Invite a mixture of wishes: something to play with, something to read, something to do together and a wish for somebody else. This keeps the list imaginative without making Christmas feel like an order form.','It is also fine if a child changes their mind, draws the present instead of naming it or has no present request at all.']],
    ['Add the details only they would know',['A favourite toy, a pet’s name, a new skill or a family joke makes the letter unmistakably theirs. Keep private information such as addresses, school names and schedules off letters that might be photographed or shared.']],
    ['Finish with a small ritual',['Add a drawing, a sticker or a fingerprint “elf seal”. Read the letter together, place it in an envelope and choose how it travels: by the fireplace, in a special postbox or on a windowsill for an elf to collect. The ritual is often what children remember most.']]
   ]},
   de:{title:'So entsteht ein Brief an den Weihnachtsmann, den Kinder lieben',description:'Ein warmer, einfacher Leitfaden mit Fragen, Aufbau und Ideen für einen ganz persönlichen Weihnachtsbrief.',dek:'Die schönsten Briefe klingen nach dem Kind, das sie geschrieben hat. Mit diesen sanften Anregungen fällt der Anfang leicht.',sections:[
    ['Beginnt mit einem kleinen Gespräch',['Frage vor dem Schreiben ganz offen: Was hat dich dieses Jahr zum Lachen gebracht? Worauf bist du stolz? Was soll der Weihnachtsmann wissen? So verschwindet die Angst vor dem leeren Blatt.','Ist dein Kind noch zu klein, notiere seine eigenen Worte. Gerade lustige Formulierungen machen den Brief später besonders.']],
    ['Vier einfache Teile genügen',['Beginnt mit einer Begrüßung, erzählt ein oder zwei Erlebnisse, ergänzt einen Wunsch und endet mit einer Frage oder lieben Worten für den Weihnachtsmann und die Rentiere.','Ein guter Anfang ist: „Lieber Weihnachtsmann, dieses Jahr habe ich…“ Weitere Anregungen sind „Ich habe gelernt…“, „Ich war mutig, als…“ oder „Zu Weihnachten hoffe ich…“.']],
    ['Eine Wunschliste ohne Druck',['Sammelt unterschiedliche Wünsche: etwas zum Spielen, etwas zum Lesen, ein gemeinsames Erlebnis und einen Wunsch für jemand anderen. So bleibt der Brief fantasievoll und wird nicht zur Bestellung.','Natürlich darf ein Kind seine Meinung ändern, den Wunsch malen oder ganz ohne Geschenkewunsch schreiben.']],
    ['Persönliche, aber sichere Details',['Lieblingsspielzeug, Haustier, neue Fähigkeit oder Familienwitz machen den Brief unverwechselbar. Adressen, Schulnamen und Tagesabläufe gehören nicht in Briefe, die fotografiert oder geteilt werden könnten.']],
    ['Ein kleines Ritual zum Schluss',['Eine Zeichnung, ein Aufkleber oder ein Fingerabdruck als „Wichtelsiegel“ vollenden den Brief. Lest ihn gemeinsam und bestimmt seinen Reiseweg: Kamin, Weihnachtspostkasten oder Fensterbank. Oft bleibt gerade dieses Ritual in Erinnerung.']]
   ]},
   es:{title:'Cómo escribir una carta a Papá Noel que recordarán siempre',description:'Una guía sencilla y cálida con preguntas, estructura e ideas para escribir una carta de Papá Noel muy personal.',dek:'Las mejores cartas suenan como el peque que las escribió. Estas preguntas ayudan a empezar sin escribir por ellos.',sections:[
    ['Empieza con una conversación',['Antes de sacar el papel, pregunta: ¿qué te hizo reír este año?, ¿de qué te sientes orgulloso?, ¿qué te gustaría contarle a Papá Noel? Hablar elimina la presión de la hoja en blanco.','Si todavía no escribe, apunta sus palabras tal como las dice. Sus expresiones y ocurrencias son parte del recuerdo.']],
    ['Una estructura de cuatro partes',['Basta con un saludo, uno o dos momentos del año, un deseo y una despedida con una pregunta o un mensaje cariñoso para Papá Noel y los renos.','Puede empezar con: «Querido Papá Noel, este año…». Si se bloquea, prueba «He aprendido…», «Fui valiente cuando…» o «Esta Navidad espero…».']],
    ['Una lista de deseos amable',['Mezclad deseos: algo para jugar, algo para leer, una experiencia juntos y un deseo para otra persona. Así la carta conserva la imaginación sin parecer un pedido.','También está bien cambiar de idea, dibujar el regalo o no pedir nada material.']],
    ['Detalles personales y seguros',['Su juguete favorito, el nombre de una mascota, una habilidad nueva o una broma familiar hacen que la carta sea única. Evita direcciones, colegios y rutinas si la carta puede fotografiarse o compartirse.']],
    ['Termina con un pequeño ritual',['Añade un dibujo, una pegatina o una huella como “sello de elfo”. Leedla juntos y decidid cómo viajará: junto a la chimenea, en un buzón especial o en la ventana para que la recoja un elfo.']]
   ]},
   fr:{title:'Comment écrire une lettre au Père Noël que les enfants garderont',description:'Un guide simple et chaleureux avec des questions et des idées pour une lettre au Père Noël vraiment personnelle.',dek:'Les plus belles lettres ressemblent à l’enfant qui les écrit. Ces quelques pistes aident à commencer sans écrire à sa place.',sections:[
    ['Commencez par discuter',['Avant de sortir le papier, demandez : qu’est-ce qui t’a fait rire cette année ? De quoi es-tu fier ? Qu’aimerais-tu raconter au Père Noël ? La conversation fait oublier la page blanche.','Si votre enfant n’écrit pas encore, notez ses mots tels quels. Ses expressions amusantes feront tout le charme du souvenir.']],
    ['Quatre petites parties suffisent',['Commencez par une salutation, racontez un ou deux moments de l’année, ajoutez un souhait puis terminez par une question ou un mot gentil pour le Père Noël et ses rennes.','Une première phrase facile : « Cher Père Noël, cette année… » Essayez aussi « J’ai appris… », « J’ai été courageux quand… » ou « À Noël, j’espère… ».']],
    ['Une liste de souhaits toute douce',['Mélangez les envies : un jeu, un livre, un moment à vivre ensemble et un souhait pour quelqu’un d’autre. La lettre reste ainsi imaginative sans devenir une commande.','Un enfant peut aussi changer d’avis, dessiner son idée ou ne demander aucun cadeau.']],
    ['Des détails personnels, sans trop en dire',['Un jouet préféré, le nom d’un animal, un nouveau talent ou une plaisanterie familiale rendent la lettre unique. Évitez adresse, école et habitudes si elle risque d’être photographiée ou partagée.']],
    ['Terminez par un petit rituel',['Ajoutez un dessin, un autocollant ou une empreinte en guise de « sceau de lutin ». Lisez la lettre ensemble puis choisissez son départ : cheminée, boîte spéciale ou rebord de fenêtre pour le passage d’un lutin.']]
   ]},
   pl:{title:'Jak napisać list do Mikołaja, który dziecko zachowa na długo',description:'Ciepły, prosty poradnik z pytaniami i pomysłami, dzięki którym list do Mikołaja będzie naprawdę osobisty.',dek:'Najpiękniejszy list brzmi jak dziecko, które go napisało. Te delikatne podpowiedzi pomagają zacząć, nie odbierając mu głosu.',sections:[
    ['Zacznijcie od rozmowy',['Zanim pojawią się kartka i kredki, zapytaj: co rozśmieszyło Cię w tym roku? Z czego jesteś dumny? Co Mikołaj powinien wiedzieć? Rozmowa zdejmie presję pustej kartki.','Jeśli dziecko jeszcze nie pisze, zanotuj dokładnie jego słowa. Zabawne zwroty i zaskakujące pomysły są częścią pamiątki.']],
    ['Wystarczą cztery proste części',['Zacznijcie od powitania, opiszcie jedno lub dwa wydarzenia z roku, dodajcie życzenie, a na końcu pytanie albo miłe słowa dla Mikołaja i reniferów.','Dobry początek to: „Drogi Mikołaju, w tym roku…”. Pomogą też zdania „Nauczyłem się…”, „Byłem odważny, gdy…” lub „W święta mam nadzieję…”.']],
    ['Lista życzeń bez presji',['Połączcie różne marzenia: coś do zabawy, coś do czytania, wspólne przeżycie i życzenie dla kogoś innego. List pozostanie twórczy i nie zmieni się w zamówienie.','Dziecko może zmienić zdanie, narysować prezent albo wcale nie prosić o rzecz.']],
    ['Osobiste, ale bezpieczne szczegóły',['Ulubiona zabawka, imię zwierzaka, nowa umiejętność czy rodzinny żart sprawią, że list będzie niepowtarzalny. Pomiń adres, nazwę szkoły i plan dnia, jeśli list może trafić na zdjęcie lub do internetu.']],
    ['Zakończcie małym rytuałem',['Dodajcie rysunek, naklejkę albo odcisk palca jako „elfią pieczęć”. Przeczytajcie list razem i wybierzcie drogę: kominek, specjalna skrzynka lub parapet, z którego odbierze go elf.']]
   ]}
  }
 },
 {
  slug:'cosy-christmas-eve-traditions',date:'2026-09-21',readingMinutes:4,
  translations:{
   en:{title:'Seven cosy Christmas Eve traditions for families',description:'Seven calm, low-cost Christmas Eve traditions that help families slow down and make memories together.',dek:'Christmas Eve does not need a packed schedule. One or two small rituals can become the moments everyone looks forward to.',sections:[
    ['1. Take a Christmas-lights walk',['Wrap up after dusk and choose a familiar route. Let children count stars, spot their favourite window or choose the best-decorated tree. Phones can stay in a pocket; the point is simply to notice things together.']],
    ['2. Make a tiny North Pole supper',['Hot chocolate, fruit and a favourite biscuit are enough. Give the snack a festive name and serve it by the tree. A small tradition repeated each year matters more than an elaborate menu.']],
    ['3. Open a book, not every present',['Choose one Christmas story and read it aloud. Older children can take a page each; younger ones can find recurring pictures. Write the year inside the cover to turn the book into a family record.']],
    ['4. Leave a kind note',['Alongside Santa’s snack, leave a thank-you for a neighbour, grandparent, teacher or friend. Children can dictate, draw or sign it. Deliver it after Christmas if the evening is already busy.']],
    ['5. Listen for sleigh bells',['Dim the lights, open a window for one quiet minute and listen. Wind, distant traffic and imagination do the rest. A grown-up with a tiny bell can add a little theatre—subtle is usually more magical.']],
    ['6. Create a yearly photograph',['Use the same spot, blanket or silly pose each Christmas Eve. Consistency turns an ordinary photo into a story that grows with the family.']],
    ['7. End with tomorrow’s promise',['Before bed, let everyone name one thing they are looking forward to that is not a present: breakfast together, music, seeing family or a slow morning. It leaves the day centred on connection.']]
   ]},
   de:{title:'Sieben gemütliche Rituale für Heiligabend',description:'Sieben ruhige, günstige Rituale, mit denen Familien an Heiligabend gemeinsam schöne Erinnerungen schaffen.',dek:'Heiligabend braucht keinen vollen Zeitplan. Schon ein oder zwei kleine Rituale werden schnell zu echten Lieblingsmomenten.',sections:[
    ['1. Ein Spaziergang zu den Weihnachtslichtern',['Geht nach Einbruch der Dunkelheit eine vertraute Runde. Kinder können Sterne zählen, ihr Lieblingsfenster finden oder den schönsten Baum wählen. Das Handy bleibt dabei einfach in der Tasche.']],
    ['2. Ein kleines Nordpol-Abendessen',['Heiße Schokolade, Obst und ein Lieblingskeks genügen. Gebt dem Snack einen festlichen Namen und esst ihn am Baum. Wiederholung ist wichtiger als ein aufwendiges Menü.']],
    ['3. Ein Buch statt aller Geschenke',['Lest gemeinsam eine Weihnachtsgeschichte. Große Kinder übernehmen einzelne Seiten, kleine suchen wiederkehrende Bilder. Schreibt das Jahr in den Einband – so wird das Buch zum Familienalbum.']],
    ['4. Eine liebe Nachricht',['Legt neben den Snack für den Weihnachtsmann einen Dank für Nachbarn, Großeltern, Lehrkräfte oder Freunde. Kinder können diktieren, malen oder unterschreiben.']],
    ['5. Auf Glöckchen lauschen',['Dämpft das Licht, öffnet kurz ein Fenster und hört genau hin. Wind, ferne Geräusche und Fantasie erledigen den Rest. Ein kleines Glöckchen darf unauffällig nachhelfen.']],
    ['6. Das jährliche Foto',['Nutzt jedes Jahr denselben Ort, dieselbe Decke oder dieselbe lustige Pose. So wird ein gewöhnliches Foto zu einer Geschichte, die mit der Familie wächst.']],
    ['7. Vorfreude auf morgen',['Vor dem Schlafengehen nennt jeder etwas, worauf er sich freut, das kein Geschenk ist: gemeinsames Frühstück, Musik, Familienbesuch oder ein ruhiger Morgen.']]
   ]},
   es:{title:'Siete tradiciones familiares para una Nochebuena acogedora',description:'Siete tradiciones tranquilas y económicas para bajar el ritmo y crear recuerdos juntos en Nochebuena.',dek:'La Nochebuena no necesita una agenda llena. Uno o dos pequeños rituales pueden convertirse en el momento más esperado.',sections:[
    ['1. Paseo de luces navideñas',['Salid al anochecer por una ruta conocida. Los peques pueden contar estrellas, elegir su ventana favorita o buscar el árbol mejor decorado. El móvil puede quedarse en el bolsillo.']],
    ['2. Una pequeña cena del Polo Norte',['Chocolate caliente, fruta y una galleta favorita son suficientes. Ponedle un nombre festivo y tomadla junto al árbol. Repetir un gesto sencillo vale más que un menú elaborado.']],
    ['3. Abrir un libro, no todos los regalos',['Elegid un cuento de Navidad y leedlo en voz alta. Los mayores pueden turnarse; los pequeños, buscar dibujos. Anotad el año en la cubierta para crear un registro familiar.']],
    ['4. Dejar una nota amable',['Junto al tentempié de Papá Noel, escribid un agradecimiento para un vecino, familiar, profe o amigo. Los niños pueden dictarlo, dibujarlo o firmarlo.']],
    ['5. Escuchar los cascabeles',['Bajad la luz, abrid la ventana un minuto y escuchad. El viento, los sonidos lejanos y la imaginación harán el resto. Un cascabel discreto puede añadir magia.']],
    ['6. La foto de cada año',['Usad el mismo rincón, manta o pose divertida cada Nochebuena. La constancia convierte una foto corriente en una historia familiar.']],
    ['7. La promesa de mañana',['Antes de dormir, cada persona dice algo que espera con ilusión y que no sea un regalo: desayunar juntos, escuchar música, ver a la familia o disfrutar de una mañana tranquila.']]
   ]},
   fr:{title:'Sept traditions douces pour le réveillon en famille',description:'Sept traditions calmes et peu coûteuses pour ralentir et créer de beaux souvenirs ensemble le soir de Noël.',dek:'Le réveillon n’a pas besoin d’un programme chargé. Un ou deux petits rituels suffisent pour créer un moment très attendu.',sections:[
    ['1. Une promenade parmi les lumières',['Sortez à la tombée de la nuit sur un trajet familier. Les enfants peuvent compter les étoiles, choisir leur fenêtre préférée ou repérer le plus beau sapin. Le téléphone reste dans la poche.']],
    ['2. Un petit souper du pôle Nord',['Chocolat chaud, fruits et biscuit préféré suffisent. Donnez un nom de fête au goûter et servez-le près du sapin. La répétition compte plus qu’un menu compliqué.']],
    ['3. Ouvrir un livre, pas tous les cadeaux',['Choisissez une histoire de Noël et lisez-la à voix haute. Les grands lisent une page, les petits cherchent des images. Notez l’année dans la couverture pour en faire une archive familiale.']],
    ['4. Laisser un mot gentil',['À côté du goûter du Père Noël, écrivez un merci à un voisin, un proche, un enseignant ou un ami. Les enfants peuvent dicter, dessiner ou signer.']],
    ['5. Écouter les grelots',['Baissez les lumières, ouvrez la fenêtre une minute et écoutez. Le vent, les bruits lointains et l’imagination feront le reste. Un petit grelot discret ajoute juste ce qu’il faut de magie.']],
    ['6. La photo annuelle',['Gardez chaque année le même coin, la même couverture ou la même pose amusante. Une photo ordinaire devient alors une histoire qui grandit avec la famille.']],
    ['7. La promesse de demain',['Avant de dormir, chacun nomme une chose attendue qui n’est pas un cadeau : le petit-déjeuner ensemble, la musique, la famille ou une matinée tranquille.']]
   ]},
   pl:{title:'Siedem przytulnych tradycji na rodzinną Wigilię',description:'Siedem spokojnych i niedrogich tradycji, które pomagają zwolnić i tworzyć wspólne wspomnienia w Wigilię.',dek:'Wigilia nie potrzebuje napiętego planu. Jeden lub dwa małe rytuały mogą stać się chwilami, na które czeka cała rodzina.',sections:[
    ['1. Spacer śladem świątecznych świateł',['Po zmroku wybierzcie znajomą trasę. Dzieci mogą liczyć gwiazdy, szukać ulubionego okna albo wybrać najpiękniejszą choinkę. Telefon niech zostanie w kieszeni.']],
    ['2. Mała kolacja z bieguna północnego',['Wystarczą gorąca czekolada, owoce i ulubione ciastko. Nadajcie przekąsce świąteczną nazwę i zjedzcie ją przy choince. Powtarzalny drobiazg znaczy więcej niż wyszukane menu.']],
    ['3. Otwórzcie książkę, nie wszystkie prezenty',['Wybierzcie jedną świąteczną opowieść i przeczytajcie ją na głos. Starsi mogą czytać po stronie, a młodsi wyszukiwać obrazki. Wpiszcie rok na okładce, tworząc rodzinną kronikę.']],
    ['4. Zostawcie komuś miłą wiadomość',['Obok przekąski dla Mikołaja połóżcie podziękowanie dla sąsiada, dziadków, nauczyciela lub przyjaciela. Dzieci mogą je podyktować, narysować albo podpisać.']],
    ['5. Posłuchajcie dzwonków sań',['Przygaście światło, otwórzcie na minutę okno i nasłuchujcie. Wiatr, odległe dźwięki i wyobraźnia zrobią resztę. Dyskretny dzwoneczek doda odrobinę teatru.']],
    ['6. Coroczne zdjęcie',['Wybierzcie to samo miejsce, koc lub zabawną pozę na każdy rok. Zwykłe zdjęcie zmieni się w historię, która rośnie razem z rodziną.']],
    ['7. Obietnica jutra',['Przed snem niech każdy wymieni jedną rzecz, na którą czeka, a która nie jest prezentem: wspólne śniadanie, muzykę, spotkanie z rodziną albo spokojny poranek.']]
   ]}
  }
 },
 {
  slug:'how-to-make-a-printable-santa-letter-magical',date:'2026-09-21',readingMinutes:4,
  translations:{
   en:{title:'How to make a printable Santa letter feel truly magical',description:'Simple printing, presentation and delivery ideas that turn a printable letter from Santa into a memorable Christmas moment.',dek:'A home-printed letter can feel every bit as special as North Pole post. The secret is thoughtful timing and one believable detail.',sections:[
    ['Choose paper that suits the design',['Warm white, ivory or lightly textured uncoated paper gives illustrations a softer finish than bright office paper. Standard 100–120 gsm paper usually feeds through a home printer easily while feeling more substantial.','Print one test page first. Select actual size or 100% scale so borders are not enlarged and cut off, and use the printer’s best-quality setting for illustrated stationery.']],
    ['Add one physical clue',['A little sign of the journey makes the story feel real: a dusting of flour “snow” near the envelope, a red ribbon, a tiny bell or a pine sprig. Pick one rather than adding everything. Understatement leaves room for imagination.','Avoid loose glitter around young children and pets. A star-shaped paper confetti piece gives a similar effect with less mess.']],
    ['Let the envelope tell the story',['Write the child’s name by hand and add “Special delivery” or “North Pole Post”. You can draw a simple stamp in red pencil or ask another adult to address it so the handwriting feels unfamiliar.']],
    ['Plan a believable arrival',['Slip it under the tree, place it beside an empty snack plate or leave it at the front door after a gentle knock. Morning discoveries are calmer; an evening arrival can become part of bedtime. Choose the moment that fits your child.']],
    ['Read without rushing',['Let the child open the envelope and decide whether to read independently or together. Pause when the letter mentions a personal detail. That recognition—not an elaborate prop—is usually the moment that creates the magic.','Afterwards, date the back and keep it with Christmas photographs or decorations. Next year it will already feel like part of the family story.']]
   ]},
   de:{title:'So wird ein Weihnachtsbrief zum Ausdrucken richtig zauberhaft',description:'Einfache Ideen für Druck, Umschlag und Übergabe, die einen Weihnachtsbrief zu einem besonderen Moment machen.',dek:'Auch ein zu Hause gedruckter Brief kann wie echte Nordpolpost wirken. Entscheidend sind der richtige Moment und ein glaubwürdiges Detail.',sections:[
    ['Papier passend zum Design',['Warmweißes, elfenbeinfarbenes oder leicht strukturiertes Naturpapier wirkt weicher als helles Büropapier. 100 bis 120 g/m² lassen sich meist gut zu Hause drucken und fühlen sich wertiger an.','Drucke zuerst eine Testseite bei 100 % Größe, damit keine Ränder abgeschnitten werden. Für illustriertes Briefpapier eignet sich die beste Druckqualität.']],
    ['Eine kleine Spur genügt',['Ein wenig Mehl-„Schnee“, rotes Band, Glöckchen oder Tannenzweig erzählt von der Reise. Entscheide dich für ein Detail statt für alles zugleich – Zurückhaltung lässt der Fantasie Platz.','Verzichte bei kleinen Kindern und Tieren auf losen Glitzer. Papiersterne erzielen einen ähnlichen Effekt ohne Chaos.']],
    ['Der Umschlag erzählt mit',['Schreibe den Namen des Kindes von Hand und ergänze „Sonderzustellung“ oder „Nordpolpost“. Ein anderer Erwachsener kann den Umschlag beschriften, damit die Handschrift unbekannt wirkt.']],
    ['Ein glaubwürdiger Ankunftsmoment',['Lege den Brief unter den Baum, neben den leeren Keksteller oder nach einem leisen Klopfen vor die Tür. Morgens ist die Entdeckung ruhiger, abends wird sie Teil des Zubettgehens.']],
    ['Ohne Eile lesen',['Lass dein Kind den Umschlag öffnen und entscheiden, ob ihr gemeinsam lest. Macht eine Pause, wenn ein persönliches Detail auftaucht. Dieses Wiedererkennen schafft meist mehr Magie als jede Dekoration.','Schreibe danach das Datum auf die Rückseite und bewahre den Brief bei den Weihnachtsfotos auf.']]
   ]},
   es:{title:'Cómo convertir una carta imprimible de Papá Noel en pura magia',description:'Ideas sencillas para imprimir, presentar y entregar una carta de Papá Noel de forma inolvidable.',dek:'Una carta impresa en casa puede parecer auténtico correo del Polo Norte. El secreto está en el momento y en un detalle creíble.',sections:[
    ['Elige un papel que acompañe el diseño',['El papel blanco cálido, marfil o ligeramente texturizado suaviza las ilustraciones. Un gramaje de 100–120 g suele pasar bien por una impresora doméstica y se siente más especial.','Imprime primero una prueba al 100 % para no ampliar ni cortar los bordes. Usa la calidad alta en papelería ilustrada.']],
    ['Añade una sola pista física',['Un poco de “nieve” de harina junto al sobre, una cinta roja, un cascabel o una ramita cuentan el viaje. Elige solo una cosa: la sutileza deja espacio a la imaginación.','Evita la purpurina suelta cerca de peques y mascotas. El confeti de papel en forma de estrella funciona sin tanto desorden.']],
    ['Deja que el sobre cuente la historia',['Escribe a mano el nombre y añade «Entrega especial» o «Correo del Polo Norte». Otra persona adulta puede escribirlo para que la letra resulte desconocida.']],
    ['Planea una llegada creíble',['Déjala bajo el árbol, junto al plato vacío de Papá Noel o delante de la puerta tras un golpecito suave. Por la mañana hay más calma; por la noche puede formar parte de la rutina de dormir.']],
    ['Leedla sin prisas',['Deja que abra el sobre y elija si quiere leer a solas o contigo. Haz una pausa cuando aparezca un detalle personal. Ese reconocimiento suele crear más magia que cualquier accesorio.','Después, escribe la fecha detrás y guarda la carta con las fotos o adornos navideños.']]
   ]},
   fr:{title:'Comment rendre une lettre du Père Noël à imprimer vraiment magique',description:'Des idées simples d’impression et de mise en scène pour transformer une lettre du Père Noël en souvenir inoubliable.',dek:'Une lettre imprimée à la maison peut sembler venir du pôle Nord. Tout repose sur le bon moment et un détail crédible.',sections:[
    ['Choisissez un papier adapté',['Un papier blanc chaud, ivoire ou légèrement texturé adoucit les illustrations. Un grammage de 100 à 120 g passe généralement bien dans une imprimante domestique tout en étant plus élégant.','Faites d’abord un essai à 100 % pour éviter que les bordures soient agrandies et coupées. Choisissez la meilleure qualité pour le papier illustré.']],
    ['Ajoutez un seul indice',['Un peu de farine en guise de neige, un ruban rouge, un grelot ou une branche de sapin raconte le voyage. Un seul détail suffit : la discrétion laisse travailler l’imagination.','Évitez les paillettes avec les jeunes enfants et les animaux. Quelques étoiles en papier donnent un effet proche sans désordre.']],
    ['L’enveloppe raconte déjà une histoire',['Écrivez le prénom à la main puis « Livraison spéciale » ou « Courrier du pôle Nord ». Un autre adulte peut écrire l’adresse pour rendre l’écriture inconnue.']],
    ['Préparez une arrivée crédible',['Glissez la lettre sous le sapin, près de l’assiette vide du Père Noël ou devant la porte après un petit coup discret. Le matin est plus calme ; le soir, elle rejoint le rituel du coucher.']],
    ['Lisez sans vous presser',['Laissez l’enfant ouvrir l’enveloppe et choisir de lire seul ou avec vous. Marquez une pause devant un détail personnel. Cette reconnaissance crée souvent davantage de magie que tous les accessoires.','Inscrivez ensuite la date au dos et gardez la lettre avec les photos ou décorations de Noël.']]
   ]},
   pl:{title:'Jak sprawić, by list od Mikołaja do wydrukowania był naprawdę magiczny',description:'Proste pomysły na druk, oprawę i wręczenie listu od Mikołaja, które tworzą niezapomnianą świąteczną chwilę.',dek:'List wydrukowany w domu może wyglądać jak prawdziwa przesyłka z bieguna północnego. Sekret to dobry moment i jeden wiarygodny szczegół.',sections:[
    ['Dobierz papier do ilustracji',['Ciepła biel, kość słoniowa lub lekko fakturowany papier niepowlekany dają delikatniejszy efekt niż jasny papier biurowy. Gramatura 100–120 g zwykle dobrze przechodzi przez domową drukarkę, a jest przyjemniejsza w dotyku.','Najpierw wydrukuj próbkę w skali 100%, aby obramowanie nie zostało powiększone i obcięte. Do ilustracji wybierz najwyższą jakość druku.']],
    ['Dodaj jeden fizyczny ślad',['Odrobina mącznego „śniegu” przy kopercie, czerwona wstążka, dzwoneczek albo gałązka opowiedzą o podróży. Wybierz jedną rzecz – subtelność zostawia miejsce wyobraźni.','Przy małych dzieciach i zwierzętach zrezygnuj z sypkiego brokatu. Papierowe gwiazdki dadzą podobny efekt bez bałaganu.']],
    ['Niech koperta zacznie opowieść',['Napisz ręcznie imię dziecka i dodaj „Przesyłka specjalna” albo „Poczta bieguna północnego”. Poproś inną dorosłą osobę o zaadresowanie, aby charakter pisma był nieznajomy.']],
    ['Zaplanuj wiarygodne przybycie',['Wsuń list pod choinkę, połóż obok pustego talerzyka po przekąsce dla Mikołaja albo zostaw przed drzwiami po delikatnym pukaniu. Poranek będzie spokojniejszy, a wieczorna dostawa może stać się częścią zasypiania.']],
    ['Czytajcie bez pośpiechu',['Pozwól dziecku otworzyć kopertę i zdecydować, czy czytacie razem. Zatrzymajcie się przy osobistym szczególe. To rozpoznanie zwykle tworzy więcej magii niż rozbudowana dekoracja.','Na koniec wpisz datę na odwrocie i zachowaj list ze świątecznymi zdjęciami lub ozdobami.']]
   ]}
  }
 }
];

export function articleTranslation(article,language='en'){return article.translations[localeCode(language)]||article.translations.en}
export function findBlogArticle(slug){return blogArticles.find(article=>article.slug===slug)}
export function blogPath(language='en',slug=''){const code=localeCode(language);return `${code==='en'?'/':`/${code}/`}blog/${slug?`${slug}/`:''}`}
export function blogAlternates(origin,slug=''){return [...languages.map(({code})=>({language:code,url:origin+blogPath(code,slug)})),{language:'x-default',url:origin+blogPath('en',slug)}]}
