import {retentionCopy} from './retention-copy.js';
import {polishLabels,polishPrivacy,polishTerms} from './legal-pl.js';
import {localeCode,languages} from './locales.js';
import {escapeHtml,siteOrigin,defaultSiteUrl,languagePath,legalPath} from './seo.js';
export const policyVersion='2026-09-23-v5';
export const legalFields={name:'VITE_BUSINESS_NAME',address:'VITE_BUSINESS_ADDRESS',country:'VITE_BUSINESS_COUNTRY',email:'VITE_SUPPORT_EMAIL',retention:'VITE_PRIVACY_RETENTION',providers:'VITE_PRIVACY_PROVIDERS'};
export function legalConfig(env={}){const result={};for(const[key,name]of Object.entries(legalFields))result[key]=String(env[name]||'').trim();result.abn=String(env.VITE_BUSINESS_ABN||'').trim();result.ready=Object.keys(legalFields).every(key=>result[key].length>0)&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(result.email);return result;}
export {legalPath} from './seo.js';
const copy={
 en:{privacy:'Privacy policy',terms:'Terms and conditions',refunds:'Cancellations and refunds',home:'Back to the mailroom',draft:'Draft — business identity, contact information and data-handling details must be completed before sales open.',updated:'Policy version',seller:'Who operates Elf Mailroom',name:'Business name',address:'Business address',country:'Country of establishment',email:'Support and privacy contact',missing:'To be completed before sales open',introPrivacy:'This notice explains how Elf Mailroom handles the information used to create and deliver a personalised digital Santa letter. The service is for adults arranging a letter for a child.',introTerms:'These terms cover a personalised digital Santa letter. You receive a PDF to download and print at home. No physical letter, envelope or other item is sent by post.',retention:'Retention schedule',providers:'Hosting, email providers and international transfers',contact:'Contact us with your order reference where relevant. Do not send card details or extra sensitive information about a child.',print:'Print or save this policy',withdrawal:'Example cancellation message',withdrawalText:'I wish to withdraw from my purchase of a digital Santa letter. Order reference: ____. Purchase date: ____. Purchaser name and email: ____. Date of this notice: ____. Send this to the support contact above; using this wording is optional.'},
 de:{privacy:'Datenschutzerklärung',terms:'Allgemeine Geschäftsbedingungen',refunds:'Widerruf und Erstattungen',home:'Zurück zur Wichtelpost',draft:'Entwurf — Unternehmensdaten, Kontaktinformationen und Angaben zur Datenverarbeitung müssen vor Verkaufsstart ergänzt werden.',updated:'Fassung',seller:'Wer Elf Mailroom betreibt',name:'Unternehmensname',address:'Geschäftsanschrift',country:'Sitzland',email:'Kontakt für Support und Datenschutz',missing:'Vor Verkaufsstart zu ergänzen',introPrivacy:'Diese Erklärung beschreibt, wie Elf Mailroom Angaben für die Erstellung und Bereitstellung eines persönlichen digitalen Weihnachtsbriefs verarbeitet. Das Angebot richtet sich an Erwachsene, die einen Brief für ein Kind bestellen.',introTerms:'Diese Bedingungen gelten für einen persönlichen digitalen Weihnachtsbrief. Du erhältst eine PDF zum Herunterladen und Ausdrucken zu Hause. Es werden kein Brief, kein Umschlag und keine anderen Gegenstände per Post verschickt.',retention:'Aufbewahrungsfristen',providers:'Hosting, E-Mail-Anbieter und internationale Übermittlungen',contact:'Bitte nenne bei Anfragen gegebenenfalls deine Bestellnummer. Sende keine Kartendaten oder zusätzlichen sensiblen Angaben über ein Kind.',print:'Diese Richtlinie drucken oder speichern',withdrawal:'Beispiel für eine Widerrufserklärung',withdrawalText:'Hiermit widerrufe ich meinen Kauf eines digitalen Weihnachtsbriefs. Bestellnummer: ____. Kaufdatum: ____. Name und E-Mail der kaufenden Person: ____. Datum der Erklärung: ____. Sende die Erklärung an den oben genannten Supportkontakt. Die Verwendung dieses Textes ist freiwillig.'},
 es:{privacy:'Política de privacidad',terms:'Términos y condiciones',refunds:'Desistimiento y reembolsos',home:'Volver al correo navideño',draft:'Borrador — hay que completar la identidad del negocio, los datos de contacto y el tratamiento de datos antes de abrir las ventas.',updated:'Versión de la política',seller:'Quién opera Elf Mailroom',name:'Nombre legal del negocio',address:'Dirección del negocio',country:'País de establecimiento',email:'Contacto de soporte y privacidad',missing:'Pendiente antes de abrir las ventas',introPrivacy:'Esta política explica cómo Elf Mailroom trata los datos utilizados para crear y entregar una carta digital personalizada de Papá Noel. El servicio está dirigido a personas adultas que encargan una carta para un menor.',introTerms:'Estas condiciones se aplican a una carta digital personalizada de Papá Noel. Recibes un PDF para descargar e imprimir en casa. No se envían cartas, sobres ni otros artículos físicos por correo postal.',retention:'Plazos de conservación',providers:'Alojamiento, proveedores de correo y transferencias internacionales',contact:'Indica la referencia del pedido cuando corresponda. No envíes datos de tarjeta ni información sensible adicional sobre un menor.',print:'Imprimir o guardar esta política',withdrawal:'Ejemplo de mensaje de desistimiento',withdrawalText:'Deseo desistir de mi compra de una carta digital de Papá Noel. Referencia del pedido: ____. Fecha de compra: ____. Nombre y correo del comprador: ____. Fecha de este aviso: ____. Envíalo al contacto de soporte indicado arriba; utilizar este texto es opcional.'},
 fr:{privacy:'Politique de confidentialité',terms:'Conditions générales',refunds:'Rétractation et remboursements',home:'Retour au courrier de Noël',draft:'Projet — l’identité de l’entreprise, les coordonnées et les modalités de traitement des données doivent être complétées avant l’ouverture des ventes.',updated:'Version de la politique',seller:'Qui exploite Elf Mailroom',name:'Raison sociale',address:'Adresse professionnelle',country:'Pays d’établissement',email:'Contact assistance et confidentialité',missing:'À compléter avant l’ouverture des ventes',introPrivacy:'Cette politique explique comment Elf Mailroom traite les informations utilisées pour créer et fournir une lettre numérique personnalisée du Père Noël. Le service s’adresse aux adultes qui commandent une lettre pour un enfant.',introTerms:'Ces conditions concernent une lettre numérique personnalisée du Père Noël. Vous recevez un PDF à télécharger et imprimer chez vous. Aucune lettre, enveloppe ou autre article physique n’est envoyé par la poste.',retention:'Durées de conservation',providers:'Hébergement, prestataires e-mail et transferts internationaux',contact:'Indiquez votre référence de commande si nécessaire. Ne transmettez pas de données de carte bancaire ni d’informations sensibles supplémentaires sur un enfant.',print:'Imprimer ou enregistrer cette politique',withdrawal:'Exemple de message de rétractation',withdrawalText:'Je souhaite me rétracter de mon achat d’une lettre numérique du Père Noël. Référence de commande : ____. Date d’achat : ____. Nom et e-mail de l’acheteur : ____. Date de cet avis : ____. Envoyez ce message au contact indiqué ci-dessus ; l’utilisation de ce texte est facultative.'}
};
// Draft translations reflect the implemented service. Business-specific sections come from public configuration.
const privacy={
 en:[
 ['Information you provide','We receive the adult purchaser’s email, the child’s first name, wishes, achievements and any optional pet, toy or message details you submit. We also keep the chosen design and language, generated letters, rewrite instructions and exclusions, revision history, accepted version and PDFs. Provide only details needed for the letter. Do not submit addresses, dates of birth, school names, health information or other sensitive details about a child.'],
 ['Orders, payments and technical data','We store purchase references, payment status, checkout references, price and relevant timestamps. Stripe processes the payment; our application does not store full card numbers or card security codes. Our hosting and security infrastructure may process IP addresses, request information and operational logs. If you use an account, we store your email and a protected password hash.'],
 ['Why we use the information','We use these details to create the letter, take payment, provide private access and PDF downloads, process rewrites, send delivery emails when enabled, answer support requests, prevent misuse and meet legal obligations. We do not use the child’s letter details for advertising.'],
 ['Legal bases where the GDPR applies','We use the adult purchaser’s necessary order and contact details to perform the purchase contract, records required by law to comply with legal obligations, and proportionate security and support processing for legitimate interests. Processing a child’s details for an adult-requested personalised letter requires an appropriate legal basis and safeguards for the child. The operator must complete and document that assessment before launch; accepting purchase terms is not blanket consent to unrelated processing.'],
 ['Who receives the data','OpenAI receives the supplied letter details and, for rewrites, previous text and editing preferences so it can generate the letter. Requests use the API with response storage disabled; this does not mean the provider has no security or other retention. Stripe receives payment and billing information. When email is enabled, the configured email provider handles the recipient address, private review link and accepted PDF. Hosting providers and authorised administrators can process data needed to operate and support the service. We may disclose information where legally required.'],
 ['Browser storage and external fonts','The draft and purchase-access token use session storage. The language preference uses local storage. Essential guest and login cookies provide access; guest cookies last up to 30 days, user sessions up to seven days and admin sessions up to eight hours. You can clear browser storage, but may lose a draft or access saved only in that browser. The site loads fonts from Google Fonts, which involves requests to Google and disclosure of technical data such as an IP address. Optional Google Analytics loads on public landing pages only after you accept analytics cookies. It measures visits and receives technical information such as your IP address and browser information. We do not load it on letter forms, private purchase pages or admin pages, and omit URL queries, fragments and referrers from configured page views. Advertising features are disabled. Analytics cookies (_ga and _ga_*) and your consent choice (elf-cookie-consent-v1 in local storage) last up to 180 days. Rejecting analytics does not affect purchases. Use Cookie settings on the landing page or letter app to change your choice; rejecting removes accessible analytics cookies and stops future collection. Withdrawal does not erase information already collected. Google processes analytics data; its storage locations and property retention settings must be included in the provider and retention details below.'],
 ['Retention and private links','Purchase inputs, letter versions, rewrite history and generated PDFs are retained in our database so the private purchase link can continue to work. The application does not currently delete them automatically after generation. The operator’s retention schedule below must specify the duration or criteria for letter data, purchase/tax records, logs and backups. A deletion request may end access to the letter; some records may need to be retained for legal reasons. Anyone with a complete private link can access the letter, so keep it confidential.'],
 ['Your rights and requests','Depending on applicable law, you may request access, correction, deletion, restriction, portability or object to certain processing. Where processing relies on consent, you can withdraw it without affecting earlier lawful processing. Contact us using the details above; we may need proportionate information to verify your request or authority to act for a child. Where the GDPR applies, you may complain to the relevant data-protection authority, including the authority where you live or work.'],
 ['Updates','We will update this notice when our processing changes. The version is shown above. New purposes, providers or retention rules must be reflected in the notice and, where required, communicated before they take effect.']
 ],
 de:[
 ['Angaben, die du übermittelst','Wir erhalten die E-Mail-Adresse der erwachsenen kaufenden Person, den Vornamen des Kindes, Wünsche, Erfolge und freiwillige Angaben zu Haustieren, Spielzeug oder einer Nachricht. Gespeichert werden außerdem Design, Sprache, erzeugte Briefe, Änderungswünsche, ausgeschlossene Themen, frühere Versionen, Bestätigungen und PDFs. Gib nur notwendige Informationen an, keine Adressen, Geburtsdaten, Schulnamen, Gesundheitsdaten oder sonstigen sensiblen Angaben über ein Kind.'],
 ['Bestell-, Zahlungs- und technische Daten','Wir speichern Bestellnummern, Zahlungsstatus, Zahlungsreferenzen, Preis und relevante Zeitpunkte. Stripe verarbeitet die Zahlung. Unsere Anwendung speichert keine vollständigen Kartennummern oder Kartenprüfcodes. Hosting- und Sicherheitsdienste können IP-Adressen, Anfrageinformationen und Betriebsprotokolle verarbeiten. Bei Nutzung eines Kontos speichern wir die E-Mail-Adresse und einen geschützten Passwort-Hash.'],
 ['Zwecke der Verarbeitung','Wir verwenden die Angaben zur Brieferstellung, Zahlungsabwicklung, privaten Bereitstellung, zum PDF-Download, für Überarbeitungen, aktivierte Zustell-E-Mails, Support, Missbrauchsprävention und gesetzliche Pflichten. Angaben aus Kinderbriefen verwenden wir nicht für Werbung.'],
 ['Rechtsgrundlagen bei Anwendung der DSGVO','Notwendige Bestell- und Kontaktdaten der erwachsenen Person dienen der Vertragserfüllung, gesetzlich erforderliche Unterlagen der Erfüllung rechtlicher Pflichten und verhältnismäßige Sicherheits- und Supportverarbeitung berechtigten Interessen. Die Verarbeitung von Kinderdaten für einen von Erwachsenen bestellten Brief benötigt eine passende Rechtsgrundlage und Schutzmaßnahmen. Der Betreiber muss diese Prüfung vor dem Start durchführen und dokumentieren. Die Zustimmung zu Kaufbedingungen ist keine pauschale Einwilligung in andere Verarbeitungen.'],
 ['Empfänger der Daten','OpenAI erhält die Briefangaben sowie bei Überarbeitungen den bisherigen Text und Änderungswünsche. Die Speicherung von Antworten über die API ist deaktiviert; dies bedeutet nicht, dass beim Anbieter keinerlei Sicherheits- oder sonstige Aufbewahrung stattfindet. Stripe erhält Zahlungs- und Rechnungsdaten. Bei aktiviertem E-Mail-Versand verarbeitet der E-Mail-Anbieter die Empfängeradresse, den privaten Link und die bestätigte PDF. Hosting-Anbieter und befugte Administratoren verarbeiten Daten für Betrieb und Support. Gesetzlich vorgeschriebene Offenlegungen bleiben möglich.'],
 ['Browserspeicher und externe Schriftarten','Entwurf und Zugangscode werden im Sitzungsspeicher gespeichert, die Spracheinstellung im lokalen Speicher. Notwendige Gast- und Anmelde-Cookies ermöglichen den Zugang. Gast-Cookies gelten bis zu 30 Tage, Nutzersitzungen bis zu sieben Tage und Admin-Sitzungen bis zu acht Stunden. Beim Löschen können Entwurf oder nur lokal gespeicherter Zugang verloren gehen. Google Fonts lädt Schriftarten und erhält dabei technische Daten wie die IP-Adresse. Optionales Google Analytics wird nur nach deiner Einwilligung auf öffentlichen Startseiten geladen, nicht auf Briefformularen, privaten Bestellseiten oder Admin-Seiten. Google erhält Besuchs- und technische Daten wie IP-Adresse und Browserinformationen. Konfigurierte Seitenaufrufe enthalten keine URL-Parameter, Fragmente oder Referrer; Werbefunktionen sind deaktiviert. Analyse-Cookies (_ga und _ga_*) und die Auswahl im lokalen Speicher (elf-cookie-consent-v1) gelten bis zu 180 Tage. Eine Ablehnung beeinträchtigt den Kauf nicht. Über Cookie-Einstellungen auf der Startseite oder in der Brief-App kannst du die Auswahl ändern; eine Ablehnung entfernt zugängliche Analyse-Cookies und stoppt weitere Erfassung, löscht aber keine bereits erhobenen Daten. Googles Verarbeitungsorte und die eingestellte Aufbewahrung sind unten bei Anbietern und Speicherfristen zu ergänzen.'],
 ['Aufbewahrung und private Links','Bestellangaben, Briefversionen, Änderungsverlauf und PDFs bleiben in der Datenbank, damit private Links funktionieren. Die Anwendung löscht sie nach der Erstellung derzeit nicht automatisch. Der unten stehende Aufbewahrungsplan muss Fristen oder Kriterien für Briefdaten, Bestell- und Steuerunterlagen, Protokolle und Sicherungen festlegen. Eine Löschung kann den Briefzugang beenden; gesetzlich erforderliche Unterlagen können länger aufbewahrt werden. Wer den vollständigen privaten Link hat, kann auf den Brief zugreifen.'],
 ['Deine Rechte','Je nach geltendem Recht kannst du Auskunft, Berichtigung, Löschung, Einschränkung oder Übertragung verlangen und bestimmten Verarbeitungen widersprechen. Eine Einwilligung kannst du mit Wirkung für die Zukunft widerrufen. Nutze den oben genannten Kontakt. Wir können angemessene Angaben zur Identitätsprüfung oder Vertretungsberechtigung für ein Kind verlangen. Bei Anwendung der DSGVO kannst du dich bei einer zuständigen Datenschutzaufsicht beschweren, etwa am Wohn- oder Arbeitsort.'],
 ['Änderungen','Bei Änderungen der Verarbeitung passen wir diese Erklärung an. Die Fassung steht oben. Neue Zwecke, Anbieter oder Fristen müssen berücksichtigt und gegebenenfalls vor ihrem Wirksamwerden mitgeteilt werden.']
 ],
 es:[
 ['Datos que facilitas','Recibimos el correo del comprador adulto, el nombre del menor, deseos, logros y datos opcionales sobre mascotas, juguetes o mensajes. Conservamos también el diseño, idioma, cartas generadas, instrucciones y exclusiones de revisión, versiones, aceptación y PDF. Facilita solo lo necesario. No incluyas direcciones, fechas de nacimiento, nombres de colegios, datos de salud u otra información sensible de un menor.'],
 ['Pedidos, pagos y datos técnicos','Guardamos referencias del pedido, estado y referencias del pago, precio y fechas relevantes. Stripe procesa el pago; nuestra aplicación no guarda números completos de tarjeta ni códigos de seguridad. La infraestructura de alojamiento y seguridad puede tratar direcciones IP, datos de solicitudes y registros operativos. Si utilizas una cuenta, guardamos el correo y un hash protegido de la contraseña.'],
 ['Para qué usamos los datos','Los usamos para crear la carta, cobrar, proporcionar acceso privado y descargas, tramitar revisiones, enviar correos cuando esté habilitado, atender consultas, evitar abusos y cumplir obligaciones legales. No usamos los detalles de la carta del menor para publicidad.'],
 ['Bases legales cuando se aplica el RGPD','Los datos necesarios del comprador adulto sirven para ejecutar el contrato; los registros exigidos por ley, para cumplir obligaciones legales; y el tratamiento proporcionado de seguridad y soporte, para intereses legítimos. Tratar datos de un menor para una carta encargada por un adulto requiere una base adecuada y garantías para el menor. El operador debe completar y documentar esta evaluación antes del lanzamiento. Aceptar condiciones de compra no es un consentimiento general para otros usos.'],
 ['Quién recibe los datos','OpenAI recibe los detalles de la carta y, para revisiones, el texto anterior y las preferencias. Usamos la API con el almacenamiento de respuestas desactivado; esto no significa que el proveedor no conserve datos por seguridad u otros motivos. Stripe recibe datos de pago y facturación. Si se activa el correo, su proveedor trata la dirección, el enlace privado y el PDF aceptado. El alojamiento y los administradores autorizados tratan datos necesarios para operar y dar soporte. Podemos comunicar datos cuando la ley lo exija.'],
 ['Almacenamiento del navegador y fuentes externas','El borrador y el código de acceso usan almacenamiento de sesión. El idioma usa almacenamiento local. Las cookies esenciales permiten el acceso: hasta 30 días para invitados, siete días para sesiones de usuario y ocho horas para administradores. Borrar el almacenamiento puede eliminar el borrador o el acceso guardado solo en ese navegador. Google Fonts recibe solicitudes y datos técnicos, como la IP, al cargar fuentes. Google Analytics opcional solo se carga con tu consentimiento en las páginas públicas de inicio, nunca en formularios de cartas, compras privadas ni administración. Google recibe datos de visitas y técnicos, como IP y navegador. Las visitas configuradas excluyen parámetros, fragmentos y referencias de URL; las funciones publicitarias están desactivadas. Las cookies de analítica (_ga y _ga_*) y tu elección en almacenamiento local (elf-cookie-consent-v1) duran hasta 180 días. Rechazar no afecta a las compras. Puedes cambiar tu elección en Ajustes de cookies en el inicio o la aplicación; rechazar elimina las cookies de analítica accesibles y detiene la recopilación futura, sin borrar datos ya recopilados. Los lugares de tratamiento de Google y la retención configurada deben detallarse abajo.'],
 ['Conservación y enlaces privados','Los datos de compra, versiones, revisiones y PDF permanecen en la base de datos para mantener el acceso privado. Actualmente no se borran automáticamente tras generar la carta. El plan indicado abajo debe definir plazos o criterios para cartas, pedidos y documentos fiscales, registros y copias de seguridad. La eliminación puede terminar el acceso; ciertas obligaciones legales exigen conservar registros. Quien tenga el enlace privado completo puede acceder a la carta.'],
 ['Tus derechos','Según la ley aplicable, puedes solicitar acceso, rectificación, eliminación, limitación, portabilidad u oponerte a ciertos tratamientos. Si el tratamiento se basa en consentimiento, puedes retirarlo sin afectar a su licitud anterior. Usa el contacto indicado arriba. Podemos pedir información proporcionada para verificar tu identidad o autoridad respecto de un menor. Bajo el RGPD puedes reclamar ante la autoridad de protección de datos competente, incluida la de tu residencia o trabajo.'],
 ['Cambios','Actualizaremos esta política cuando cambie el tratamiento. La versión figura arriba. Los nuevos fines, proveedores o plazos deben reflejarse y, cuando sea necesario, comunicarse antes de entrar en vigor.']
 ],
 fr:[
 ['Informations fournies','Nous recevons l’e-mail de l’acheteur adulte, le prénom de l’enfant, ses souhaits, réussites et les détails facultatifs sur un animal, jouet ou message. Nous conservons aussi le modèle, la langue, les lettres, consignes et exclusions de réécriture, versions, validation et PDF. Ne fournissez que les détails nécessaires, sans adresse, date de naissance, nom d’école, donnée de santé ou autre information sensible sur un enfant.'],
 ['Commandes, paiements et données techniques','Nous enregistrons les références de commande et de paiement, le statut, le prix et les dates utiles. Stripe traite le paiement ; notre application ne conserve pas les numéros complets de carte ni les cryptogrammes. L’hébergement et la sécurité peuvent traiter des adresses IP, informations de requête et journaux techniques. Si vous utilisez un compte, nous conservons l’e-mail et une empreinte protégée du mot de passe.'],
 ['Pourquoi nous utilisons ces données','Elles servent à créer la lettre, encaisser le paiement, fournir l’accès privé et les téléchargements, traiter les réécritures, envoyer les e-mails activés, répondre aux demandes, prévenir les abus et respecter la loi. Les détails de la lettre de l’enfant ne servent pas à la publicité.'],
 ['Bases juridiques lorsque le RGPD s’applique','Les données nécessaires de l’acheteur adulte servent à exécuter le contrat, les documents imposés par la loi à respecter les obligations légales, et les traitements proportionnés de sécurité et d’assistance aux intérêts légitimes. Les données d’un enfant pour une lettre commandée par un adulte nécessitent une base adaptée et des garanties pour l’enfant. L’exploitant doit effectuer et documenter cette analyse avant le lancement. Accepter des conditions d’achat ne vaut pas consentement général à d’autres traitements.'],
 ['Destinataires','OpenAI reçoit les détails de la lettre et, pour les réécritures, le texte précédent et les préférences. Nous utilisons l’API sans stockage des réponses ; cela ne signifie pas que le prestataire ne conserve aucune donnée à des fins de sécurité ou autres. Stripe reçoit les données de paiement et facturation. Lorsque l’e-mail est activé, son prestataire traite l’adresse, le lien privé et le PDF validé. L’hébergeur et les administrateurs autorisés traitent les données nécessaires au service. Des divulgations peuvent être exigées par la loi.'],
 ['Stockage du navigateur et polices externes','Le brouillon et le code d’accès utilisent le stockage de session ; la langue utilise le stockage local. Des cookies essentiels permettent l’accès : jusqu’à 30 jours pour les visiteurs, sept jours pour les utilisateurs et huit heures pour les administrateurs. Effacer ces données peut supprimer un brouillon ou un accès conservé uniquement dans ce navigateur. Google Fonts reçoit des requêtes et données techniques, telles que l’adresse IP, lors du chargement des polices. Google Analytics facultatif se charge uniquement après votre accord sur les pages publiques d’accueil, jamais dans les formulaires de lettres, achats privés ou pages d’administration. Google reçoit des données de visite et techniques, comme l’adresse IP et le navigateur. Les pages vues configurées excluent paramètres, fragments et référents des URL ; les fonctions publicitaires sont désactivées. Les cookies statistiques (_ga et _ga_*) et votre choix en stockage local (elf-cookie-consent-v1) durent jusqu’à 180 jours. Refuser ne gêne pas les achats. Modifiez votre choix via Paramètres des cookies sur l’accueil ou dans l’application ; refuser supprime les cookies statistiques accessibles et arrête la collecte future, sans effacer les données déjà collectées. Les lieux de traitement de Google et la conservation configurée doivent être précisés ci-dessous.'],
 ['Conservation et liens privés','Les données d’achat, versions, réécritures et PDF restent en base pour maintenir l’accès privé. L’application ne les efface actuellement pas automatiquement après génération. Le calendrier ci-dessous doit préciser les durées ou critères pour les lettres, commandes et documents fiscaux, journaux et sauvegardes. Une suppression peut mettre fin à l’accès ; certains documents doivent être conservés légalement. Toute personne disposant du lien privé complet peut accéder à la lettre.'],
 ['Vos droits','Selon la loi applicable, vous pouvez demander l’accès, la rectification, l’effacement, la limitation, la portabilité ou vous opposer à certains traitements. Vous pouvez retirer un consentement sans affecter les traitements antérieurs licites. Utilisez le contact ci-dessus. Nous pouvons demander des éléments proportionnés pour vérifier votre identité ou votre autorité pour un enfant. Le RGPD permet de saisir une autorité de protection des données compétente, notamment dans votre pays de résidence ou de travail.'],
 ['Mises à jour','Cette politique sera adaptée si les traitements changent. Sa version figure ci-dessus. Les nouveaux objectifs, prestataires ou durées doivent y apparaître et, si nécessaire, être communiqués avant leur application.']
 ]
};
const terms={
 en:[
 ['Who may order','You must be an adult able to enter a purchase contract and have authority to provide the child’s information. Please check names, language and supplied details before paying. Do not submit unlawful, abusive or sensitive content or information you are not entitled to share.'],
 ['What you buy and what it costs','One order covers one personalised Santa letter in the chosen design and language, as a downloadable PDF. The displayed price is US$3.99 for one letter, paid once through Stripe, with no subscription. Confirm the final amount and currency at checkout. Your bank may apply its own currency-conversion charges. Printing materials, a printer and postal delivery are not included.'],
 ['Generation, review and delivery','After confirmed payment, AI generates the letter using your details. You receive a private page to review it, request included changes, accept the current version and download the PDF. The current offer includes five rewrite requests. Email links and accepted PDFs are sent when email delivery is enabled. Generation or email may be delayed or fail; contact support if your paid letter is unavailable. The letters are fictional entertainment; AI may make mistakes and wording is not guaranteed to be exclusive. Read the letter before sharing it with a child.'],
 ['Using and keeping your PDF','You need a compatible browser, internet access and a PDF reader; printing requires your own printer or print service. Save the accepted PDF to your own device. Keep your private purchase link confidential because anyone with it can access and revise the letter. We provide the letter for personal and family use, including printing it as a gift, not resale of the service or artwork.'],
 ['Cancellations and refunds','There is nothing physical to return. Your cancellation and refund rights depend on applicable law. Where the EU/EEA distance-contract withdrawal right applies, the usual period is 14 days from conclusion of the contract, subject to applicable rules. This checkout does not ask you to waive that right: payment, requesting generation, accepting the wording or downloading the PDF is not treated by us as a waiver. Notify the support contact above with a clear statement and your order reference if you wish to withdraw. Where withdrawal is valid, we refund the amount due using the original payment method, without undue delay and within the applicable legal deadline (normally 14 days after notice for EU withdrawal). No physical return is required. We do not impose a blanket “no refunds for digital goods” rule.'],
 ['Faulty or undelivered letters','If the PDF cannot be accessed, is materially different from what was purchased, or otherwise fails applicable legal standards, contact support. You may be entitled to supply, correction, a price reduction or a refund under applicable law. The included rewrites do not replace these rights, and using all rewrites or accepting a version does not remove statutory remedies. Outside mandatory cancellation rights, contact us with the problem so we can assess it; no additional automatic change-of-mind guarantee is promised.'],
 ['Support, disputes and changes','Send purchase, cancellation and complaint requests to the support contact above. These terms do not exclude mandatory consumer protections, statutory remedies or rights to bring a claim in a court available under applicable law. The version accepted at checkout applies to that purchase; later updates do not retrospectively remove your rights.']
 ],
 de:[
 ['Wer bestellen darf','Du musst volljährig und zum Vertragsschluss berechtigt sein sowie die Angaben des Kindes übermitteln dürfen. Prüfe Namen, Sprache und Details vor der Zahlung. Übermittle keine rechtswidrigen, beleidigenden oder sensiblen Inhalte und keine Daten, die du nicht teilen darfst.'],
 ['Leistung und Preis','Eine Bestellung umfasst einen persönlichen Weihnachtsbrief im gewählten Design und in der gewählten Sprache als PDF. Der angezeigte Preis beträgt einmalig 3,99 US-Dollar pro Brief, zahlbar über Stripe, ohne Abo. Prüfe Endbetrag und Währung an der Kasse. Deine Bank kann eigene Umrechnungsgebühren berechnen. Druckmaterial, Drucker und Postversand sind nicht enthalten.'],
 ['Erstellung, Prüfung und Bereitstellung','Nach bestätigter Zahlung erstellt KI den Brief anhand deiner Angaben. Über eine private Seite kannst du ihn prüfen, enthaltene Änderungen wünschen, die aktuelle Version bestätigen und die PDF herunterladen. Das aktuelle Angebot umfasst fünf Überarbeitungen. E-Mail-Links und bestätigte PDFs werden bei aktiviertem E-Mail-Versand verschickt. Erstellung oder E-Mail können sich verzögern oder fehlschlagen; kontaktiere den Support, wenn dein bezahlter Brief fehlt. Die Briefe dienen fiktiver Unterhaltung. KI kann Fehler machen; eine exklusive Formulierung ist nicht garantiert. Lies den Brief, bevor du ihn einem Kind zeigst.'],
 ['PDF verwenden und aufbewahren','Du benötigst einen geeigneten Browser, Internetzugang und einen PDF-Reader. Drucker oder Druckservice organisierst du selbst. Speichere die bestätigte PDF auf deinem Gerät. Halte den privaten Link geheim, da jede Person mit diesem Link den Brief ansehen und überarbeiten kann. Der Brief ist für die persönliche und familiäre Nutzung einschließlich ausgedruckter Geschenke bestimmt, nicht zum Weiterverkauf des Dienstes oder der Illustrationen.'],
 ['Widerruf und Erstattungen','Es gibt keine körperliche Ware zurückzusenden. Deine Widerrufs- und Erstattungsrechte richten sich nach dem anwendbaren Recht. Soweit das EU-/EWR-Widerrufsrecht für Fernabsatzverträge gilt, beträgt die Frist nach den geltenden Regeln gewöhnlich 14 Tage ab Vertragsschluss. An dieser Kasse verlangen wir keinen Verzicht: Zahlung, Anforderung der Erstellung, Bestätigung des Textes oder PDF-Download behandeln wir nicht als Verzicht. Erkläre deinen Widerruf eindeutig gegenüber dem oben genannten Supportkontakt und nenne die Bestellnummer. Bei wirksamem Widerruf erstatten wir den geschuldeten Betrag über das ursprüngliche Zahlungsmittel unverzüglich und innerhalb der gesetzlichen Frist, bei EU-Widerruf normalerweise binnen 14 Tagen nach Mitteilung. Eine Rücksendung ist nicht nötig. Es gilt kein pauschaler Erstattungsausschluss für digitale Inhalte.'],
 ['Fehlerhafte oder nicht bereitgestellte Briefe','Kontaktiere den Support, wenn die PDF unzugänglich ist, wesentlich vom gekauften Produkt abweicht oder geltende gesetzliche Anforderungen nicht erfüllt. Je nach Recht können Bereitstellung, Nachbesserung, Preisminderung oder Erstattung zustehen. Überarbeitungen ersetzen diese Rechte nicht. Auch ausgeschöpfte Überarbeitungen oder eine bestätigte Version beseitigen keine gesetzlichen Ansprüche. Außerhalb zwingender Widerrufsrechte prüfen wir dein Anliegen individuell; eine zusätzliche automatische Erstattungsgarantie bei Meinungsänderung wird nicht zugesagt.'],
 ['Support, Streitigkeiten und Änderungen','Sende Bestell-, Widerrufs- und Beschwerdeanfragen an den oben genannten Kontakt. Zwingende Verbraucherrechte, gesetzliche Ansprüche und zuständige Gerichte werden nicht ausgeschlossen. Für den Kauf gilt die an der Kasse akzeptierte Fassung; spätere Änderungen nehmen dir nicht rückwirkend Rechte.']
 ],
 es:[
 ['Quién puede comprar','Debes ser adulto, poder contratar y estar autorizado para facilitar la información del menor. Revisa nombre, idioma y datos antes de pagar. No envíes contenido ilegal, abusivo o sensible ni datos que no puedas compartir.'],
 ['Producto y precio','Cada pedido incluye una carta personalizada con el diseño e idioma elegidos, en PDF descargable. El precio mostrado es de 3,99 USD por carta, en un único pago mediante Stripe y sin suscripción. Confirma importe y moneda al pagar. Tu banco puede aplicar comisiones de cambio. No se incluyen materiales, impresora ni envío postal.'],
 ['Creación, revisión y entrega','Tras confirmar el pago, la IA genera la carta con tus datos. En una página privada puedes revisarla, solicitar los cambios incluidos, aceptar la versión actual y descargar el PDF. La oferta actual incluye cinco revisiones. Los enlaces y PDF aceptados se envían si el correo está activado. La generación o el envío pueden retrasarse o fallar; contacta con soporte si tu carta pagada no está disponible. Son cartas de ficción para entretenimiento. La IA puede cometer errores y no se garantiza una redacción exclusiva. Léela antes de compartirla con un menor.'],
 ['Uso y conservación del PDF','Necesitas navegador compatible, conexión a internet y lector de PDF; la impresión requiere tu impresora o un servicio externo. Guarda el PDF en tu dispositivo. Mantén el enlace privado en secreto: quien lo tenga puede acceder y revisar la carta. Se permite el uso personal y familiar, incluida su impresión como regalo, no la reventa del servicio o las ilustraciones.'],
 ['Desistimiento y reembolsos','No hay ningún artículo físico que devolver. Los derechos de desistimiento y reembolso dependen de la ley aplicable. Cuando se aplica el desistimiento de contratos a distancia de la UE/EEE, el plazo habitual es de 14 días desde la celebración del contrato, según las reglas aplicables. Este pago no solicita que renuncies a ese derecho: no tratamos como renuncia el pago, pedir la generación, aceptar el texto ni descargar el PDF. Envía una declaración clara al contacto de soporte con tu referencia de pedido. Cuando proceda el desistimiento, reembolsaremos el importe debido por el método original, sin demora indebida y dentro del plazo legal, normalmente 14 días desde el aviso para el desistimiento de la UE. No hace falta devolución física. No aplicamos una prohibición general de reembolsos para productos digitales.'],
 ['Cartas defectuosas o no entregadas','Contacta con soporte si no puedes acceder al PDF, difiere sustancialmente de lo adquirido o incumple los requisitos legales. Puedes tener derecho al suministro, corrección, reducción del precio o reembolso. Las revisiones incluidas no sustituyen esos derechos; agotarlas o aceptar una versión no elimina los remedios legales. Fuera de los derechos obligatorios, contacta para que evaluemos el problema; no se promete una garantía automática adicional por cambio de opinión.'],
 ['Soporte, disputas y cambios','Envía las consultas de compra, desistimiento y reclamación al contacto indicado. Estas condiciones no excluyen la protección obligatoria, los remedios legales ni los tribunales disponibles por ley. La versión aceptada al pagar se aplica a esa compra; las modificaciones posteriores no eliminan derechos retroactivamente.']
 ],
 fr:[
 ['Qui peut commander','Vous devez être adulte, avoir la capacité de contracter et être autorisé à fournir les informations de l’enfant. Vérifiez le prénom, la langue et les détails avant le paiement. Ne transmettez pas de contenu illicite, abusif ou sensible, ni de données que vous n’êtes pas autorisé à partager.'],
 ['Produit et prix','Une commande correspond à une lettre personnalisée dans le modèle et la langue choisis, en PDF téléchargeable. Le prix affiché est de 3,99 USD par lettre, payé une seule fois via Stripe, sans abonnement. Confirmez le montant et la devise au paiement. Votre banque peut facturer une conversion. Le matériel d’impression, l’imprimante et l’envoi postal ne sont pas inclus.'],
 ['Création, vérification et fourniture','Après confirmation du paiement, l’IA génère la lettre avec vos informations. Une page privée permet de la vérifier, demander les modifications incluses, valider la version et télécharger le PDF. L’offre actuelle comprend cinq réécritures. Les liens et PDF validés sont envoyés si l’e-mail est activé. La génération ou l’envoi peuvent être retardés ou échouer ; contactez l’assistance si votre lettre payée est indisponible. Les lettres sont des fictions de divertissement. L’IA peut se tromper et l’exclusivité du texte n’est pas garantie. Lisez la lettre avant de la partager avec un enfant.'],
 ['Utilisation et conservation du PDF','Il faut un navigateur compatible, internet et un lecteur PDF. L’impression nécessite votre imprimante ou un service externe. Enregistrez le PDF sur votre appareil. Gardez le lien privé confidentiel : toute personne qui le possède peut accéder à la lettre et la modifier. L’usage est personnel et familial, y compris l’impression pour un cadeau, sans revente du service ou des illustrations.'],
 ['Rétractation et remboursements','Il n’y a aucun objet physique à renvoyer. Les droits de rétractation et remboursement dépendent de la loi applicable. Lorsque le droit de rétractation à distance de l’UE/EEE s’applique, le délai habituel est de 14 jours après la conclusion du contrat, selon les règles applicables. Ce paiement ne vous demande pas d’y renoncer : nous ne considérons ni le paiement, ni la demande de génération, ni la validation du texte, ni le téléchargement comme une renonciation. Envoyez une déclaration claire au contact d’assistance avec la référence de commande. En cas de rétractation valable, nous remboursons le montant dû par le moyen d’origine, sans retard injustifié et dans le délai légal, normalement 14 jours après notification pour la rétractation UE. Aucun retour physique n’est nécessaire. Nous n’appliquons pas d’interdiction générale de remboursement des produits numériques.'],
 ['Lettres non fournies ou défectueuses','Contactez l’assistance si le PDF est inaccessible, diffère substantiellement du produit acheté ou ne respecte pas les exigences légales. Vous pouvez avoir droit à la fourniture, correction, réduction du prix ou remboursement. Les réécritures ne remplacent pas ces droits ; les épuiser ou valider une version ne supprime pas les recours légaux. En dehors des droits obligatoires, contactez-nous pour examiner le problème ; aucune garantie automatique supplémentaire pour changement d’avis n’est promise.'],
 ['Assistance, litiges et modifications','Adressez les demandes d’achat, rétractation et réclamation au contact ci-dessus. Ces conditions n’excluent pas les protections impératives, recours légaux ni tribunaux accessibles selon la loi. La version acceptée lors du paiement s’applique à cet achat ; les changements ultérieurs ne retirent pas vos droits rétroactivement.']
 ]
};
export function policyData(type,language='en',config=legalConfig()){
 const code=localeCode(language),labels=copy[code];if(!['privacy','terms'].includes(type))throw new Error('Unknown policy');
 return {type,code,labels,title:labels[type],intro:type==='privacy'?labels.introPrivacy:labels.introTerms,sections:type==='privacy'?privacy[code]:terms[code],config,version:policyVersion};
}
export function policyBody(type,language,config){
 const data=policyData(type,language,config),{labels:l}=data,e=escapeHtml;
 const identity=['name','address','country','email'].map(key=>`<dt>${e(l[key])}</dt><dd>${key==='email'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(config.email)?`<a href="mailto:${e(config.email)}">${e(config.email)}</a>`:e(config[key]||l.missing)}</dd>`).join('');
 return `<header class="legal-header"><a class="logo" href="${languagePath(data.code)}">elf mailroom</a><a href="${languagePath(data.code)}">${e(l.home)}</a></header><main class="legal-page"><nav class="language-links" aria-label="Language">${languages.map(x=>`<a href="${legalPath(type,x.code)}" hreflang="${x.code}" lang="${x.code}"${x.code===data.code?' aria-current="page"':''}>${x.name}</a>`).join('')}</nav>${!config.ready?`<p class="legal-draft" role="status">${e(l.draft)}</p>`:''}<h1>${e(data.title)}</h1><p class="legal-version">${e(l.updated)}: ${policyVersion}</p><p>${e(data.intro)}</p><nav class="legal-tabs"><a href="${legalPath('privacy',data.code)}">${e(l.privacy)}</a><a href="${legalPath('terms',data.code)}">${e(l.terms)}</a><a href="${legalPath('terms',data.code)}#cancellation">${e(l.refunds)}</a></nav><section><h2>${e(l.seller)}</h2><dl>${identity}${config.abn?`<dt>ABN</dt><dd>${e(config.abn)}</dd>`:''}</dl><p>${e(l.contact)}</p></section>${data.sections.map(([title,text],i)=>`<section${type==='terms'&&i===4?' id="cancellation"':''}><h2>${e(title)}</h2><p>${e(text)}</p></section>`).join('')}${type==='privacy'?`<section><h2>${e(l.retention)}</h2><p>${e(config.retention||l.missing)}</p></section><section><h2>${e(l.providers)}</h2><p>${e(config.providers||l.missing)}</p></section>`:`<section><h2>${e(l.withdrawal)}</h2><p>${e(l.withdrawalText)}</p></section>`}</main>`;
}
export function policyDocument(type,language,config,{origin=defaultSiteUrl,stylesheet='/src/legal.css'}={}){
 const data=policyData(type,language,config),e=escapeHtml,base=siteOrigin(origin);
 return `<!doctype html><html lang="${data.code}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(data.title)} | Elf Mailroom</title><meta name="description" content="${e(data.intro)}"><meta name="robots" content="noindex,follow"><link rel="canonical" href="${e(base+legalPath(type,data.code))}"><link rel="stylesheet" href="${e(stylesheet)}"><link rel="icon" href="/favicon.svg"></head><body>${policyBody(type,data.code,config)}</body></html>`;
}
const australianPrivacy={
 en:['Australian privacy requests and complaints','You may ask Webz Australia for access to or correction of your personal information, or make a privacy complaint, using the contact above. Explain your concern so we can investigate and respond. Where the Australian Privacy Act applies, you can escalate an unresolved complaint to the Office of the Australian Information Commissioner (OAIC), subject to its complaint requirements. The operator must confirm whether the Act and other relevant privacy laws apply, and identify overseas recipient countries and safeguards in the provider information below.'],
 de:['Datenschutzanfragen und Beschwerden in Australien','Über den oben genannten Kontakt kannst du Webz Australia um Zugang zu deinen personenbezogenen Daten oder deren Berichtigung bitten und Datenschutzbeschwerden einreichen. Beschreibe dein Anliegen zur Prüfung. Soweit der australische Privacy Act gilt, kannst du eine ungelöste Beschwerde nach den geltenden Voraussetzungen an das Office of the Australian Information Commissioner (OAIC) richten. Der Betreiber muss die anwendbaren Datenschutzgesetze sowie Empfängerländer und Schutzmaßnahmen in den Anbieterangaben klären.'],
 es:['Solicitudes y reclamaciones de privacidad en Australia','Puedes solicitar a Webz Australia acceso o corrección de tus datos, o presentar una reclamación, mediante el contacto indicado. Explica el problema para investigarlo y responder. Cuando se aplique la Privacy Act australiana, puedes elevar una reclamación no resuelta al Office of the Australian Information Commissioner (OAIC), según sus requisitos. El operador debe confirmar las leyes aplicables y detallar los países receptores y garantías en la información de proveedores.'],
 fr:['Demandes et réclamations de confidentialité en Australie','Vous pouvez demander à Webz Australia l’accès ou la correction de vos données, ou déposer une réclamation, via le contact ci-dessus. Décrivez le problème pour permettre une enquête et une réponse. Lorsque la Privacy Act australienne s’applique, une réclamation non résolue peut être transmise à l’Office of the Australian Information Commissioner (OAIC), selon ses conditions. L’exploitant doit confirmer les lois applicables ainsi que les pays destinataires et garanties dans les informations sur les prestataires.']
};
const australianGuarantees={
 en:['Australian Consumer Law','Nothing in these terms excludes rights that cannot be excluded under the Australian Consumer Law. If a consumer guarantee is not met, the remedy depends on the nature and seriousness of the failure. A major failure may entitle you to choose a refund or replacement for goods, or cancellation and a refund for a service, and compensation for reasonably foreseeable loss where the law provides it. For a non-major failure, we may first provide an appropriate fix within a reasonable time. Simply changing your mind does not generally create a refund right under Australian Consumer Law. Any mandatory rights that apply in another country are also preserved.'],
 de:['Australisches Verbraucherrecht','Diese Bedingungen schließen keine unabdingbaren Rechte nach dem Australian Consumer Law aus. Bei Verletzung einer Verbrauchergarantie richtet sich die Abhilfe nach Art und Schwere des Fehlers. Ein wesentlicher Fehler kann zur Wahl zwischen Erstattung und Ersatz bei Waren beziehungsweise Kündigung und Erstattung bei Dienstleistungen sowie gesetzlichem Ersatz vorhersehbarer Schäden berechtigen. Bei kleineren Fehlern kann zunächst eine angemessene Behebung innerhalb angemessener Zeit erfolgen. Eine bloße Meinungsänderung begründet im Allgemeinen keinen Erstattungsanspruch nach australischem Recht. Zwingende Rechte anderer Länder bleiben erhalten.'],
 es:['Ley australiana de consumo','Estas condiciones no excluyen derechos irrenunciables bajo la Australian Consumer Law. El remedio por incumplir una garantía depende del tipo y gravedad del problema. Un fallo grave puede permitir elegir reembolso o sustitución para bienes, o cancelación y reembolso para servicios, y compensación de pérdidas previsibles cuando la ley lo prevea. Para fallos menores podemos ofrecer primero una solución en un plazo razonable. Cambiar de opinión no genera generalmente un derecho a reembolso bajo esta ley. Se conservan también los derechos obligatorios aplicables en otros países.'],
 fr:['Droit australien de la consommation','Ces conditions n’excluent aucun droit impératif au titre de l’Australian Consumer Law. Le recours dépend de la nature et de la gravité du défaut. Un défaut majeur peut permettre de choisir remboursement ou remplacement pour un bien, ou résiliation et remboursement pour un service, ainsi que l’indemnisation des pertes prévisibles prévue par la loi. Pour un défaut mineur, une correction adaptée peut d’abord être proposée dans un délai raisonnable. Un simple changement d’avis ne crée généralement pas de droit au remboursement selon cette loi. Les droits impératifs applicables dans d’autres pays sont également préservés.']
};
const internationalSales={
 en:['Worldwide digital orders','Webz Australia is based in Australia and offers digital letters to customers worldwide, subject to payment availability and applicable legal restrictions. The price is US$3.99 per letter, charged in US dollars; your bank or payment provider may apply currency conversion or fees. Letters are available in English, German, Spanish, French and Polish. Your purchase is a PDF to download and print yourself; no physical letter is posted. Mandatory consumer protections that apply in your country remain available, including applicable cancellation and refund rights described above.'],
 de:['Digitale Bestellungen weltweit','Webz Australia hat seinen Sitz in Australien und bietet digitale Briefe weltweit an, soweit die Zahlung möglich und der Verkauf gesetzlich zulässig ist. Der Preis beträgt 3,99 US-Dollar pro Brief und wird in US-Dollar abgerechnet; deine Bank oder dein Zahlungsanbieter kann Währungsumrechnungen oder Gebühren anwenden. Briefe sind auf Englisch, Deutsch, Spanisch, Französisch und Polnisch verfügbar. Du erhältst eine PDF zum Herunterladen und Selbstausdrucken; es wird kein Brief per Post verschickt. Zwingende Verbraucherrechte in deinem Land bleiben erhalten, einschließlich der oben beschriebenen anwendbaren Widerrufs- und Erstattungsrechte.'],
 es:['Pedidos digitales en todo el mundo','Webz Australia tiene su sede en Australia y ofrece cartas digitales a clientes de todo el mundo, sujeto a la disponibilidad de pago y las restricciones legales aplicables. El precio es de 3,99 dólares estadounidenses por carta y se cobra en esa moneda; tu banco o proveedor de pago puede aplicar conversión de divisas o comisiones. Las cartas están disponibles en inglés, alemán, español, francés y polaco. Recibes un PDF para descargar e imprimir; no se envía ninguna carta física por correo. Se mantienen las protecciones obligatorias del consumidor aplicables en tu país, incluidos los derechos de cancelación y reembolso descritos anteriormente.'],
 fr:['Commandes numériques dans le monde entier','Webz Australia est établie en Australie et propose des lettres numériques aux clients du monde entier, sous réserve de la disponibilité du paiement et des restrictions légales applicables. Le prix est de 3,99 dollars américains par lettre, facturés dans cette devise ; votre banque ou prestataire de paiement peut appliquer une conversion de devises ou des frais. Les lettres sont disponibles en anglais, allemand, espagnol, français et polonais. Votre achat est un PDF à télécharger et à imprimer vous-même ; aucune lettre physique n’est envoyée par la poste. Les protections impératives des consommateurs applicables dans votre pays restent garanties, notamment les droits de rétractation et de remboursement décrits ci-dessus.']
};
for(const{code}of languages.filter(x=>x.code!=='pl')){privacy[code].splice(3,0,australianPrivacy[code]);terms[code].push(australianGuarantees[code],internationalSales[code]);}

copy.pl=polishLabels;privacy.pl=polishPrivacy;terms.pl=polishTerms;

const retentionIndex=privacy.en.findIndex(([title])=>title==='Retention and private links');
for(const code of Object.keys(retentionCopy)){privacy[code][retentionIndex]=retentionCopy[code];terms[code].push(retentionCopy[code]);}
