// Polish translation of the existing draft policies; business details come from configuration.
export const polishLabels={
 privacy:'Polityka prywatności',terms:'Regulamin',refunds:'Anulowanie i zwroty',home:'Wróć do poczty elfów',draft:'Projekt — przed rozpoczęciem sprzedaży należy uzupełnić dane firmy, kontakt i informacje o przetwarzaniu danych.',updated:'Wersja dokumentu',seller:'Kto prowadzi Elf Mailroom',name:'Nazwa firmy',address:'Adres firmy',country:'Kraj siedziby',email:'Kontakt w sprawie obsługi i prywatności',missing:'Do uzupełnienia przed rozpoczęciem sprzedaży',introPrivacy:'Ten dokument opisuje, jak Elf Mailroom przetwarza dane służące do stworzenia i dostarczenia spersonalizowanego cyfrowego listu od Mikołaja. Usługa jest przeznaczona dla dorosłych zamawiających list dla dziecka.',introTerms:'Regulamin dotyczy spersonalizowanego cyfrowego listu od Mikołaja. Otrzymujesz PDF do pobrania i wydrukowania w domu. Nie wysyłamy pocztą papierowego listu, koperty ani innych przedmiotów.',retention:'Okresy przechowywania',providers:'Hosting, dostawcy poczty i przekazywanie danych za granicę',contact:'W razie potrzeby podaj numer zamówienia. Nie przesyłaj danych karty ani dodatkowych wrażliwych informacji o dziecku.',print:'Wydrukuj lub zapisz dokument',withdrawal:'Przykładowa wiadomość o odstąpieniu',withdrawalText:'Odstępuję od zakupu cyfrowego listu od Mikołaja. Numer zamówienia: ____. Data zakupu: ____. Imię i nazwisko oraz e-mail kupującego: ____. Data oświadczenia: ____. Wyślij wiadomość na wskazany powyżej adres obsługi. Użycie tego wzoru jest dobrowolne.'
};
export const polishPrivacy=[
 ['Dane, które podajesz','Otrzymujemy e-mail dorosłego kupującego, imię dziecka, jego życzenia, osiągnięcia oraz opcjonalne szczegóły o zwierzaku, zabawce lub treści wiadomości. Zapisujemy również wzór i język, wygenerowane listy, wskazówki i wykluczenia do zmian, historię wersji, zaakceptowaną wersję i pliki PDF. Podawaj wyłącznie dane potrzebne do listu. Nie przesyłaj adresów, dat urodzenia, nazw szkół, informacji o zdrowiu ani innych wrażliwych danych dziecka.'],
 ['Zamówienia, płatności i dane techniczne','Zapisujemy numery zamówień, status płatności, identyfikatory płatności, cenę i odpowiednie daty. Płatność obsługuje Stripe; aplikacja nie przechowuje pełnych numerów kart ani kodów zabezpieczających. Infrastruktura hostingowa i zabezpieczenia mogą przetwarzać adresy IP, dane żądań i dzienniki działania. W przypadku konta zapisujemy e-mail i zabezpieczony skrót hasła.'],
 ['Cele przetwarzania','Dane służą do stworzenia listu, przyjęcia płatności, zapewnienia prywatnego dostępu i pobierania PDF, wprowadzania zmian, wysyłki e-maili, jeśli jest włączona, obsługi zgłoszeń, zapobiegania nadużyciom i realizacji obowiązków prawnych. Nie wykorzystujemy szczegółów listu dziecka do reklam.'],
 ['Wnioski i skargi dotyczące prywatności w Australii','Możesz zwrócić się do Webz Australia o dostęp do danych, ich poprawienie lub rozpatrzenie skargi, korzystając z kontaktu powyżej. Opisz problem, abyśmy mogli go zbadać i odpowiedzieć. Jeśli ma zastosowanie australijska Privacy Act, nierozwiązaną skargę można skierować do Office of the Australian Information Commissioner (OAIC), zgodnie z jego wymaganiami. Operator musi ustalić zakres obowiązywania przepisów i wskazać kraje odbiorców danych oraz zabezpieczenia w informacjach o dostawcach poniżej.'],
 ['Podstawy prawne, gdy ma zastosowanie RODO','Niezbędne dane zamówienia i kontaktowe dorosłego kupującego przetwarzamy w celu wykonania umowy, wymagane prawem dokumenty — w celu realizacji obowiązków prawnych, a proporcjonalne działania związane z bezpieczeństwem i obsługą — na podstawie uzasadnionych interesów. Przetwarzanie danych dziecka w celu przygotowania listu zamówionego przez dorosłego wymaga odpowiedniej podstawy i zabezpieczeń. Przed uruchomieniem sprzedaży operator musi przeprowadzić i udokumentować tę ocenę. Akceptacja regulaminu nie jest ogólną zgodą na niezwiązane z zakupem przetwarzanie.'],
 ['Odbiorcy danych','OpenAI otrzymuje szczegóły listu, a przy zmianach także poprzednią treść i wskazówki redakcyjne. Żądania API wyłączają przechowywanie odpowiedzi, ale nie oznacza to braku przechowywania danych przez dostawcę dla bezpieczeństwa lub innych celów. Stripe otrzymuje dane płatnicze i rozliczeniowe. Przy włączonej wysyłce dostawca poczty przetwarza adres odbiorcy, prywatny link i zaakceptowany PDF. Hosting i upoważnieni administratorzy mogą przetwarzać dane potrzebne do działania i obsługi usługi. Dane mogą być ujawnione, jeśli wymaga tego prawo.'],
 ['Pamięć przeglądarki, pliki cookie i czcionki','Szkic i token dostępu są przechowywane w pamięci sesji, a język w pamięci lokalnej. Niezbędne pliki cookie zapewniają dostęp: dla gości do 30 dni, sesji użytkowników do siedmiu dni, a administratorów do ośmiu godzin. Wyczyszczenie pamięci może usunąć szkic lub dostęp zapisany tylko w tej przeglądarce. Google Fonts otrzymuje żądania i dane techniczne, takie jak IP, podczas ładowania czcionek. Opcjonalne Google Analytics ładuje się wyłącznie po zgodzie na publicznych stronach głównych, nigdy w formularzu listu, prywatnym zamówieniu ani panelu administratora. Otrzymuje dane o wizytach, IP i przeglądarce. Skonfigurowane odsłony pomijają parametry, fragmenty adresów i adres strony odsyłającej. Funkcje reklamowe są wyłączone. Pliki _ga i _ga_* oraz wybór zgody elf-cookie-consent-v1 w pamięci lokalnej są przechowywane do 180 dni. Odrzucenie nie wpływa na zakupy. Wybór zmienisz przez Ustawienia plików cookie na stronie głównej lub w aplikacji; odrzucenie usuwa dostępne analityczne pliki cookie i zatrzymuje przyszłe zbieranie danych, ale nie usuwa danych już zebranych. Miejsca przetwarzania przez Google i ustawienia retencji należy wskazać poniżej.'],
 ['Przechowywanie i prywatne linki','Dane zamówienia, wersje listu, historia zmian i PDF pozostają w bazie, aby prywatny link nadal działał. Aplikacja nie usuwa ich automatycznie po wygenerowaniu. Harmonogram poniżej musi określać okresy lub kryteria przechowywania danych listów, dokumentów zakupowych i podatkowych, dzienników i kopii zapasowych. Usunięcie danych może zakończyć dostęp do listu; część dokumentów może podlegać obowiązkowi zachowania. Każdy posiadacz pełnego prywatnego linku ma dostęp do listu, więc chroń ten link.'],
 ['Twoje prawa i wnioski','Zależnie od obowiązującego prawa możesz żądać dostępu, sprostowania, usunięcia, ograniczenia przetwarzania, przeniesienia danych lub wnieść sprzeciw. Zgodę można wycofać bez wpływu na zgodność wcześniejszego przetwarzania z prawem. Skontaktuj się z nami; możemy poprosić o proporcjonalne informacje potwierdzające tożsamość lub uprawnienie do działania za dziecko. Gdy obowiązuje RODO, możesz złożyć skargę do właściwego organu ochrony danych, w tym w miejscu zamieszkania lub pracy.'],
 ['Zmiany dokumentu','Aktualizujemy dokument, gdy zmienia się przetwarzanie. Wersja widnieje powyżej. Nowe cele, dostawcy lub okresy przechowywania muszą znaleźć odzwierciedlenie w polityce, a tam, gdzie wymagają tego przepisy, zostać zakomunikowane przed wejściem w życie.']
];
export const polishTerms=[
 ['Kto może zamówić','Musisz być osobą dorosłą uprawnioną do zawarcia umowy i podania danych dziecka. Przed zapłatą sprawdź imię, język i szczegóły. Nie przesyłaj treści niezgodnych z prawem, obraźliwych, wrażliwych ani danych, których nie masz prawa udostępniać.'],
 ['Przedmiot zakupu i cena','Jedno zamówienie obejmuje jeden spersonalizowany list od Mikołaja w wybranym wzorze i języku jako PDF do pobrania. Cena wynosi jednorazowo 3,99 USD, płatne przez Stripe, bez abonamentu. Sprawdź końcową kwotę i walutę przy płatności. Bank może naliczyć opłaty za przewalutowanie. Papier, drukarka i wysyłka pocztowa nie są wliczone.'],
 ['Tworzenie, sprawdzanie i dostarczenie','Po potwierdzeniu płatności AI tworzy list na podstawie podanych danych. Na prywatnej stronie możesz go przeczytać, poprosić o zmiany w cenie, zaakceptować aktualną wersję i pobrać PDF. Oferta obejmuje pięć próśb o zmianę treści. Linki i zaakceptowane PDF wysyłamy e-mailem, gdy wysyłka jest włączona. Tworzenie i wysyłka mogą się opóźnić lub nie powieść; jeśli opłacony list jest niedostępny, skontaktuj się z obsługą. Listy są fikcyjną rozrywką. AI może popełniać błędy i nie gwarantujemy wyłączności sformułowań. Przeczytaj list przed pokazaniem go dziecku.'],
 ['Korzystanie z PDF i jego zachowanie','Potrzebujesz zgodnej przeglądarki, internetu i czytnika PDF, a do druku własnej drukarki lub usługi drukowania. Zapisz zaakceptowany PDF na swoim urządzeniu. Chroń prywatny link, ponieważ każdy jego posiadacz może przeglądać i zmieniać list. List jest do użytku osobistego i rodzinnego, również jako wydrukowany prezent, a nie do odsprzedaży usługi lub ilustracji.'],
 ['Anulowanie i zwroty','Nie ma fizycznego przedmiotu do zwrotu. Prawa do anulowania i zwrotu zależą od właściwych przepisów. Jeśli ma zastosowanie prawo odstąpienia od umowy zawartej na odległość w UE/EOG, zwykły termin wynosi 14 dni od zawarcia umowy, z uwzględnieniem odpowiednich zasad. Nasza płatność nie wymaga zrzeczenia się tego prawa: zapłaty, prośby o wygenerowanie, akceptacji treści ani pobrania PDF nie traktujemy jako takiego zrzeczenia. Aby odstąpić, wyślij jednoznaczne oświadczenie z numerem zamówienia do obsługi wskazanej powyżej. Przy skutecznym odstąpieniu zwracamy należną kwotę pierwotną metodą płatności bez zbędnej zwłoki i w ustawowym terminie (zwykle 14 dni od powiadomienia dla odstąpienia w UE). Zwrot fizyczny nie jest wymagany. Nie stosujemy ogólnej zasady „brak zwrotów za produkty cyfrowe”.'],
 ['Wadliwy lub niedostarczony list','Jeśli PDF jest niedostępny, istotnie różni się od zakupionego produktu lub nie spełnia obowiązujących standardów prawnych, skontaktuj się z obsługą. Możesz mieć prawo do dostarczenia, poprawienia, obniżenia ceny lub zwrotu. Zmiany w cenie nie zastępują tych praw, a ich wykorzystanie lub akceptacja wersji nie usuwa ustawowych środków ochrony. Poza obowiązkowymi prawami do odstąpienia opisz problem, abyśmy mogli go ocenić; nie obiecujemy dodatkowej automatycznej gwarancji zwrotu po zmianie zdania.'],
 ['Obsługa, spory i zmiany','Zapytania o zakup, odstąpienie i reklamacje kieruj do obsługi wskazanej powyżej. Regulamin nie wyłącza obowiązkowej ochrony konsumenta, ustawowych roszczeń ani prawa do właściwego sądu. Do zakupu stosuje się wersję zaakceptowaną przy płatności; późniejsze zmiany nie odbierają praw wstecz.'],
 ['Australijskie prawo konsumenckie','Regulamin nie wyłącza niezbywalnych praw wynikających z Australian Consumer Law. Środek ochrony zależy od charakteru i wagi naruszenia gwarancji konsumenckiej. Poważna wada może uprawniać do wyboru zwrotu lub wymiany towaru, anulowania i zwrotu za usługę oraz odszkodowania za racjonalnie przewidywalną szkodę, jeśli przewiduje to prawo. Przy mniejszych wadach możemy najpierw zapewnić odpowiednią naprawę w rozsądnym czasie. Sama zmiana zdania co do zasady nie daje prawa do zwrotu na podstawie tego prawa. Zachowane są też obowiązkowe prawa innych krajów.'],
 ['Zamówienia cyfrowe na całym świecie','Webz Australia ma siedzibę w Australii i oferuje cyfrowe listy na całym świecie, z uwzględnieniem dostępności płatności i ograniczeń prawnych. Cena wynosi 3,99 USD za list, pobierane w dolarach amerykańskich; bank lub dostawca płatności może naliczyć przewalutowanie lub opłaty. Dostępne języki to angielski, niemiecki, hiszpański, francuski i polski. Kupujesz PDF do samodzielnego pobrania i wydrukowania; nie wysyłamy papierowego listu. Obowiązkowe prawa konsumenta w Twoim kraju pozostają zachowane, w tym opisane wyżej prawa do odstąpienia i zwrotu.']
];
