export const languages = [{code:'en',name:'English',prompt:'British English'},{code:'de',name:'Deutsch',prompt:'German'},{code:'es',name:'Español',prompt:'Spanish'},{code:'fr',name:'Français',prompt:'French'},{code:'pl',name:'Polski',prompt:'Polish'}];
export const letterLanguages = [
 {code:'en-GB',name:'🇬🇧 English (UK)',prompt:'British English'},
 {code:'en-US',name:'🇺🇸 English (US)',prompt:'American English'},
 {code:'en-AU',name:'🇦🇺 English (Australia)',prompt:'Australian English'},
 ...languages.filter(x=>x.code!=='en')
];
export const localeCode = code => languages.some(x=>x.code===code)?code:'en';
export const letterLocaleCode = code => code?.startsWith('en-')||code==='en'?'en':localeCode(code);
export const letterLanguageCode = code => code==='en'?'en-GB':letterLanguages.some(x=>x.code===code)?code:'en-GB';
export const stationery = {
 pl:{desk:'Z BIURKA',santa:'Święty Mikołaj',post:'BIEGUN PÓŁNOCNY · POCZTA ŚWIĄTECZNA',footer:'ODROBINA MAGII Z BIEGUNA PÓŁNOCNEGO, TYLKO DLA CIEBIE',greeting:name=>`Cześć, ${name}!`,watermark:'PODGLĄD · ELF MAILROOM'},
 en:{desk:'FROM THE DESK OF',santa:'Santa Claus',post:'NORTH POLE · CHRISTMAS POST',footer:'A LITTLE NORTH POLE MAGIC, JUST FOR YOU',greeting:name=>`Dear ${name},`,watermark:'PREVIEW · ELF MAILROOM'},
 de:{desk:'VOM SCHREIBTISCH DES',santa:'Weihnachtsmanns',signature:'Dein Weihnachtsmann',post:'NORDPOL · WEIHNACHTSPOST',footer:'EIN WENIG NORDPOLZAUBER, NUR FÜR DICH',greeting:name=>`Hallo ${name},`,watermark:'VORSCHAU · ELF MAILROOM'},
 es:{desk:'DESDE EL ESCRITORIO DE',santa:'Papá Noel',post:'POLO NORTE · CORREO NAVIDEÑO',footer:'UN POQUITO DE MAGIA DEL POLO NORTE PARA TI',greeting:name=>`¡Hola, ${name}!`,watermark:'VISTA PREVIA · ELF MAILROOM'},
 fr:{desk:'DU BUREAU DU',santa:'Père Noël',post:'PÔLE NORD · COURRIER DE NOËL',footer:'UN PEU DE MAGIE DU PÔLE NORD, JUSTE POUR TOI',greeting:name=>`Bonjour ${name},`,watermark:'APERÇU · ELF MAILROOM'}
};
const sampleBodies={
 pl:'Twój list dotarł na biegun północny! Elfy położyły go obok mojego kubka gorącej czekolady. Czytałem go z uśmiechem.\n\nSłyszałem o Twoich wspaniałych przygodach w tym roku. Odkrywaj świat, próbuj nowych rzeczy i dziel się życzliwością z ludźmi wokół Ciebie.\n\nRenifery ćwiczą lądowanie, a warsztat jest pełen niespodzianek. Wszyscy szykujemy się na naprawdę magiczne święta!\n\nPrzesyłam wielki, śnieżny uścisk,',
 en:'Your letter has arrived at the North Pole! The elves placed it beside my hot chocolate, and reading it made me smile.\n\nI heard about your wonderful adventures this year. Keep being curious, trying new things and sharing your kindness with the people around you.\n\nThe reindeer are practising their landings and the workshop is full of surprises. We’re all getting ready for a very magical Christmas!\n\nWith a big, snowy hug,',
 de:'Dein Brief ist am Nordpol angekommen! Die Wichtel haben ihn neben meine heiße Schokolade gelegt. Beim Lesen musste ich lächeln.\n\nIch habe von deinen wunderbaren Abenteuern in diesem Jahr gehört. Bleib neugierig, probiere Neues aus und schenke den Menschen um dich herum deine Freundlichkeit.\n\nDie Rentiere üben ihre Landungen und die Werkstatt steckt voller Überraschungen. Wir bereiten uns alle auf ein zauberhaftes Weihnachtsfest vor!\n\nMit einer großen, schneeweißen Umarmung,',
 es:'¡Tu carta ha llegado al Polo Norte! Los elfos la dejaron junto a mi chocolate caliente y me hizo sonreír al leerla.\n\nMe he enterado de tus maravillosas aventuras de este año. Sigue descubriendo cosas nuevas, probando nuevos retos y compartiendo tu cariño con quienes te rodean.\n\nLos renos están practicando sus aterrizajes y el taller está lleno de sorpresas. ¡Todos nos preparamos para una Navidad muy mágica!\n\nCon un abrazo enorme y nevado,',
 fr:'Ta lettre est arrivée au pôle Nord ! Les lutins l’ont posée à côté de mon chocolat chaud, et elle m’a donné le sourire.\n\nJ’ai entendu parler de tes merveilleuses aventures de cette année. Garde ta curiosité, essaie de nouvelles choses et partage ta gentillesse avec les personnes qui t’entourent.\n\nLes rennes s’entraînent à atterrir et l’atelier déborde de surprises. Nous préparons tous un Noël vraiment magique !\n\nAvec un gros câlin tout enneigé,'
};
export function localizedSample(language='en',name='Sophie'){const code=localeCode(language);return `${stationery[code].greeting(name)}\n\n${sampleBodies[code]}`;}
// Shared by React and transactional email. English keys remain readable at call sites.
const rows=`
Cancellations and refunds|Widerruf und Erstattungen|Desistimiento y reembolsos|Rétractation et remboursements|Anulowanie i zwroty
How much does a personalised Santa letter cost?|Was kostet ein persönlicher Weihnachtsbrief?|¿Cuánto cuesta una carta personalizada de Papá Noel?|Combien coûte une lettre personnalisée du Père Noël ?|Ile kosztuje spersonalizowany list od Mikołaja?
Each letter costs US$3.99, paid once. It includes your chosen design, five rewrite requests and a PDF to download and print. There is no subscription.|Jeder Brief kostet einmalig 3,99 US-Dollar. Enthalten sind dein Wunschdesign, fünf Überarbeitungen und eine PDF zum Ausdrucken. Es gibt kein Abo.|Cada carta cuesta 3,99 USD en un único pago. Incluye el diseño elegido, cinco revisiones y un PDF para descargar e imprimir. No hay suscripción.|Chaque lettre coûte 3,99 USD, en un seul paiement. Le prix inclut le modèle choisi, cinq réécritures et un PDF à télécharger et imprimer. Sans abonnement.|Każdy list kosztuje jednorazowo 3,99 USD. Cena obejmuje wybrany wzór, pięć próśb o zmianę treści oraz PDF do pobrania i wydrukowania. Bez abonamentu.
When can I download my Santa letter?|Wann kann ich meinen Weihnachtsbrief herunterladen?|¿Cuándo puedo descargar mi carta de Papá Noel?|Quand puis-je télécharger ma lettre du Père Noël ?|Kiedy mogę pobrać list od Mikołaja?
After payment is confirmed, your letter is generated and appears on your private purchase page. Review it, request changes if needed, then accept it to download the PDF.|Nach Bestätigung der Zahlung wird dein Brief erstellt und auf deiner privaten Bestellseite angezeigt. Prüfe ihn, wünsche bei Bedarf Änderungen und bestätige ihn, um die PDF herunterzuladen.|Tras confirmar el pago, se genera tu carta y aparece en tu página privada. Revísala, pide cambios si los necesitas y acéptala para descargar el PDF.|Après confirmation du paiement, votre lettre est générée et apparaît sur votre page privée. Vérifiez-la, demandez des modifications si nécessaire, puis validez-la pour télécharger le PDF.|Po potwierdzeniu płatności list zostanie wygenerowany i pojawi się na prywatnej stronie zamówienia. Przeczytaj go, poproś o zmiany, jeśli chcesz, a następnie zaakceptuj i pobierz PDF.
Choose from six illustrated designs, including Santa at the beach and a kangaroo Christmas BBQ.|Wähle aus sechs illustrierten Designs, darunter Weihnachten am Strand und ein Weihnachtsgrillen mit Kängurus.|Elige entre seis diseños ilustrados, con Papá Noel en la playa y una barbacoa navideña con canguros.|Choisissez parmi six modèles illustrés, dont le Père Noël à la plage et un barbecue de Noël avec des kangourous.|Wybierz jeden z sześciu ilustrowanych wzorów, w tym Mikołaja na plaży i świątecznego grilla z kangurami.
Your letter is created with AI from the details you choose to share. You review the words before downloading.|Dein Brief wird mithilfe von KI aus deinen Angaben erstellt. Du prüfst den Text vor dem Herunterladen.|Tu carta se crea con IA a partir de los detalles que compartes. Tú revisas el texto antes de descargarla.|Votre lettre est créée avec l’IA à partir des détails que vous partagez. Vous vérifiez le texte avant de la télécharger.|List powstaje przy pomocy AI na podstawie udostępnionych przez Ciebie szczegółów. Przed pobraniem sprawdzasz jego treść.
Choose your language|Sprache wählen|Elige tu idioma|Choisissez votre langue|Wybierz język
Receive it as a digital PDF to download and print at home. Nothing is sent by post.|Du erhältst den Brief als digitale PDF zum Herunterladen und Ausdrucken zu Hause. Es wird nichts per Post verschickt.|Recíbela como PDF digital para descargar e imprimir en casa. No se envía nada por correo postal.|Recevez votre lettre au format PDF à télécharger et imprimer chez vous. Aucun envoi par la poste.|Otrzymasz cyfrowy PDF do pobrania i wydrukowania w domu. Niczego nie wysyłamy pocztą.
Website language|Sprache der Website|Idioma de la web|Langue du site|Język strony
Letter language|Sprache des Briefes|Idioma de la carta|Langue de la lettre|Język listu
Digital PDF only. Download and print at home. No physical letter will be posted.|Nur als digitale PDF. Zu Hause herunterladen und ausdrucken. Es wird kein Brief per Post verschickt.|Solo PDF digital. Descárgalo e imprímelo en casa. No enviamos cartas físicas por correo.|PDF numérique uniquement. À télécharger et imprimer chez vous. Aucune lettre physique ne sera envoyée.|Tylko cyfrowy PDF. Pobierz i wydrukuj w domu. Nie wysyłamy papierowego listu pocztą.
THE NORTH POLE POSTAL SERVICE|DIE WEIHNACHTSPOST VOM NORDPOL|EL CORREO DEL POLO NORTE|LE COURRIER DU PÔLE NORD|POCZTA BIEGUNA PÓŁNOCNEGO
Back to the mailroom|Zurück zur Wichtelpost|Volver al correo navideño|Retour au courrier de Noël|Wróć do poczty elfów
How it works|So funktioniert’s|Cómo funciona|Comment ça marche|Jak to działa
The letters|Die Briefe|Las cartas|Les lettres|Listy
For parents|Für Eltern|Para las familias|Pour les parents|Dla rodziców
FAQs|Fragen|Preguntas frecuentes|Questions fréquentes|Pytania i odpowiedzi
Write to Santa|An den Weihnachtsmann schreiben|Escribir a Papá Noel|Écrire au Père Noël|Napisz do Mikołaja
Write a letter to Santa|Einen Brief an den Weihnachtsmann schreiben|Escribir una carta a Papá Noel|Écrire une lettre au Père Noël|Napisz list do Mikołaja
A little letter. A whole lot of Christmas magic.|Ein kleiner Brief. Ganz viel Weihnachtszauber.|Una pequeña carta. Mucha magia navideña.|Une petite lettre. Toute la magie de Noël.|Mały list. Całe mnóstwo świątecznej magii.
Santa’s mailroom is open.|Die Weihnachtspost ist geöffnet.|El correo de Papá Noel está abierto.|Le courrier du Père Noël est ouvert.|Poczta Mikołaja jest otwarta.
Help your child write to Santa and receive a magical, personalised reply made just for them.|Hilf deinem Kind, dem Weihnachtsmann zu schreiben – für eine zauberhafte Antwort nur für dein Kind.|Ayuda a tu peque a escribir a Papá Noel y recibe una respuesta mágica y personalizada.|Aidez votre enfant à écrire au Père Noël et recevez une réponse magique, rien que pour lui.|Pomóż dziecku napisać do Mikołaja i otrzymaj magiczną, osobistą odpowiedź przygotowaną specjalnie dla niego.
See how it works|So geht’s|Descubre cómo funciona|Découvrir le fonctionnement|Zobacz, jak to działa
Made for little believers. Loved by grown-ups.|Für kleine Weihnachtsfans. Von Großen geliebt.|Para pequeños soñadores. Con el cariño de los mayores.|Pour les petits rêveurs. Approuvé par les grands.|Dla małych marzycieli. Z miłością od dorosłych.
Four little steps. One big smile.|Vier kleine Schritte. Ein großes Lächeln.|Cuatro pasitos. Una gran sonrisa.|Quatre petites étapes. Un grand sourire.|Cztery małe kroki. Jeden wielki uśmiech.
You bring the wishes. We’ll bring the Christmas magic.|Du bringst die Wünsche mit. Wir den Weihnachtszauber.|Tú traes los deseos. Nosotros, la magia navideña.|Vous apportez les souhaits. Nous, la magie de Noël.|Ty przynosisz życzenia. My dodajemy świąteczną magię.
Tell their story|Erzähle von deinem Kind|Cuéntanos su historia|Racontez son histoire|Opowiedz o dziecku
Add their name, wishes and little details for Santa’s personal reply.|Name, Wünsche und kleine Details für eine persönliche Antwort.|Añade su nombre, deseos y pequeños detalles para una respuesta personal.|Ajoutez son prénom, ses souhaits et ses petites particularités.|Dodaj imię, życzenia i drobne szczegóły, aby Mikołaj mógł napisać osobistą odpowiedź.
Pick their stationery|Wähle das Briefpapier|Elige el diseño|Choisissez le papier|Wybierz papier listowy
Explore illustrated designs with a sample letter, then choose their favourite.|Entdecke illustrierte Designs mit einem Musterbrief.|Explora los diseños ilustrados con una carta de ejemplo.|Découvrez les modèles illustrés avec une lettre d’exemple.|Obejrzyj ilustrowane wzory z przykładowym listem i wybierz ulubiony.
Pay securely|Sicher bezahlen|Paga con seguridad|Payez en toute sécurité|Zapłać bezpiecznie
One payment. No account or subscription needed.|Eine Zahlung. Kein Konto oder Abo nötig.|Un solo pago. Sin cuenta ni suscripción.|Un seul paiement. Sans compte ni abonnement.|Jedna płatność. Bez konta i abonamentu.
Review, download and print|Prüfen, herunterladen und ausdrucken|Revisa, descarga e imprime|Vérifiez, téléchargez et imprimez|Przeczytaj, pobierz i wydrukuj
Request changes, accept the letter, then print your PDF at home.|Änderungen wünschen, Brief bestätigen und die PDF zu Hause ausdrucken.|Pide cambios, acepta la carta e imprime el PDF en casa.|Demandez des modifications, validez la lettre et imprimez le PDF chez vous.|Poproś o zmiany, zaakceptuj list i wydrukuj PDF w domu.
A little peek at the magic · Fictional example|Ein kleiner Einblick · Fiktives Beispiel|Un vistazo a la magia · Ejemplo ficticio|Un aperçu de la magie · Exemple fictif|Odrobina magii na próbę · Fikcyjny przykład
{name}’s letter|Brief für {name}|Carta de {name}|Lettre de {name}|List dla: {name}
A letter that feels like theirs.|Ein Brief ganz für dein Kind.|Una carta hecha para tu peque.|Une lettre qui lui ressemble.|List stworzony właśnie dla Twojego dziecka.
Their favourite toy. A brave little moment. That very special Christmas wish.|Das Lieblingsspielzeug. Ein mutiger Moment. Ein ganz besonderer Weihnachtswunsch.|Su juguete favorito. Un momento de valentía. Ese deseo tan especial.|Son jouet préféré. Un petit moment de courage. Ce souhait si particulier.|Ulubiona zabawka. Mały akt odwagi. Wyjątkowe świąteczne życzenie.
Choose English, German, Spanish, French or Polish for their letter.|Wähle Englisch, Deutsch, Spanisch, Französisch oder Polnisch für den Brief.|Elige inglés, alemán, español, francés o polaco para su carta.|Choisissez l’anglais, l’allemand, l’espagnol, le français ou le polonais pour sa lettre.|Wybierz list po angielsku, niemiecku, hiszpańsku, francusku lub polsku.
Create my child’s letter|Brief für mein Kind gestalten|Crear la carta de mi peque|Créer la lettre de mon enfant|Stwórz list dla mojego dziecka
A little magic. A lot of care.|Ein wenig Magie. Ganz viel Sorgfalt.|Un poco de magia. Mucho cariño.|Un peu de magie. Beaucoup d’attention.|Trochę magii. Mnóstwo troski.
You’re in charge|Du entscheidest|Tú decides|Vous décidez|Ty decydujesz
Choose the details you share and check them before you pay.|Wähle deine Angaben und prüfe sie vor der Zahlung.|Elige qué compartir y revísalo antes de pagar.|Choisissez les informations à partager et vérifiez-les avant de payer.|Wybierz, co chcesz udostępnić, i sprawdź szczegóły przed zapłatą.
Make it just right|Genau so, wie du möchtest|Hazla a su medida|Pour une lettre parfaite|Dopracuj każdy szczegół
Ask for a different tone or tell us what to leave out before accepting.|Wünsche dir einen anderen Ton oder sage, was weggelassen werden soll.|Pide otro tono o indica qué omitir antes de aceptar.|Demandez un autre ton ou précisez quoi omettre avant de valider.|Poproś o inny ton lub wskaż, co pominąć, zanim zaakceptujesz list.
A keepsake to print at home|Ein Andenken zum Selbstausdrucken|Un recuerdo para imprimir en casa|Un souvenir à imprimer chez vous|Pamiątka do wydrukowania w domu
Personalised Santa Letter|Persönlicher Weihnachtsbrief|Carta personalizada de Papá Noel|Lettre personnalisée du Père Noël|Spersonalizowany list od Mikołaja
Six illustrated themes|Sechs illustrierte Themen|Seis temas ilustrados|Six thèmes illustrés|Sześć ilustrowanych motywów
Five rewrite requests included|Fünf Überarbeitungen inklusive|Cinco solicitudes de revisión incluidas|Cinq demandes de réécriture incluses|Pięć próśb o zmianę treści w cenie
A downloadable, print-ready PDF|Eine druckfertige PDF zum Herunterladen|Un PDF descargable listo para imprimir|Un PDF à télécharger et imprimer|PDF gotowy do pobrania i wydrukowania
Personalise your letter|Deinen Brief gestalten|Personaliza tu carta|Personnalisez votre lettre|Spersonalizuj swój list
One-time payment per letter · No subscription.|Einmalzahlung pro Brief · Kein Abo.|Un pago por carta · Sin suscripción.|Paiement unique par lettre · Sans abonnement.|Jednorazowa płatność za list · Bez abonamentu.
Grown-up questions, answered.|Antworten für die Großen.|Respuestas para los mayores.|Les réponses aux questions des grands.|Odpowiedzi na pytania dorosłych.
Is the letter really personalised?|Ist der Brief wirklich persönlich?|¿La carta es personalizada?|La lettre est-elle vraiment personnalisée ?|Czy list naprawdę jest spersonalizowany?
Yes. After payment, a fresh letter is written using the details you provide. Before payment, previews contain fictional sample text.|Ja. Nach der Zahlung entsteht ein neuer Brief mit deinen Angaben. Vor der Zahlung zeigen wir einen fiktiven Mustertext.|Sí. Tras el pago se crea una carta nueva con tus datos. Antes de pagar, las vistas previas muestran un ejemplo ficticio.|Oui. Après le paiement, une nouvelle lettre est rédigée à partir de vos informations. Avant le paiement, l’aperçu présente un exemple fictif.|Tak. Po zapłacie powstaje nowy list na podstawie podanych szczegółów. Przed zapłatą podglądy zawierają fikcyjną, przykładową treść.
Will you send a letter in the post?|Wird ein Brief per Post verschickt?|¿Enviáis una carta por correo postal?|Envoyez-vous une lettre par la poste ?|Czy wyślecie list pocztą?
Can I ask for changes?|Kann ich Änderungen wünschen?|¿Puedo pedir cambios?|Puis-je demander des modifications ?|Czy mogę poprosić o zmiany?
Yes. Review your letter after payment and request up to five rewrites with your preferences or topics to avoid. Accept it to download the clean PDF.|Ja. Prüfe den Brief nach der Zahlung und wünsche bis zu fünf Überarbeitungen mit deinen Vorlieben oder unerwünschten Themen. Bestätige ihn für die PDF ohne Wasserzeichen.|Sí. Revisa la carta tras el pago y pide hasta cinco cambios con tus preferencias o temas que evitar. Acéptala para descargar el PDF sin marca de agua.|Oui. Après le paiement, demandez jusqu’à cinq réécritures avec vos préférences ou les sujets à éviter. Validez la lettre pour télécharger le PDF sans filigrane.|Tak. Po zapłacie przeczytaj list i poproś o maksymalnie pięć zmian, podając swoje wskazówki lub tematy do pominięcia. Zaakceptuj list, aby pobrać PDF bez znaku wodnego.
Which languages can I choose?|Welche Sprachen gibt es?|¿Qué idiomas puedo elegir?|Quelles langues puis-je choisir ?|Jakie języki są dostępne?
English, German, Spanish, French and Polish. The website and letter languages can be chosen separately.|Englisch, Deutsch, Spanisch, Französisch und Polnisch. Website und Brief können unterschiedliche Sprachen haben.|Inglés, alemán, español, francés y polaco. Puedes elegir por separado el idioma de la web y el de la carta.|Anglais, allemand, espagnol, français et polonais. La langue du site et celle de la lettre se choisissent séparément.|Angielski, niemiecki, hiszpański, francuski i polski. Język strony i język listu można wybrać niezależnie.
Privacy|Datenschutz|Privacidad|Confidentialité|Prywatność
Terms|Bedingungen|Condiciones|Conditions|Regulamin
Contact|Kontakt|Contacto|Contact|Kontakt
Close|Schließen|Cerrar|Fermer|Zamknij
Policies and support details will be published before purchases open.|Richtlinien und Kontaktdaten werden vor Verkaufsstart veröffentlicht.|Las políticas y los datos de contacto se publicarán antes de abrir las compras.|Les conditions et les coordonnées du service client seront publiées avant l’ouverture des achats.|Regulamin, polityka prywatności i dane kontaktowe zostaną opublikowane przed rozpoczęciem sprzedaży.
Made with a little help from the elves at the North Pole.|Mit ein wenig Hilfe der Wichtel vom Nordpol.|Con una pequeña ayuda de los elfos del Polo Norte.|Avec un petit coup de main des lutins du pôle Nord.|Stworzone z małą pomocą elfów z bieguna północnego.
Skip to content|Zum Inhalt|Ir al contenido|Aller au contenu|Przejdź do treści
Toggle menu|Menü öffnen|Abrir menú|Ouvrir le menu|Otwórz lub zamknij menu
Letter details|Angaben zum Brief|Detalles de la carta|Détails de la lettre|Szczegóły listu
Pick a design|Design auswählen|Elige un diseño|Choisissez un modèle|Wybierz wzór
Pay|Bezahlen|Pagar|Payer|Zapłać
Download PDF|PDF herunterladen|Descargar PDF|Télécharger le PDF|Pobierz PDF
Every bit of magic starts with them.|Der Zauber beginnt mit deinem Kind.|La magia empieza con tu peque.|La magie commence avec votre enfant.|Każda odrobina magii zaczyna się od dziecka.
Dress their letter in Christmas magic.|Weihnachtszauber für deinen Brief.|Viste su carta de magia navideña.|Habillez sa lettre de magie de Noël.|Otul list świąteczną magią.
A little magic, ready to make theirs.|Ein wenig Magie, nur für dein Kind.|Un poco de magia, solo para tu peque.|Un peu de magie, rien que pour votre enfant.|Odrobina magii, gotowa dla Twojego dziecka.
Tell Santa a little about them|Erzähle dem Weihnachtsmann von deinem Kind|Cuéntale a Papá Noel algo sobre tu peque|Parlez de votre enfant au Père Noël|Opowiedz Mikołajowi trochę o dziecku
First names and small details are perfect. No address or date of birth needed.|Vorname und kleine Details genügen. Keine Adresse oder Geburtsdatum nötig.|Basta con su nombre y unos detalles. No hace falta dirección ni fecha de nacimiento.|Un prénom et quelques détails suffisent. Pas besoin d’adresse ni de date de naissance.|Wystarczy imię i kilka drobnych szczegółów. Nie potrzebujemy adresu ani daty urodzenia.
Their first name|Vorname des Kindes|Su nombre|Son prénom|Imię dziecka
What’s on their Christmas wish list?|Was wünscht sich dein Kind zu Weihnachten?|¿Qué desea para Navidad?|Que souhaite votre enfant pour Noël ?|O czym marzy na święta?
Something they’re proud of|Worauf ist dein Kind stolz?|Algo de lo que se siente orgulloso|Une chose qui fait sa fierté|Coś, z czego jest dumne
A pet or special toy|Ein Haustier oder Lieblingsspielzeug|Una mascota o un juguete especial|Un animal ou un jouet préféré|Zwierzak lub wyjątkowa zabawka
Their letter to Santa|Der Brief deines Kindes an den Weihnachtsmann|Su carta a Papá Noel|Sa lettre au Père Noël|List dziecka do Mikołaja
optional|optional|opcional|facultatif|opcjonalnie
Free to preview. No account or card needed.|Kostenlose Vorschau. Kein Konto oder Karte nötig.|Vista previa gratis. Sin cuenta ni tarjeta.|Aperçu gratuit. Sans compte ni carte.|Podgląd jest bezpłatny. Bez konta i karty.
Your draft stays in this browser tab until checkout.|Dein Entwurf bleibt bis zur Kasse in diesem Browser-Tab.|El borrador se guarda en esta pestaña hasta el pago.|Votre brouillon reste dans cet onglet jusqu’au paiement.|Szkic pozostaje w tej karcie przeglądarki do momentu płatności.
Choose your letter design|Briefdesign auswählen|Elige el diseño de tu carta|Choisissez le modèle de lettre|Wybierz wzór listu
SAMPLE LETTER|MUSTERBRIEF|CARTA DE EJEMPLO|LETTRE D’EXEMPLE|PRZYKŁADOWY LIST
This watermarked sample uses fictional details. Your personal letter is written after payment. The final PDF has no watermark.|Dieses Muster mit Wasserzeichen enthält fiktive Angaben. Dein persönlicher Brief entsteht nach der Zahlung. Die fertige PDF hat kein Wasserzeichen.|Este ejemplo con marca de agua usa datos ficticios. Tu carta se escribe tras el pago. El PDF final no lleva marca de agua.|Cet exemple avec filigrane contient des détails fictifs. Votre lettre est rédigée après le paiement. Le PDF final n’a pas de filigrane.|Ten przykład ze znakiem wodnym zawiera fikcyjne szczegóły. Twój osobisty list powstanie po zapłacie. Gotowy PDF nie ma znaku wodnego.
Back to details|Zurück zu den Angaben|Volver a los detalles|Retour aux détails|Wróć do szczegółów
Continue to payment|Weiter zur Zahlung|Continuar al pago|Passer au paiement|Przejdź do płatności
Your Christmas delivery|Dein digitaler Weihnachtsbrief|Tu carta navideña digital|Votre lettre de Noël numérique|Twoja świąteczna przesyłka
Your email address|Deine E-Mail-Adresse|Tu correo electrónico|Votre adresse e-mail|Twój adres e-mail
We’ll email your private review link, then the PDF after you accept.|Wir senden dir den privaten Link zur Prüfung und nach deiner Bestätigung die PDF.|Te enviaremos el enlace privado de revisión y el PDF cuando aceptes.|Nous vous enverrons le lien privé, puis le PDF après votre validation.|Wyślemy e-mailem prywatny link do listu, a po akceptacji również PDF.
Used for payment. Return to your private link to review and download.|Für die Zahlung. Über deinen privaten Link kannst du den Brief prüfen und herunterladen.|Para el pago. Vuelve a tu enlace privado para revisar y descargar.|Pour le paiement. Retrouvez votre lien privé pour vérifier et télécharger.|Używany do płatności. Wróć do prywatnego linku, aby przeczytać i pobrać list.
I understand this is a digital PDF, with no postal delivery, and agree to the purchase terms.|Ich verstehe, dass dies eine digitale PDF ohne Postversand ist, und stimme den Kaufbedingungen zu.|Entiendo que es un PDF digital, sin envío postal, y acepto las condiciones de compra.|Je comprends qu’il s’agit d’un PDF numérique, sans envoi postal, et j’accepte les conditions d’achat.|Rozumiem, że kupuję cyfrowy PDF bez wysyłki pocztą, i akceptuję warunki zakupu.
Purchase terms|Kaufbedingungen|Condiciones de compra|Conditions d’achat|Warunki zakupu
Opening secure checkout…|Sichere Kasse wird geöffnet…|Abriendo el pago seguro…|Ouverture du paiement sécurisé…|Otwieramy bezpieczną płatność…
Pay {price} & get my letter|{price} bezahlen und Brief erhalten|Pagar {price} y recibir mi carta|Payer {price} et recevoir ma lettre|Zapłać {price} i odbierz list
Secure payment with Stripe · No subscription|Sicher bezahlen mit Stripe · Kein Abo|Pago seguro con Stripe · Sin suscripción|Paiement sécurisé avec Stripe · Sans abonnement|Bezpieczna płatność przez Stripe · Bez abonamentu
Payments aren’t open yet. You can still preview the sample designs.|Zahlungen sind noch nicht möglich. Du kannst die Musterdesigns ansehen.|Los pagos aún no están disponibles. Puedes ver los diseños de ejemplo.|Les paiements ne sont pas encore ouverts. Vous pouvez découvrir les modèles.|Płatności nie są jeszcze dostępne. Możesz obejrzeć przykładowe wzory.
Back to designs|Zurück zu den Designs|Volver a los diseños|Retour aux modèles|Wróć do wzorów
Please try again.|Bitte versuche es erneut.|Inténtalo de nuevo.|Veuillez réessayer.|Spróbuj ponownie.
You left checkout before finishing. Your details are still here.|Du hast die Kasse verlassen. Deine Angaben sind noch da.|Has salido del pago. Tus datos siguen aquí.|Vous avez quitté le paiement. Vos informations sont conservées.|Płatność nie została dokończona. Twoje dane nadal tu są.
Santa’s Special Delivery|Die Weihnachtspost|El correo de Papá Noel|Le courrier du Père Noël|Specjalna przesyłka Mikołaja
Reindeer Wishes|Rentierwünsche|Deseos de renos|Les vœux des rennes|Życzenia reniferów
Christmas Eve Flight|Flug am Heiligabend|Vuelo de Nochebuena|Le vol de Noël|Wigilijny lot
Jolly Christmas Pals|Fröhliche Weihnachtsfreunde|Amigos de Navidad|Les amis de Noël|Weseli świąteczni przyjaciele
Santa’s Beach Christmas|Weihnachtsmann am Strand|Navidad en la playa|Le Noël du Père Noël à la plage|Święta Mikołaja na plaży
Kangaroo Christmas BBQ|Weihnachtsgrillen mit Kängurus|Barbacoa navideña con canguros|Barbecue de Noël des kangourous|Świąteczny grill kangurów
Santa in flip-flops, sandy toes and seaside Christmas magic.|Der Weihnachtsmann in Flip-Flops, Sand an den Füßen und Weihnachtszauber am Meer.|Papá Noel en chanclas, arena entre los dedos y magia navideña junto al mar.|Le Père Noël en tongs, les pieds dans le sable et la magie de Noël au bord de la mer.|Mikołaj w japonkach, piasek pod stopami i świąteczna magia nad morzem.
Kangaroos in flip-flops, festive gifts and a sunny Christmas BBQ.|Kängurus in Flip-Flops, Geschenke und ein sonniges Weihnachtsgrillen.|Canguros en chanclas, regalos y una soleada barbacoa navideña.|Des kangourous en tongs, des cadeaux et un barbecue de Noël au soleil.|Kangury w japonkach, prezenty i świąteczny grill w słońcu.
Santa, his mailbag and a few woodland friends.|Der Weihnachtsmann, sein Postsack und Freunde aus dem Wald.|Papá Noel, su saco y unos amigos del bosque.|Le Père Noël, son sac et ses amis de la forêt.|Mikołaj, worek z listami i kilku leśnych przyjaciół.
Two cozy reindeer in their Christmas scarves.|Zwei gemütliche Rentiere mit Weihnachtsschals.|Dos renos con sus bufandas navideñas.|Deux rennes bien au chaud dans leurs écharpes.|Dwa urocze renifery w świątecznych szalikach.
Santa’s sleigh above a snowy North Pole village.|Der Schlitten über einem verschneiten Nordpoldorf.|El trineo sobre un pueblo nevado del Polo Norte.|Le traîneau au-dessus d’un village enneigé du pôle Nord.|Sanie Mikołaja nad ośnieżoną wioską na biegunie północnym.
A happy Santa, silly reindeer and their crayon-coloured friends.|Der Weihnachtsmann, lustige Rentiere und bunte Freunde.|Papá Noel, renos divertidos y amigos de colores.|Le Père Noël, de joyeux rennes et leurs amis colorés.|Wesoły Mikołaj, zabawne renifery i ich kredkowi przyjaciele.
Watermarked letter preview|Briefvorschau mit Wasserzeichen|Vista previa de la carta con marca de agua|Aperçu de la lettre avec filigrane|Podgląd listu ze znakiem wodnym
Preparing preview…|Vorschau wird erstellt…|Preparando vista previa…|Préparation de l’aperçu…|Przygotowujemy podgląd…
Preview unavailable. Please try again.|Vorschau nicht verfügbar. Bitte erneut versuchen.|Vista previa no disponible. Inténtalo de nuevo.|Aperçu indisponible. Veuillez réessayer.|Podgląd jest niedostępny. Spróbuj ponownie.
Show accessible text|Barrierefreien Text anzeigen|Mostrar texto accesible|Afficher le texte accessible|Pokaż dostępną wersję tekstową
YOUR PRIVATE NORTH POLE DELIVERY|DEINE PRIVATE NORDPOLPOST|TU CORREO PRIVADO DEL POLO NORTE|VOTRE COURRIER PRIVÉ DU PÔLE NORD|TWOJA PRYWATNA PRZESYŁKA Z BIEGUNA PÓŁNOCNEGO
A little letter. Just for them.|Ein kleiner Brief. Nur für dein Kind.|Una pequeña carta. Solo para tu peque.|Une petite lettre. Rien que pour votre enfant.|Mały list. Specjalnie dla Twojego dziecka.
Read it together, make it yours, then keep the magic.|Gemeinsam lesen, anpassen und den Zauber bewahren.|Leedla juntos, hacedla vuestra y guardad la magia.|Lisez-la ensemble, personnalisez-la et gardez la magie.|Przeczytajcie go razem, dopracujcie i zachowajcie magię.
Try again|Erneut versuchen|Reintentar|Réessayer|Spróbuj ponownie
Opening your purchase…|Dein Kauf wird geöffnet…|Abriendo tu compra…|Ouverture de votre achat…|Otwieramy Twoje zamówienie…
Payment confirmed|Zahlung bestätigt|Pago confirmado|Paiement confirmé|Płatność potwierdzona
Confirming payment|Zahlung wird bestätigt|Confirmando el pago|Confirmation du paiement|Potwierdzamy płatność
Version {version}|Version {version}|Versión {version}|Version {version}|Wersja {version}
Private link copied|Privater Link kopiert|Enlace privado copiado|Lien privé copié|Prywatny link skopiowany
Copy private link|Privaten Link kopieren|Copiar enlace privado|Copier le lien privé|Skopiuj prywatny link
We’re checking your payment. There’s no need to pay again.|Wir prüfen deine Zahlung. Bitte nicht erneut bezahlen.|Estamos comprobando tu pago. No hace falta pagar otra vez.|Nous vérifions votre paiement. Inutile de payer à nouveau.|Sprawdzamy płatność. Nie musisz płacić ponownie.
Santa is making your changes. Your previous version is below while you wait.|Der Weihnachtsmann überarbeitet den Brief. Bis dahin siehst du die vorherige Version.|Papá Noel está haciendo los cambios. Mientras tanto puedes ver la versión anterior.|Le Père Noël effectue vos modifications. La version précédente reste visible en attendant.|Mikołaj wprowadza Twoje zmiany. Poprzednia wersja jest dostępna poniżej.
Santa is writing your letter. It will appear here when it’s ready.|Der Weihnachtsmann schreibt deinen Brief. Er erscheint hier, sobald er fertig ist.|Papá Noel está escribiendo tu carta. Aparecerá aquí cuando esté lista.|Le Père Noël rédige votre lettre. Elle apparaîtra ici dès qu’elle sera prête.|Mikołaj pisze Twój list. Pojawi się tutaj, gdy będzie gotowy.
We couldn’t finish the latest request.|Die letzte Anfrage konnte nicht abgeschlossen werden.|No hemos podido terminar la última solicitud.|La dernière demande n’a pas pu aboutir.|Nie udało się zrealizować ostatniej prośby.
Your previous letter is still here to review and accept.|Dein vorheriger Brief ist noch zur Prüfung und Bestätigung da.|La carta anterior sigue aquí para revisarla y aceptarla.|Votre lettre précédente reste disponible pour vérification et validation.|Poprzedni list nadal możesz przeczytać i zaakceptować.
Your paid order is saved; keep the order reference for support.|Dein bezahlter Auftrag ist gespeichert. Bewahre die Bestellnummer auf.|Tu pedido pagado está guardado. Conserva la referencia para contactar con soporte.|Votre commande payée est enregistrée. Gardez la référence pour le service client.|Opłacone zamówienie jest zapisane. Zachowaj jego numer na wypadek kontaktu z obsługą.
THE FINAL LITTLE TOUCH|DER LETZTE KLEINE SCHLIFF|EL ÚLTIMO TOQUE|LA DERNIÈRE PETITE TOUCHE|OSTATNI MAGICZNY SZCZEGÓŁ
Ready to treasure.|Bereit zum Aufbewahren.|Lista para guardar.|Un souvenir à garder.|Gotowy, by zachować go na pamiątkę.
Does it feel just right?|Ist der Brief genau richtig?|¿Está a tu gusto?|La lettre vous plaît-elle ?|Czy wszystko się zgadza?
Your accepted version is saved. Download it again whenever you need it.|Deine bestätigte Version ist gespeichert. Lade sie jederzeit erneut herunter.|Tu versión aceptada está guardada. Descárgala de nuevo cuando quieras.|Votre version validée est enregistrée. Téléchargez-la à nouveau quand vous voulez.|Zaakceptowana wersja jest zapisana. Możesz pobrać ją ponownie, kiedy zechcesz.
Ask for a different tone or leave out a topic, then approve the version you love.|Wünsche dir einen anderen Ton oder lasse ein Thema weg. Bestätige dann deine Lieblingsversion.|Pide otro tono o que se omita un tema y acepta la versión que te guste.|Demandez un autre ton ou retirez un sujet, puis validez votre version préférée.|Poproś o inny ton lub pominięcie tematu, a następnie zaakceptuj ulubioną wersję.
One little moment…|Einen kleinen Moment…|Un momentito…|Un petit instant…|Jeszcze chwilka…
Accept & download PDF|Bestätigen und PDF herunterladen|Aceptar y descargar PDF|Valider et télécharger le PDF|Zaakceptuj i pobierz PDF
Request changes|Änderungen wünschen|Pedir cambios|Demander des modifications|Poproś o zmiany
{count} rewrite requests remaining. Your letter’s history is safely saved.|Noch {count} Überarbeitungen. Frühere Versionen bleiben gespeichert.|Quedan {count} revisiones. El historial de tu carta está guardado.|Il reste {count} réécritures. L’historique de votre lettre est conservé.|Pozostałe prośby o zmianę treści: {count}. Historia listu jest bezpiecznie zapisana.
What would you like Santa to change?|Was soll der Weihnachtsmann ändern?|¿Qué quieres que cambie Papá Noel?|Que souhaitez-vous modifier ?|Co Mikołaj ma zmienić?
Words or topics to leave out|Wörter oder Themen zum Weglassen|Palabras o temas que evitar|Mots ou sujets à éviter|Słowa lub tematy do pominięcia
Make it more playful and shorter.|Verspielter und kürzer schreiben.|Hazla más divertida y breve.|Rendez-la plus amusante et plus courte.|Niech list będzie krótszy i bardziej zabawny.
School grades, the bicycle, being watched|Schulnoten, das Fahrrad, beobachtet werden|Notas del colegio, la bicicleta, sentirse vigilado|Notes scolaires, le vélo, être surveillé|Oceny w szkole, rower, obserwowanie dziecka
Separate topics with commas or new lines. Earlier exclusions carry forward.|Themen mit Kommas oder Zeilenumbrüchen trennen. Frühere Ausschlüsse bleiben erhalten.|Separa los temas con comas o saltos de línea. Se mantienen las exclusiones anteriores.|Séparez les sujets par des virgules ou des retours à la ligne. Les exclusions précédentes sont conservées.|Oddziel tematy przecinkami lub nowymi wierszami. Wcześniejsze wykluczenia nadal obowiązują.
Rewrite my letter|Meinen Brief überarbeiten|Reescribir mi carta|Réécrire ma lettre|Napisz list od nowa
Your accepted PDF has been sent by email.|Deine bestätigte PDF wurde per E-Mail versandt.|Tu PDF aceptado se ha enviado por correo electrónico.|Votre PDF validé a été envoyé par e-mail.|Zaakceptowany PDF został wysłany e-mailem.
Your accepted PDF is queued for email delivery.|Deine bestätigte PDF wartet auf den E-Mail-Versand.|Tu PDF aceptado está en espera de envío por correo.|Votre PDF validé attend son envoi par e-mail.|Zaakceptowany PDF czeka na wysłanie e-mailem.
Email delivery could not be confirmed. Download your PDF here.|Der E-Mail-Versand konnte nicht bestätigt werden. Lade die PDF hier herunter.|No se ha confirmado el envío. Descarga el PDF aquí.|L’envoi par e-mail n’a pas pu être confirmé. Téléchargez votre PDF ici.|Nie udało się potwierdzić wysyłki e-maila. Pobierz PDF tutaj.
The final PDF email is sent only after you accept this version.|Die fertige PDF wird erst nach Bestätigung dieser Version per E-Mail versandt.|El PDF final se envía por correo cuando aceptes esta versión.|Le PDF final est envoyé par e-mail après validation de cette version.|E-mail z gotowym PDF zostanie wysłany dopiero po akceptacji tej wersji.
Order reference|Bestellnummer|Referencia del pedido|Référence de commande|Numer zamówienia
Keep your private link safe. Anyone with it can view and revise this letter.|Bewahre deinen privaten Link sicher auf. Wer ihn hat, kann den Brief ansehen und überarbeiten.|Guarda tu enlace privado. Quien lo tenga puede ver y revisar la carta.|Gardez votre lien privé en sécurité. Toute personne le possédant peut voir et modifier la lettre.|Chroń swój prywatny link. Każdy, kto go ma, może przeglądać i zmieniać ten list.
Copy the private link from your browser’s address bar.|Kopiere den privaten Link aus der Adresszeile.|Copia el enlace privado de la barra de direcciones.|Copiez le lien privé depuis la barre d’adresse.|Skopiuj prywatny link z paska adresu przeglądarki.
Your Santa letter is ready to review ✨|Dein Weihnachtsbrief ist zur Prüfung bereit ✨|Tu carta de Papá Noel está lista para revisar ✨|Votre lettre du Père Noël est prête à vérifier ✨|Twój list od Mikołaja czeka na przeczytanie ✨
A special delivery from Santa ✨|Ein besonderer Brief vom Weihnachtsmann ✨|Un correo especial de Papá Noel ✨|Un courrier spécial du Père Noël ✨|Specjalna przesyłka od Mikołaja ✨
A little magic has arrived.|Ein wenig Magie ist angekommen.|Ha llegado un poco de magia.|Un peu de magie est arrivée.|Przybyła odrobina magii.
Your letter is ready. Review it, request changes, or accept and download your PDF.|Dein Brief ist fertig. Prüfe ihn, wünsche Änderungen oder bestätige ihn und lade die PDF herunter.|Tu carta está lista. Revísala, pide cambios o acéptala y descarga el PDF.|Votre lettre est prête. Vérifiez-la, demandez des modifications ou validez-la pour télécharger le PDF.|Twój list jest gotowy. Przeczytaj go, poproś o zmiany lub zaakceptuj i pobierz PDF.
Your accepted letter is attached as letter-from-santa.pdf. Print it at home and treasure it.|Dein bestätigter Brief ist als letter-from-santa.pdf angehängt. Drucke ihn zu Hause aus.|Tu carta aceptada está adjunta como letter-from-santa.pdf. Imprímela en casa y guárdala.|Votre lettre validée est jointe sous le nom letter-from-santa.pdf. Imprimez-la chez vous et gardez-la.|Zaakceptowany list znajdziesz w załączniku letter-from-santa.pdf. Wydrukuj go w domu i zachowaj na pamiątkę.
Review your letter|Deinen Brief prüfen|Revisar tu carta|Vérifier votre lettre|Przeczytaj swój list
Visit your purchase|Deinen Kauf öffnen|Ver tu compra|Retrouver votre achat|Otwórz zamówienie
With love from the elves|Liebe Grüße von den Wichteln|Con cariño de los elfos|Avec toute l’affection des lutins|Z serdecznymi pozdrowieniami od elfów
`;
export const translations={en:{},de:{},es:{},fr:{},pl:{}};
for(const row of rows.trim().split('\n')){const [en,de,es,fr,pl]=row.split('|');for(const [code,value] of Object.entries({en,de,es,fr,pl})){if(!value)throw new Error(`Missing ${code} translation: ${en}`);translations[code][en]=value;}}
export function translate(language,key,values={}){let text=translations[localeCode(language)][key]||key;return text.replace(/\{(\w+)\}/g,(match,name)=>values[name]??match);}
export function orderLanguage(order){try{return letterLocaleCode(order.language||JSON.parse(order.child_details||'{}').language)}catch{return 'en'}}
export const digitalNotice='Digital PDF only. Download and print at home. No physical letter will be posted.';
const errorRows=`
Please use the Elf Mailroom website.|Bitte nutze die Elf-Mailroom-Website.|Utiliza la web de Elf Mailroom.|Veuillez utiliser le site Elf Mailroom.|Skorzystaj ze strony Elf Mailroom.
Add your email, choose a design and accept the purchase terms.|E-Mail eingeben, Design wählen und Kaufbedingungen akzeptieren.|Añade tu correo, elige un diseño y acepta las condiciones.|Saisissez votre e-mail, choisissez un modèle et acceptez les conditions.|Podaj e-mail, wybierz wzór i zaakceptuj warunki zakupu.
The mailroom is not taking payments yet. Your preview is ready to enjoy.|Zahlungen sind noch nicht möglich. Die Vorschau ist verfügbar.|Los pagos aún no están disponibles. Puedes disfrutar de la vista previa.|Les paiements ne sont pas encore ouverts. L’aperçu reste disponible.|Poczta nie przyjmuje jeszcze płatności. Możesz korzystać z podglądu.
Checkout could not open. Please try again in a moment.|Die Kasse konnte nicht geöffnet werden. Bitte gleich erneut versuchen.|No se pudo abrir el pago. Inténtalo en un momento.|Le paiement n’a pas pu s’ouvrir. Réessayez dans un instant.|Nie udało się otworzyć płatności. Spróbuj ponownie za chwilę.
Open the complete private link for this purchase, including its token.|Öffne den vollständigen privaten Link für diesen Kauf, einschließlich Zugangscode.|Abre el enlace privado completo de esta compra, incluido su código.|Ouvrez le lien privé complet de cet achat, y compris son code d’accès.|Otwórz pełny prywatny link do zamówienia, razem z tokenem dostępu.
Purchase not found. Use its complete private link.|Kauf nicht gefunden. Verwende den vollständigen privaten Link.|Compra no encontrada. Usa el enlace privado completo.|Achat introuvable. Utilisez le lien privé complet.|Nie znaleziono zamówienia. Użyj jego pełnego prywatnego linku.
Your PDF will be ready once payment is confirmed.|Die PDF ist nach Bestätigung der Zahlung verfügbar.|El PDF estará disponible cuando se confirme el pago.|Le PDF sera disponible après confirmation du paiement.|PDF będzie gotowy po potwierdzeniu płatności.
Santa is still preparing your letter. Please check its status before downloading.|Der Weihnachtsmann bereitet den Brief noch vor. Bitte warte mit dem Download.|Papá Noel aún está preparando tu carta. Comprueba su estado antes de descargar.|Le Père Noël prépare encore votre lettre. Vérifiez son état avant de télécharger.|Mikołaj nadal przygotowuje Twój list. Przed pobraniem sprawdź jego status.
Please review and accept the current letter before downloading.|Bitte prüfe und bestätige den aktuellen Brief vor dem Download.|Revisa y acepta la carta actual antes de descargar.|Veuillez vérifier et valider la lettre actuelle avant de télécharger.|Przed pobraniem przeczytaj i zaakceptuj aktualną wersję listu.
Purchase not found.|Kauf nicht gefunden.|Compra no encontrada.|Achat introuvable.|Nie znaleziono zamówienia.
Rewriting is temporarily unavailable. Your current letter is saved.|Überarbeitungen sind gerade nicht verfügbar. Dein Brief ist gespeichert.|Las revisiones no están disponibles temporalmente. Tu carta está guardada.|La réécriture est temporairement indisponible. Votre lettre est conservée.|Zmiany są chwilowo niedostępne. Aktualny list jest zapisany.
Describe the changes in 3–1,500 characters and use up to 20 short exclusions.|Beschreibe die Änderungen mit 3–1.500 Zeichen und höchstens 20 kurzen Ausschlüssen.|Describe los cambios con 3–1500 caracteres y hasta 20 exclusiones breves.|Décrivez les modifications en 3 à 1 500 caractères avec 20 exclusions courtes au maximum.|Opisz zmiany w 3–1500 znakach i podaj maksymalnie 20 krótkich wykluczeń.
Choose the current letter version.|Wähle die aktuelle Briefversion.|Elige la versión actual de la carta.|Choisissez la version actuelle de la lettre.|Wybierz aktualną wersję listu.
Something went wrong. Please try again.|Etwas ist schiefgegangen. Bitte erneut versuchen.|Algo ha fallado. Inténtalo de nuevo.|Une erreur s’est produite. Veuillez réessayer.|Coś poszło nie tak. Spróbuj ponownie.
This purchase has not been paid.|Dieser Kauf wurde noch nicht bezahlt.|Esta compra aún no se ha pagado.|Cet achat n’a pas encore été payé.|To zamówienie nie zostało opłacone.
The letter has changed. Refresh and review the latest version.|Der Brief wurde geändert. Lade die Seite neu und prüfe die aktuelle Version.|La carta ha cambiado. Actualiza y revisa la última versión.|La lettre a changé. Actualisez et vérifiez la dernière version.|List się zmienił. Odśwież stronę i przeczytaj najnowszą wersję.
A letter is already being written. Please wait for it to finish.|Ein Brief wird bereits geschrieben. Bitte warte, bis er fertig ist.|Ya se está escribiendo una carta. Espera a que termine.|Une lettre est en cours de rédaction. Veuillez patienter.|List jest już w trakcie pisania. Poczekaj na zakończenie.
An email is being sent. Please try again in a moment.|Eine E-Mail wird versandt. Bitte versuche es gleich erneut.|Se está enviando un correo. Inténtalo en un momento.|Un e-mail est en cours d’envoi. Réessayez dans un instant.|Trwa wysyłanie e-maila. Spróbuj ponownie za chwilę.
The original details are unavailable for this older order. Please contact support for an edit.|Die ursprünglichen Angaben dieser älteren Bestellung fehlen. Bitte kontaktiere den Support.|Los datos originales de este pedido antiguo no están disponibles. Contacta con soporte.|Les informations d’origine de cette ancienne commande sont indisponibles. Contactez le service client.|Brak oryginalnych szczegółów tego starszego zamówienia. W sprawie zmian skontaktuj się z obsługą.
You’ve used the included rewrites. Please contact support for further changes.|Die enthaltenen Überarbeitungen sind aufgebraucht. Kontaktiere den Support für weitere Änderungen.|Has usado las revisiones incluidas. Contacta con soporte para más cambios.|Vous avez utilisé les réécritures incluses. Contactez le service client pour d’autres modifications.|Wszystkie zmiany w cenie zostały wykorzystane. W sprawie kolejnych skontaktuj się z obsługą.
Your letter is not ready yet.|Dein Brief ist noch nicht fertig.|Tu carta aún no está lista.|Votre lettre n’est pas encore prête.|Twój list nie jest jeszcze gotowy.
`;
for(const row of errorRows.trim().split('\n')){const[en,de,es,fr,pl]=row.split('|');for(const[code,value]of Object.entries({en,de,es,fr,pl}))translations[code][en]=value;}
