const baseURL=process.env.E2E_BASE_URL||'http://localhost:5173';
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {createLetterPdf} from '../apps/api/src/pdf.js';
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1360,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const id='aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa',token='a'.repeat(64);let order={id,status:'paid',design:'jolly',generationStatus:'ready',emailStatus:'not_requested',version:1,accepted:false,rewritesRemaining:5,canRewrite:true,purchaseUrl:`${baseURL}/write/purchase/${id}#token=${token}`,letter:'Dear Mila,\n\nYour kind heart has brought a little warmth to the North Pole. Biscuit sounds like a lovely friend, and I have noted your Christmas wish.\n\nKeep sharing your kindness, and have a wonderful Christmas.\n\nWith a big snowy hug,'};
await page.route('**/api/orders/**',async route=>{assert.equal(route.request().headers().authorization,`Bearer ${token}`);const path=new URL(route.request().url()).pathname;
 if(path.endsWith('/accept')){assert.equal(route.request().postDataJSON().version,order.version);order={...order,accepted:true};return route.fulfill({json:{ok:true}})}
 if(path.endsWith('/rewrite')){const body=route.request().postDataJSON();assert.equal(body.instructions,'Make it shorter and more playful.');assert.deepEqual(body.avoid,['Biscuit']);order={...order,version:2,rewritesRemaining:4,letter:'Dear Mila,\n\nA jolly little elf has just slid down a snowy hill with your letter! Your kindness makes Christmas brighter. Keep being curious and brave.\n\nWith a happy Christmas hug,'};return route.fulfill({status:202,json:{ok:true}})}
 if(path.endsWith('/preview'))return route.fulfill({contentType:'application/pdf',body:await createLetterPdf(order.letter,order.design)});
 if(path.endsWith('/pdf')){assert(order.accepted);return route.fulfill({contentType:'application/pdf',body:await createLetterPdf(order.letter,order.design)})}
 return route.fulfill({json:order});});
await page.goto(order.purchaseUrl);await page.getByRole('button',{name:'Reject',exact:true}).click();await page.getByRole('button',{name:'Request changes',exact:true}).click();await page.getByLabel('What would you like Santa to change?').fill('Make it shorter and more playful.');await page.getByLabel('Words or topics to leave out').fill('Biscuit');await page.getByRole('button',{name:'Rewrite my letter'}).click();await page.getByText('Version 2',{exact:false}).first().waitFor();assert.doesNotMatch(await page.locator('.preview-accessible p').textContent(),/Biscuit/);await page.locator('.paid-letter-preview canvas').first().waitFor();await page.screenshot({path:'tests/purchase-review.png',fullPage:true});const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Accept & download PDF',exact:true}).click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'letter-from-santa.pdf');await page.getByRole('button',{name:'Download PDF',exact:true}).waitFor();await page.setViewportSize({width:360,height:800});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'tests/purchase-mobile.png',fullPage:true});
let admin=false;let adminOrder={id,buyer_email:'parent@example.com',status:'paid',design:'jolly',created_at:Date.now(),amount_cents:399,letter_version:2,accepted_version:2,generation_status:'ready',email_status:'not_requested',rewrite_count:1,letter:order.letter,child_details:{name:'Mila',wish:'a bicycle',proud:'being kind',pet:'Biscuit',message:'Dear Santa, how are the elves?'}};let versions=[{version:2,source:'rewrite',letter:order.letter,created_at:Date.now()},{version:1,source:'generated',letter:'Dear Mila, original letter with Biscuit.',created_at:Date.now()-1000}];
await page.route('**/api/admin/**',async route=>{const pathname=new URL(route.request().url()).pathname;
 if(pathname.endsWith('/login')){admin=true;return route.fulfill({json:{email:'headelf@example.com'}})}
 if(pathname.endsWith('/logout')){admin=false;return route.fulfill({json:{ok:true}})}
 if(!admin)return route.fulfill({status:401,json:{error:'Sign in to the admin mailroom.'}});
 if(pathname.endsWith('/me'))return route.fulfill({json:{email:'headelf@example.com'}});
 if(pathname.endsWith('/letter')){const data=route.request().postDataJSON();assert.equal(data.version,2);adminOrder={...adminOrder,letter:data.letter,letter_version:3,accepted_version:null};versions=[{version:3,source:'admin',letter:data.letter,created_at:Date.now(),editor:'headelf@example.com'},...versions];return route.fulfill({json:{version:3}})}
 if(pathname.endsWith('/'+id))return route.fulfill({json:{order:adminOrder,versions,requests:[{id:'req1',instructions:'Make it playful',avoid:'["Biscuit"]',status:'ready',created_at:Date.now()}]}});
 return route.fulfill({json:{orders:[adminOrder],total:1,page:1,pageSize:25,summary:{purchases:1,paid:1,letters:1,revenue:399}}});});
await page.setViewportSize({width:1360,height:1000});await page.goto(baseURL+'/write/admin');await page.getByLabel('Admin email').fill('headelf@example.com');await page.getByLabel('Password',{exact:true}).fill('a-long-admin-password');await page.getByRole('button',{name:'Open the mailroom',exact:true}).click();await page.getByRole('heading',{name:'Purchases & letters'}).waitFor();await page.screenshot({path:'tests/admin-purchases.png',fullPage:true});await page.getByRole('button',{name:'View & edit'}).click();await page.getByLabel('Letter text').fill(order.letter+'\nA little extra Christmas cheer from the head elf.');await page.getByRole('button',{name:'Save new version'}).click();await page.getByRole('status').waitFor();assert.match(await page.getByRole('status').innerText(),/New version saved/);await page.screenshot({path:'tests/admin-edit.png',fullPage:true});await page.setViewportSize({width:360,height:800});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'tests/admin-mobile.png',fullPage:true});await page.getByRole('button',{name:'Sign out'}).click();await page.getByLabel('Admin email').waitFor();assert.deepEqual(errors,[]);await browser.close();console.log('Purchase links, revisions, approval/download, admin login/edit/history and mobile checks passed (mocked API).');
