import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {languages} from '../packages/shared/locales.js';
import {seoCopy,languagePath} from '../packages/shared/seo.js';
import {articleTranslation,blogArticles,blogCopy,blogPath} from '../packages/shared/blog.js';
const temp=await mkdtemp(path.join(tmpdir(),'elf-seo-')),origin='http://localhost:3210';
const proc=spawn(process.execPath,['apps/api/src/server.js'],{env:{...process.env,PORT:'3210',PUBLIC_URL:origin,DATABASE_PATH:path.join(temp,'orders.sqlite'),OPENAI_API_KEY:'',STRIPE_SECRET_KEY:'',EMAIL_ENABLED:'false',SALES_ENABLED:'false'},stdio:['ignore','pipe','pipe']});
let browser;
try{
 await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Server startup timed out')),8000);proc.stdout.once('data',()=>{clearTimeout(timer);resolve()});proc.once('error',reject)});browser=await chromium.launch();
 const nojs=await browser.newContext({javaScriptEnabled:false});const plain=await nojs.newPage();
 for(const{code}of languages){const url=origin+languagePath(code),response=await fetch(url),html=await response.text();assert.equal(response.status,200);assert(html.includes(seoCopy[code].h1));assert(html.includes('application/ld+json'));assert(!html.includes('noindex'));await plain.goto(url);assert.equal(await plain.locator('h1').count(),1);assert((await plain.locator('h1').innerText()).includes(seoCopy[code].h1));assert.equal(await plain.title(),seoCopy[code].title);assert.equal(await plain.locator('html').getAttribute('lang'),code);assert.equal(await plain.locator('meta[name="description"]').getAttribute('content'),seoCopy[code].description);assert.equal(await plain.locator('meta[property="og:title"]').getAttribute('content'),seoCopy[code].title);assert.equal(await plain.locator('meta[property="og:description"]').getAttribute('content'),seoCopy[code].description);assert.equal(await plain.locator('meta[name="twitter:title"]').getAttribute('content'),seoCopy[code].title);assert.equal(await plain.locator('meta[name="twitter:description"]').getAttribute('content'),seoCopy[code].description);assert.equal(await plain.locator('meta[property="og:locale"]').getAttribute('content'),{en:'en_GB',de:'de_DE',es:'es_ES',fr:'fr_FR',pl:'pl_PL'}[code]);assert.equal(new URL(await plain.locator('meta[property="og:url"]').getAttribute('content')).pathname,languagePath(code));assert.match(await plain.locator('meta[property="og:image"]').getAttribute('content'),/^https?:\/\//);if(code!=='en'){const direct=await fetch(origin+'/'+code,{redirect:'manual'});assert.equal(direct.status,301);assert.equal(new URL(direct.headers.get('location'),origin).pathname,languagePath(code));}assert.equal(await plain.locator('link[rel="alternate"][hreflang]').count(),languages.length+1);const canonical=await plain.locator('link[rel="canonical"]').getAttribute('href');assert.equal(new URL(canonical).pathname,languagePath(code));assert.equal(await plain.locator('.language-links a').count(),languages.length);assert.equal(await plain.locator('.home-blog-card').count(),blogArticles.length);assert.equal(new URL(await plain.locator('.home-blog-heading .button').getAttribute('href'),origin).pathname,blogPath(code));const schema=JSON.parse(await plain.locator('#elf-schema').textContent());assert.equal(schema['@graph'].length,4);assert.equal(schema['@graph'].find(x=>x['@type']==='Product').offers,undefined);}
 for(const{code}of languages){const indexUrl=origin+blogPath(code);await plain.goto(indexUrl);assert.equal(await plain.locator('html').getAttribute('lang'),code);assert.equal(await plain.locator('h1').innerText(),blogCopy[code].title);assert.equal(await plain.locator('.blog-card').count(),blogArticles.length);assert.equal(new URL(await plain.locator('link[rel="canonical"]').getAttribute('href')).pathname,blogPath(code));assert.equal(new URL(await plain.locator('.language-links a[lang="pl"]').getAttribute('href'),origin).pathname,blogPath('pl'));for(const article of blogArticles){const copy=articleTranslation(article,code),url=origin+blogPath(code,article.slug),response=await fetch(url);assert.equal(response.status,200);assert((await response.text()).includes(copy.title));await plain.goto(url);assert.equal(await plain.locator('h1').innerText(),copy.title);assert.equal(await plain.locator('.blog-article-body section').count(),copy.sections.length);assert.equal(await plain.locator('meta[property="og:type"]').getAttribute('content'),'article');assert.equal(new URL(await plain.locator('.language-links a[lang="fr"]').getAttribute('href'),origin).pathname,blogPath('fr',article.slug));assert(JSON.parse(await plain.locator('#elf-schema').textContent())['@graph'].some(x=>x['@type']==='BlogPosting'));}}
 for(const{code}of languages)for(const type of ['privacy','terms']){const url=origin+languagePath(code)+type+'/';const response=await fetch(url);assert.equal(response.status,200);await plain.goto(url);assert.equal(await plain.locator('h1').count(),1);assert.equal(await plain.locator('html').getAttribute('lang'),code);assert((await plain.locator('body').innerText()).includes('Webz Australia'));assert.equal(await plain.locator('.language-links a').count(),languages.length);if(type==='terms')assert.equal(await plain.locator('#cancellation').count(),1);}
 await nojs.close();
 const context=await browser.newContext();const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 // A saved preference must not replace an explicitly requested language URL during hydration.
 await context.addInitScript(()=>localStorage.setItem('elf-language','fr'));
 await page.goto(origin+'/de/');await page.getByRole('heading',{level:1}).waitFor();await page.locator('.raster-preview>img').waitFor();assert.equal(await page.locator('html').getAttribute('lang'),'de');
 await page.locator('.language-picker select').selectOption('es');assert.equal(new URL(page.url()).pathname,'/es/');await page.waitForFunction(title=>document.title===title,seoCopy.es.title);assert.equal(new URL(await page.locator('link[rel="canonical"]').getAttribute('href')).pathname,'/es/');assert.equal(JSON.parse(await page.locator('#elf-schema').textContent())['@graph'].find(x=>x['@type']==='WebPage').inLanguage,'es');
 await page.reload();await page.locator('.raster-preview>img').waitFor();assert.equal(await page.title(),seoCopy.es.title);await page.goBack();await page.waitForFunction(title=>document.title===title,seoCopy.de.title);
 for(const width of [1440,1024,768,390,360]){await page.setViewportSize({width,height:1000});for(const{code}of languages){await page.locator('.language-picker select').selectOption(code);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${code} overflow at ${width}`);if(code==='en'&&(width===1440||width===360))await page.locator('.hero').screenshot({path:`tests/seo-hero-${width}.png`});}}
 await page.goto(origin+blogPath('en'));await page.locator('.language-picker select').selectOption('pl');assert.equal(new URL(page.url()).pathname,blogPath('pl'));await page.waitForFunction(title=>document.title===title,blogCopy.pl.title+' | Elf Mailroom');await page.locator('.language-picker select').selectOption('en');for(const width of [1440,390,360]){await page.setViewportSize({width,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`blog overflow at ${width}`);}
 await page.route('**/api/config',route=>route.fulfill({json:{checkoutEnabled:true}}));await page.goto(origin+'/');await page.waitForFunction(()=>JSON.parse(document.querySelector('#elf-schema').textContent)['@graph'].some(x=>x['@type']==='Product'&&x.offers?.price==='3.99'));assert.equal(await page.locator('#elf-schema').count(),1);assert.equal(await page.locator('link[rel=canonical]').count(),1);
 const robots=await fetch(origin+'/robots.txt').then(r=>r.text());assert(robots.includes('Sitemap:'));assert(!robots.includes('Disallow: /write'));const sitemap=await fetch(origin+'/sitemap.xml').then(r=>r.text());assert.equal((sitemap.match(/<loc>/g)||[]).length,languages.length*(blogArticles.length+2));
 for(const pathname of ['/write/','/write/admin','/write/purchase/test']){const response=await fetch(origin+pathname);assert.match(response.headers.get('x-robots-tag'),/noindex/);assert.match(await response.text(),/name="robots" content="noindex,nofollow"/)}assert.equal((await fetch(origin+'/missing-page')).status,404);
 assert.deepEqual(errors,[]);console.log('SEO: all pre-rendered locales work without JavaScript; hydration, canonical/hreflang/schema, language navigation, responsive headings, sitemap and private-page noindex passed.');
}finally{await browser?.close();proc.kill();if(proc.exitCode===null)await new Promise(r=>proc.once('exit',r));await rm(temp,{recursive:true,force:true})}
