export default {
 en:{
  title:'Printable Santa letter: printing tips and magical delivery ideas',
  description:'Make a printable Santa letter feel special with simple paper, printer and envelope tips, plus sweet North Pole messages and easy ways to present it.',
  dek:'To make a printable Santa letter feel magical, check the personal details, print a test page and add one small surprise to the envelope. A quiet moment to read it together matters more than lots of decorations. Here is a simple way to prepare it at home.',
  sections:[
   ['1. Check the words before you print',['Read the letter yourself first. Check the child’s name and the details they will recognise, such as a pet, a favourite activity or something they worked hard to learn. Remove any promise of a gift you cannot guarantee.','With Elf Mailroom, the letter is a digital PDF for you to download and print. The envelope, printing and little delivery ritual are yours to arrange; a physical letter is not sent through the post.']],
   ['2. Choose paper and print one test page',['Ordinary printer paper works well. For a more substantial feel, try warm-white paper around 100–120 gsm only if your printer supports that weight and type. Check its paper guidance before buying a pack.','Select the paper size that matches your PDF and look at the print preview. Try actual size first; if the border falls outside the printable area, use “Fit” or “Fit to printable area”. Print one test sheet before choosing a higher-quality colour setting.']],
   ['3. Give the envelope a little North Pole character',['Write the child’s first name by hand and add “North Pole Post” or a drawn stamp. A paper star drawn in the corner gives you a festive touch without loose glitter or extra props.','Add a short message on the back flap. One tiny detail is enough to invite a story about the journey.'],'A message for the envelope: “Special delivery for a very lovely human. Checked by elves; sniffed by reindeer.”'],
   ['4. Choose a calm moment for the delivery',['Place the envelope beside the tree, with a Christmas book or at the breakfast table. Pick a time when your child can enjoy opening it without needing to rush out of the house.','If surprises make them uneasy, tell them a special letter is waiting and let them decide when to open it. For siblings, prepare a personal detail for each child without comparing their achievements.']],
   ['5. Read together and save the memory',['Let your child open the envelope and choose whether to read it alone or with you. Pause at the detail they recognise and follow their questions. There is no need to stage a perfect reaction or take a photograph.','Write the date on the back afterwards and keep the letter flat in a folder or memory box. Save the original PDF too, so you can print another copy if this one gets loved a little too much.'],'A little keepsake note: “Folded with care, sprinkled with cheer, ready for a smile from ear to ear.”']
  ],
  faqs:[
   ['What paper should I use for a printable Santa letter?','Normal printer paper is enough. Warm-white paper around 100–120 gsm can feel more substantial, but check that your printer supports the paper’s weight and finish before using it.'],
   ['Why are the edges of my Santa letter being cut off?','The design may extend beyond your printer’s printable area, or the selected paper size may be wrong. Check the size and preview, then try “Fit to printable area” and print a test page.'],
   ['Can I print a Santa letter without a colour printer?','Yes. Preview the PDF in greyscale and print a test sheet to check that the text and illustrations remain clear. A hand-drawn envelope can add colour afterwards.'],
   ['How can I present a Santa letter without glitter or mess?','Write a North Pole message on the envelope, draw a small star and leave the letter beside the tree or a favourite book. A personal detail in the letter provides the main surprise.']
  ]
 },
 de:{
  title:'Brief vom Weihnachtsmann ausdrucken und zauberhaft überreichen',
  description:'Tipps für Papier, Druckeinstellungen und Umschlag: So wird ein Brief vom Weihnachtsmann zum Ausdrucken persönlich, mit kleinen Botschaften aus der Wichtelpost.',
  dek:'Prüfe die persönlichen Angaben, drucke eine Testseite und ergänze eine kleine Überraschung auf dem Umschlag. Ein ruhiger Moment zum gemeinsamen Lesen macht den Weihnachtsbrief besonders. So bereitest du ihn zu Hause vor.',
  sections:[
   ['1. Den Text vor dem Drucken prüfen',['Stimmen Name, Haustier und die kleinen Erlebnisse, die dein Kind wiedererkennt? Lies den Brief zuerst selbst. Entferne Geschenkversprechen, die du nicht sicher erfüllen kannst.','Bei Elf Mailroom erhältst du eine digitale PDF zum Herunterladen und Ausdrucken. Umschlag, Druck und Übergabe gestaltest du selbst; es wird kein Papierbrief per Post verschickt.']],
   ['2. Papier wählen und eine Testseite drucken',['Normales Druckerpapier reicht aus. Warmweißes Papier mit etwa 100–120 g/m² fühlt sich etwas kräftiger an, sofern dein Drucker diese Papierart und Stärke unterstützt. Prüfe dazu die Herstellerangaben.','Wähle das zur PDF passende Papierformat und kontrolliere die Vorschau. Beginne mit der tatsächlichen Größe. Liegt der Rand außerhalb des Druckbereichs, wähle „Anpassen“ oder „An Druckbereich anpassen“. Drucke erst eine Testseite, bevor du die Farbqualität erhöhst.']],
   ['3. Dem Umschlag Nordpol-Charme geben',['Schreibe den Vornamen von Hand und ergänze „Nordpolpost“ oder eine gemalte Briefmarke. Ein aufgemalter Stern sorgt für Stimmung, ganz ohne losen Glitzer.','Auf die Rückseite passt eine kurze Nachricht. Ein kleines Detail genügt, um sich die Reise des Briefs vorzustellen.'],'Für den Umschlag: „Sonderzustellung für einen ganz lieben Menschen. Von Wichteln geprüft, von Rentieren beschnuppert.“'],
   ['4. Einen ruhigen Moment für die Übergabe wählen',['Lege den Brief zum Baum, neben ein Weihnachtsbuch oder auf den Frühstückstisch. Wähle eine Zeit ohne Eile.','Mag dein Kind keine Überraschungen, kündige den Brief an und lass es den Zeitpunkt wählen. Für Geschwister passen eigene Erinnerungen in jeden Brief, ohne ihre Leistungen zu vergleichen.']],
   ['5. Gemeinsam lesen und die Erinnerung bewahren',['Dein Kind darf selbst öffnen und entscheiden, ob ihr zusammen lest. Lasst Raum für Fragen. Eine perfekte Reaktion oder ein Foto ist nicht nötig.','Schreibe danach das Datum auf die Rückseite und bewahre den Brief flach in einer Mappe auf. Speichere auch die PDF, falls das geliebte Original später einen Ersatz braucht.'],'Ein kleiner Erinnerungsgruß: „Mit Sorgfalt gefaltet und Weihnachtsfreude gefüllt. Jetzt fehlt nur noch dein Lächeln.“']
  ],
  faqs:[
   ['Welches Papier eignet sich für einen Brief vom Weihnachtsmann?','Normales Druckerpapier genügt. Warmweißes Papier mit etwa 100–120 g/m² wirkt kräftiger. Prüfe vorab, ob dein Drucker die Stärke und Oberfläche unterstützt.'],
   ['Warum werden die Ränder beim Drucken abgeschnitten?','Das Motiv liegt möglicherweise außerhalb des Druckbereichs oder das gewählte Papierformat stimmt nicht. Prüfe Format und Vorschau und teste anschließend „An Druckbereich anpassen“.'],
   ['Kann ich den Weihnachtsbrief in Schwarz-Weiß drucken?','Ja. Kontrolliere die PDF in der Graustufenvorschau und drucke eine Testseite, damit Text und Bilder gut erkennbar bleiben. Den Umschlag kannst du danach bunt bemalen.'],
   ['Wie überreiche ich den Brief ohne Glitzer und Unordnung?','Schreibe einen Nordpolgruß auf den Umschlag, male einen Stern und lege den Brief zum Baum oder Lieblingsbuch. Die persönliche Erinnerung im Text ist die eigentliche Überraschung.']
  ]
 },
 es:{
  title:'Carta de Papá Noel para imprimir: consejos y entrega mágica',
  description:'Prepara una carta de Papá Noel para imprimir con consejos de papel, ajustes y sobres, mensajes cariñosos y formas sencillas de entregarla en casa.',
  dek:'Revisa los detalles personales, imprime una página de prueba y añade una pequeña sorpresa al sobre. Un momento tranquilo para leer juntos hace especial una carta de Papá Noel. Así puedes prepararla en casa.',
  sections:[
   ['1. Revisa el texto antes de imprimir',['Comprueba el nombre y los detalles que reconocerá tu peque: su mascota, una actividad favorita o algo que se esforzó en aprender. Elimina cualquier promesa de regalo que no puedas asegurar.','Elf Mailroom ofrece un PDF digital para descargar e imprimir. Tú preparas la impresión, el sobre y la entrega; no se envía una carta física por correo.']],
   ['2. Elige papel y haz una prueba',['El papel de impresora corriente sirve. Si quieres más cuerpo, prueba papel blanco cálido de unos 100–120 g/m², siempre que tu impresora admita ese gramaje y acabado. Consulta sus indicaciones antes de comprarlo.','Selecciona el tamaño de papel del PDF y mira la vista previa. Prueba primero el tamaño real; si el borde queda fuera del área imprimible, usa «Ajustar» o «Ajustar al área de impresión». Haz una prueba antes de subir la calidad de color.']],
   ['3. Dale al sobre un toque del Polo Norte',['Escribe su nombre a mano y añade «Correo del Polo Norte» o un sello dibujado. Una estrella pintada en una esquina aporta un detalle festivo sin purpurina suelta.','En la solapa cabe una pequeña frase sobre el viaje. No hace falta añadir más adornos.'],'Para el sobre: «Entrega especial para una personita encantadora. Revisado por elfos y olisqueado por renos».'],
   ['4. Busca un momento tranquilo para entregarla',['Deja la carta junto al árbol, al lado de un cuento o en la mesa del desayuno. Escoge una hora sin prisas para salir de casa.','Si las sorpresas le incomodan, avisa de que hay una carta y deja que decida cuándo abrirla. Para hermanos, incluye un detalle propio de cada uno sin comparar sus logros.']],
   ['5. Leed juntos y guardad el recuerdo',['Deja que abra el sobre y elija si quiere compañía para leer. Haz una pausa cuando reconozca un detalle y escucha sus preguntas. No hace falta conseguir una reacción perfecta ni una foto.','Después, anota la fecha detrás y guarda la carta plana en una carpeta. Conserva también el PDF por si el original termina muy abrazado, doblado o gastado.'],'Un pequeño recuerdo: «Doblada con cariño y llena de alegría. Solo falta tu sonrisa para completar la magia».']
  ],
  faqs:[
   ['¿Qué papel uso para imprimir una carta de Papá Noel?','El papel corriente es suficiente. Un papel blanco cálido de unos 100–120 g/m² puede darle más cuerpo, pero comprueba que la impresora admite ese gramaje y acabado.'],
   ['¿Por qué se cortan los bordes de la carta al imprimir?','Puede que el diseño sobrepase el área imprimible o que el tamaño de papel seleccionado sea incorrecto. Revisa el tamaño y la vista previa, prueba «Ajustar al área de impresión» e imprime una hoja de prueba.'],
   ['¿Puedo imprimir la carta en blanco y negro?','Sí. Revisa el PDF en escala de grises y haz una prueba para comprobar que texto e ilustraciones se distinguen. Puedes añadir color dibujando en el sobre.'],
   ['¿Cómo entrego la carta sin purpurina ni desorden?','Escribe un mensaje del Polo Norte, dibuja una estrella en el sobre y deja la carta junto al árbol o un libro favorito. El detalle personal del texto será la sorpresa principal.']
  ]
 },
 fr:{
  title:'Lettre du Père Noël à imprimer : conseils et petits détails magiques',
  description:'Papier, réglages d’impression, enveloppe et petits mots du pôle Nord : préparez une lettre du Père Noël à imprimer et un joli moment pour la découvrir.',
  dek:'Vérifiez les détails personnels, imprimez une page d’essai et ajoutez une petite surprise sur l’enveloppe. Un moment calme pour lire ensemble rend la lettre du Père Noël spéciale. Voici comment la préparer à la maison.',
  sections:[
   ['1. Relisez les mots avant d’imprimer',['Vérifiez le prénom et les détails que votre enfant reconnaîtra : son animal, une activité préférée ou un apprentissage qui lui a demandé des efforts. Retirez toute promesse de cadeau que vous ne pouvez pas assurer.','Elf Mailroom fournit un PDF numérique à télécharger et à imprimer. Vous préparez l’impression, l’enveloppe et la remise de la lettre ; aucun courrier papier n’est envoyé par la poste.']],
   ['2. Choisissez le papier et faites un essai',['Le papier d’imprimante ordinaire convient. Pour plus de tenue, essayez un papier blanc chaud d’environ 100 à 120 g/m², si votre imprimante accepte ce grammage et cette finition. Vérifiez ses indications avant l’achat.','Choisissez le format de papier du PDF et regardez l’aperçu. Essayez la taille réelle ; si la bordure dépasse la zone imprimable, utilisez « Ajuster » ou « Ajuster à la zone d’impression ». Faites un essai avant d’augmenter la qualité couleur.']],
   ['3. Donnez à l’enveloppe un air de pôle Nord',['Écrivez le prénom à la main et ajoutez « Courrier du pôle Nord » ou un timbre dessiné. Une étoile dessinée dans un coin apporte une touche festive sans paillettes.','Glissez un petit message sur le rabat. Un seul détail suffit pour imaginer le voyage de la lettre.'],'Pour l’enveloppe : « Livraison spéciale pour une adorable petite personne. Vérifiée par les lutins, reniflée par les rennes. »'],
   ['4. Choisissez un moment calme pour la découverte',['Posez la lettre près du sapin, d’un livre de Noël ou sur la table du petit-déjeuner. Évitez un moment où il faut partir à toute vitesse.','Si votre enfant n’aime pas les surprises, prévenez-le et laissez-le choisir quand ouvrir. Pour une fratrie, ajoutez un souvenir propre à chacun sans comparer les réussites.']],
   ['5. Lisez ensemble et gardez le souvenir',['Laissez votre enfant ouvrir et choisir de lire seul ou avec vous. Faites une pause lorsqu’il reconnaît un détail et accueillez ses questions. Aucune réaction parfaite ni photo n’est nécessaire.','Inscrivez ensuite la date au dos et rangez la lettre à plat dans une pochette. Conservez aussi le PDF pour pouvoir remplacer un original devenu un peu trop câliné.'],'Un mot à conserver : « Pliée avec soin, remplie de joie. Il ne manque que ton sourire pour terminer son voyage. »']
  ],
  faqs:[
   ['Quel papier choisir pour une lettre du Père Noël à imprimer ?','Un papier d’imprimante ordinaire suffit. Un blanc chaud d’environ 100 à 120 g/m² offre plus de tenue, mais vérifiez que votre imprimante accepte son grammage et sa finition.'],
   ['Pourquoi les bords de ma lettre sont-ils coupés ?','Le motif peut dépasser la zone imprimable, ou le format sélectionné peut être incorrect. Vérifiez le format et l’aperçu, puis essayez « Ajuster à la zone d’impression » sur une page de test.'],
   ['Peut-on imprimer la lettre sans imprimante couleur ?','Oui. Vérifiez le PDF en niveaux de gris et faites un essai pour contrôler la lisibilité du texte et des illustrations. Vous pouvez ajouter de la couleur sur l’enveloppe à la main.'],
   ['Comment présenter la lettre sans paillettes ni désordre ?','Écrivez un mot du pôle Nord, dessinez une étoile sur l’enveloppe et posez la lettre près du sapin ou d’un livre préféré. Le détail personnel du texte sera la principale surprise.']
  ]
 },
 pl:{
  title:'List od Mikołaja do druku: jak wydrukować i wręczyć?',
  description:'Dobierz papier, ustaw drukarkę i przygotuj kopertę na list od Mikołaja do druku. Proste wskazówki, czułe wiadomości od elfów i pomysły na wyjątkowe wręczenie.',
  dek:'Sprawdź osobiste szczegóły, wydrukuj stronę próbną i dodaj małą niespodziankę na kopercie. Spokojna chwila na wspólne czytanie sprawi, że list od Mikołaja będzie wyjątkowy. Tak przygotujesz go w domu krok po kroku.',
  sections:[
   ['1. Przeczytaj treść przed drukowaniem',['Sprawdź imię dziecka i szczegóły, które rozpozna: zwierzaka, ulubioną zabawę albo umiejętność, nad którą pracowało. Usuń obietnice prezentów, których nie możesz zapewnić.','Elf Mailroom udostępnia cyfrowy plik PDF do pobrania i wydrukowania. Druk, kopertę i sposób wręczenia przygotowujesz samodzielnie; papierowy list nie jest wysyłany pocztą.']],
   ['2. Wybierz papier i zrób próbny wydruk',['Zwykły papier do drukarki wystarczy. Jeśli wolisz nieco sztywniejszy, wybierz ciepłą biel o gramaturze około 100–120 g/m², o ile urządzenie obsługuje taki papier. Przed zakupem sprawdź zalecenia producenta.','Ustaw format papieru zgodny z PDF-em i obejrzyj podgląd. Zacznij od rzeczywistego rozmiaru. Jeśli ramka wychodzi poza obszar druku, wybierz „Dopasuj” lub „Dopasuj do obszaru wydruku”. Zrób próbę przed ustawieniem wyższej jakości koloru.']],
   ['3. Dodaj kopercie odrobinę bieguna północnego',['Napisz ręcznie imię dziecka i dodaj „Poczta bieguna północnego” albo narysowany znaczek. Gwiazdka w rogu zapewni świąteczny akcent bez sypkiego brokatu.','Na klapce zmieści się krótka wiadomość o podróży. Jeden szczegół wystarczy, by uruchomić wyobraźnię.'],'Na kopertę: „Przesyłka specjalna dla kogoś bardzo kochanego. Sprawdzona przez elfy, obwąchana przez renifery”.'],
   ['4. Wybierz spokojny moment na wręczenie',['Połóż list przy choince, obok świątecznej książki albo na stole przy śniadaniu. Wybierz chwilę, gdy nie musicie zaraz wychodzić z domu.','Jeśli dziecko nie lubi niespodzianek, zapowiedz list i pozwól zdecydować, kiedy go otworzyć. Dla rodzeństwa przygotuj osobiste wspomnienie w każdym liście, bez porównywania osiągnięć.']],
   ['5. Przeczytajcie i zachowajcie pamiątkę',['Niech dziecko samo otworzy kopertę i wybierze wspólne albo samodzielne czytanie. Zatrzymajcie się przy znajomym szczególe i porozmawiajcie. Nie trzeba idealnej reakcji ani zdjęcia.','Potem dopisz datę na odwrocie i przechowuj list na płasko w teczce lub pudełku wspomnień. Zachowaj też PDF, gdyby mocno przytulany oryginał potrzebował kiedyś zastępstwa.'],'Mały liścik na pamiątkę: „Złożony z troską, wypełniony radością. Do pełni magii brakuje tylko Twojego uśmiechu”.']
  ],
  faqs:[
   ['Na jakim papierze wydrukować list od Mikołaja?','Zwykły papier do drukarki wystarczy. Ciepła biel o gramaturze około 100–120 g/m² może dać przyjemniejszy efekt, ale najpierw sprawdź, czy drukarka obsługuje tę gramaturę i rodzaj papieru.'],
   ['Dlaczego drukarka obcina ramkę listu?','Ilustracja może wychodzić poza obszar druku albo wybrany format papieru jest nieprawidłowy. Sprawdź format i podgląd, następnie wypróbuj opcję „Dopasuj do obszaru wydruku” na jednej stronie.'],
   ['Czy list można wydrukować bez kolorowej drukarki?','Tak. Sprawdź podgląd PDF-u w skali szarości i zrób próbny wydruk, aby upewnić się, że tekst i ilustracje są czytelne. Kolor możesz dodać ręcznie na kopercie.'],
   ['Jak wręczyć list od Mikołaja bez brokatu i bałaganu?','Dodaj wiadomość z bieguna północnego i narysuj gwiazdkę na kopercie. Połóż list przy choince lub ulubionej książce. Główną niespodzianką będzie osobisty szczegół w treści.']
  ]
 }
};
