import BlogImage from './BlogImage';
import CookieConsent from '@elf/shared/cookies';
import React,{useState,useEffect} from 'react';
import {ArrowRight,Check,Heart,ShieldCheck,Mail,PenLine,Sparkles,Menu,X,ChevronDown,Printer} from 'lucide-react';
import {santaLetterPrice,designs} from '@elf/shared';
import {languages,localizedSample,digitalNotice} from '@elf/shared/locales';
import {LocaleProvider,useLocale,LanguagePicker,DigitalNotice} from '@elf/shared/i18n';
import {Logo,Button,SectionHeading,LetterCard} from '@elf/shared/ui';
import '@elf/shared/styles';
import './christmas.css';
import ChristmasAccents,{Holly} from './ChristmasAccents';
import {ChristmasDoodle,CozySurprise,FestiveFlourish,HangingOrnaments,useFestiveEntrances} from './FestiveDetails';
import {seoCopy,landingFaqs,languagePath,localizedPath} from '@elf/shared/seo';
import Seo from './Seo';
import {legalPath} from '@elf/shared/seo';
import {articleTranslation,blogArticles,blogCopy,blogPath} from '@elf/shared/blog';
export function Navbar({homePage=false}){const{language,t}=useLocale();const[open,setOpen]=useState(false);const home=languagePath(language);return <><div className="announcement"><Sparkles size={13}/>{t('A little letter. A whole lot of Christmas magic.')}<Sparkles size={13}/></div><header className="navbar wrap"><Logo/><nav aria-label={t('How it works')} className={open?'open':''}>{[['How it works','how-it-works'],['The letters','letters'],['For parents','parents'],['FAQs','faq']].map(([name,id])=><a key={id} href={homePage?`#${id}`:`${home}#${id}`} onClick={()=>setOpen(false)}>{t(name)}</a>)}<a href={blogPath(language)} onClick={()=>setOpen(false)}>{blogCopy[language].label}</a></nav><LanguagePicker/><Button>{t('Write to Santa')}</Button><button className="menu-toggle" aria-label={t('Toggle menu')} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header></>}
function Hero(){const{language,t}=useLocale();const copy=seoCopy[language];return <section className="hero wrap"><div className="hero-copy"><div className="pill"><span/>{t('THE NORTH POLE POSTAL SERVICE')}</div><h1>{copy.h1}</h1><p>{copy.intro} {t('Receive it as a digital PDF to download and print at home. Nothing is sent by post.')}</p><div className="hero-actions"><Button>{t('Write a letter to Santa')}</Button><a className="text-link" href="#how-it-works">{t('See how it works')} <ArrowRight size={15}/></a></div><div className="hero-note"><Heart size={15}/>{t('Made for little believers. Loved by grown-ups.')}</div></div><div className="hero-art"><ChristmasAccents/><img src="/assets/mailroom.webp" width="1536" height="1024" alt={copy.alt} fetchPriority="high"/></div></section>}
function HowItWorks(){const{language,t}=useLocale();return <section id="how-it-works" className="how-section"><HangingOrnaments/><div className="wrap"><CozySurprise kind="bell"/><SectionHeading title={seoCopy[language].how}>{t('You bring the wishes. We’ll bring the Christmas magic.')}</SectionHeading><div className="steps">{[['Tell their story','Add their name, wishes and little details for Santa’s personal reply.','letter','paper'],['Pick their stationery','Choose from six illustrated designs, including Santa at the beach and a kangaroo Christmas BBQ.','stocking','envelope'],['Pay securely','One payment. No account or subscription needed.','heart','reply'],['Review, download and print','Request changes, accept the letter, then print your PDF at home.','gift','paper']].map(([title,text,art,cls],i)=><article className="step" key={title}><div className={`step-art ${cls}`} aria-hidden="true"><span><ChristmasDoodle kind={art}/></span><i>✦</i></div><div className="step-title"><span>0{i+1}</span><h3>{t(title)}</h3></div><p>{t(text)}</p></article>)}</div></div></section>}
function PersonalisedLetter(){
 const{language,t}=useLocale();
 const[example,setExample]=useState('Sophie');
 const[design,setDesign]=useState('classic');
 return <section className="personalised wrap" id="letters">
  <div className="sample-scene">
   <fieldset className="sample-design-picker">
    <legend>{t('Choose your letter design')}</legend>
    <div className="sample-design-grid">{designs.map(theme=><label className={`sample-design-option ${design===theme.id?'selected':''}`} key={theme.id}>
     <input type="radio" className="sr-only" name="sample-design" value={theme.id} checked={design===theme.id} onChange={()=>setDesign(theme.id)}/>
     <span className="sample-design-paper" aria-hidden="true"><img src={`/assets/stationery/${theme.art}.webp`} width="1024" height="1536" alt="" loading="lazy"/><span className="sample-design-lines"/></span>
     <span className="sample-design-name">{t(theme.name)}</span><span className="sample-design-check" aria-hidden="true">{design===theme.id&&<Check size={12}/>}</span>
    </label>)}</div>
   </fieldset>
   <div className="sample-tabs" role="group">{['Sophie','Oliver'].map(name=><button key={name} className={example===name?'active':''} aria-pressed={example===name} onClick={()=>setExample(name)}><Mail size={13} aria-hidden="true"/>{t('{name}’s letter',{name})}</button>)}</div>
   <div className="selected-sample"><Holly className="sample-holly"/><LetterCard text={localizedSample(language,example)} language={language} design={design} sample/></div>
   <div className="sample-caption"><strong aria-live="polite">{t(designs.find(theme=>theme.id===design).name)}</strong>{t('A little peek at the magic · Fictional example')}</div>
  </div>
  <div className="personal-copy"><FestiveFlourish kind="letter"/><h2>{seoCopy[language].example}</h2><p>{t('Their favourite toy. A brave little moment. That very special Christmas wish.')}</p><p>{t('Choose English, German, Spanish, French or Polish for their letter.')}</p><p>{t('Your letter is created with AI from the details you choose to share. You review the words before downloading.')}</p><ul className="check-list">{['Six illustrated themes','Five rewrite requests included','A downloadable, print-ready PDF'].map(x=><li key={x}><Check size={17}/>{t(x)}</li>)}</ul><Button>{t('Create my child’s letter')}</Button><DigitalNotice/></div>
 </section>;
}
function ParentTrust(){const{t}=useLocale();return <section className="parent-section" id="parents"><div className="wrap parent-inner"><div><h2>{t('A little magic. A lot of care.')}</h2><p>{t('Made for little believers. Loved by grown-ups.')}</p><CozySurprise kind="mug"/></div><div className="parent-points">{[[ShieldCheck,'You’re in charge','Choose the details you share and check them before you pay.'],[PenLine,'Make it just right','Ask for a different tone or tell us what to leave out before accepting.'],[Printer,'A keepsake to print at home',digitalNotice]].map(([Icon,title,text])=><article key={title}><span><Icon size={23}/></span><div><h3>{t(title)}</h3><p>{t(text)}</p></div></article>)}</div></div></section>}
function BlogHighlights(){const{language}=useLocale(),copy=blogCopy[language];return <section className="home-blog" aria-labelledby="home-blog-title"><div className="wrap"><div className="home-blog-heading"><div><span className="eyebrow"><Sparkles size={13}/>{copy.label}</span><h2 id="home-blog-title">{copy.title}</h2><p>{copy.intro}</p></div><Button href={blogPath(language)} secondary>{copy.all}</Button></div><div className="home-blog-grid">{blogArticles.map(article=>{const item=articleTranslation(article,language);return <article className="home-blog-card" key={article.slug}><div className="home-blog-mark"><BlogImage article={article} language={language}/></div><h3><a href={blogPath(language,article.slug)}>{item.title}</a></h3><p>{item.description}</p><a className="blog-read" href={blogPath(language,article.slug)}>{copy.read}<ArrowRight size={15}/></a></article>})}</div></div></section>}
function Products(){const{language,t}=useLocale();return <section className="products wrap" id="pricing"><FestiveFlourish kind="stocking"/><SectionHeading title={seoCopy[language].price}/><div className="digital-product"><article className="product featured"><CozySurprise kind="gift"/><h3>{t('Personalised Santa Letter')}</h3><DigitalNotice/><div className="price">{santaLetterPrice.label}</div><ul className="check-list">{['Six illustrated themes','Five rewrite requests included','A downloadable, print-ready PDF'].map(x=><li key={x}><Check size={15}/>{t(x)}</li>)}</ul><Button>{t('Personalise your letter')}</Button><small>{t('One-time payment per letter · No subscription.')}</small></article></div></section>}
function FAQ(){const{language,t}=useLocale();const faqs=landingFaqs;return <section className="faq wrap" id="faq"><FestiveFlourish kind="robin"/><SectionHeading title={seoCopy[language].faq}/><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary><span className="faq-question"><Sparkles size={16} aria-hidden="true"/>{t(q)}</span><ChevronDown size={18}/></summary><p>{t(a)}</p></details>)}</div></section>}
export function Footer({routePath}){const{language,t}=useLocale();const[config,setConfig]=useState(null);const[notice,setNotice]=useState(false);const home=languagePath(language);useEffect(()=>{fetch('/api/config').then(r=>r.json()).then(setConfig).catch(()=>{})},[]);return <footer className="wrap"><div className="festive-footer"><ChristmasDoodle kind="tree"/><CozySurprise kind="gingerbread"/><ChristmasDoodle kind="tree"/></div><nav className="language-links" aria-label={t('Choose your language')}>{languages.map(x=><a key={x.code} href={routePath?localizedPath(routePath,x.code):languagePath(x.code)} hrefLang={x.code} lang={x.code} aria-current={x.code===language?'page':undefined}>{x.name}</a>)}</nav><div className="footer-top"><Logo/><div><a href={`${home}#how-it-works`}>{t('How it works')}</a><a href={`${home}#faq`}>{t('FAQs')}</a><a href={blogPath(language)}>{blogCopy[language].label}</a><a href={legalPath('privacy',language)}>{t('Privacy')}</a><a href={legalPath('terms',language)}>{t('Terms')}</a><a href={legalPath('terms',language)+'#cancellation'}>{t('Cancellations and refunds')}</a>{config?.supportEmail?<a href={`mailto:${config.supportEmail}`}>{t('Contact')}</a>:<button onClick={()=>setNotice(!notice)}>{t('Contact')}</button>}</div></div>{notice&&<p role="status">{t('Policies and support details will be published before purchases open.')}</p>}<DigitalNotice/><div className="footer-bottom"><span>© {new Date().getFullYear()} Elf Mailroom</span><span>{t('Made with a little help from the elves at the North Pole.')} ♡</span></div></footer>}
export default function App(){useFestiveEntrances();const{language,t}=useLocale();const[checkoutEnabled,setCheckoutEnabled]=useState(false);useEffect(()=>{fetch('/api/config').then(r=>r.json()).then(config=>setCheckoutEnabled(config.checkoutEnabled===true)).catch(()=>{})},[]);return <div className="christmas-landing"><Seo language={language} checkoutEnabled={checkoutEnabled}/><a className="skip-link" href="#main">{t('Skip to content')}</a><CookieConsent/><Navbar homePage/><main id="main"><Hero/><div className="trust-strip"><span><ChristmasDoodle kind="stocking"/>{t('Six illustrated themes')}</span><span><ChristmasDoodle kind="heart"/>{t('Five rewrite requests included')}</span><span><ChristmasDoodle kind="gift"/>{t('A keepsake to print at home')}</span></div><HowItWorks/><PersonalisedLetter/><ParentTrust/><BlogHighlights/><Products/><FAQ/><section className="final-cta"><div className="wrap"><div className="final-cta-copy"><div className="festive-sendoff" aria-hidden="true" data-festive-enter><ChristmasDoodle kind="stocking"/><ChristmasDoodle kind="letter"/><ChristmasDoodle kind="tree"/></div><h2>{t('A little letter. A whole lot of Christmas magic.')}</h2><DigitalNotice/><Button>{t('Write to Santa')}</Button></div><img src="/assets/mailroom.webp" alt="" loading="lazy" width="1536" height="1024"/></div></section></main><Footer/></div>}
