import React,{useEffect,useState} from 'react';
import {Search,LogOut,FlaskConical,ArrowLeft,Save} from 'lucide-react';
import {Logo,Button,LetterCard} from '@elf/shared/ui';
import {getDesign} from '@elf/shared';
import {orderLanguage} from '@elf/shared/locales';
import AdminTestLetter from './AdminTestLetter';
async function api(path,data){const response=await fetch(`/api/admin/${path}`,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const result=await response.json();if(!response.ok)throw Object.assign(new Error(result.error||'Please try again.'),{status:response.status});return result;}
const date=value=>value?new Date(value).toLocaleString():'Not recorded';
const state=order=>['queued','generating','retrying'].includes(order.generation_status)?'Writing':order.generation_status==='failed'?'Needs attention':order.letter_version>0&&order.accepted_version===order.letter_version?'Accepted':order.letter_version>0?'Awaiting review':'Not generated';
export default function Admin(){
 const[user,setUser]=useState(null);const[initial,setInitial]=useState(true);const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[list,setList]=useState(null);const[search,setSearch]=useState('');const[query,setQuery]=useState('');const[status,setStatus]=useState('');const[page,setPage]=useState(1);const[selection,setSelection]=useState(null);const[text,setText]=useState('');const[notice,setNotice]=useState('');const[testing,setTesting]=useState(false);
 useEffect(()=>{document.title='Admin mailroom | Elf Mailroom';api('me').then(setUser).catch(()=>{}).finally(()=>setInitial(false));},[]);
 useEffect(()=>{if(!user)return;let active=true;api(`orders?search=${encodeURIComponent(query)}&status=${status}&page=${page}`).then(data=>{if(active)setList(data)}).catch(e=>{if(active){setError(e.message);if(e.status===401)setUser(null)}});return()=>{active=false};},[user,query,status,page,selection?.order.letter_version]);
 async function login(e){e.preventDefault();setBusy(true);setError('');try{setUser(await api('login',{email,password}));setPassword('');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function open(id){setBusy(true);setError('');setNotice('');try{const data=await api(`orders/${id}`);setSelection(data);setText(data.order.letter);window.scrollTo(0,0);}catch(e){setError(e.message);if(e.status===401)setUser(null);}finally{setBusy(false);}}
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await api(`orders/${selection.order.id}/letter`,{version:selection.order.letter_version,letter:text});await open(selection.order.id);setNotice('New version saved. The parent must review and accept it before the final PDF is sent.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function logout(){try{await api('logout',{});setUser(null);setList(null);setSelection(null);setTesting(false);setPassword('');}catch(e){setError(e.message);}}
 return <><header className="builder-header"><Logo/><div className="admin-header-actions"><span>Admin mailroom</span>{user&&<button onClick={logout}><LogOut size={15}/> Sign out</button>}</div></header><main className="admin-page wrap">{initial?<p>Opening the admin mailroom…</p>:!user?<form className="form-card admin-login" onSubmit={login}><span className="eyebrow">FOR THE HEAD ELF</span><h1>Welcome to the mailroom.</h1><p>Sign in to manage purchases and Santa’s letters.</p>{error&&<p className="error" role="alert">{error}</p>}<label htmlFor="admin-email">Admin email</label><input id="admin-email" type="email" required autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)}/><label htmlFor="admin-password">Password</label><input id="admin-password" type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/><Button href={null} type="submit" disabled={busy}>{busy?'Signing in…':'Open the mailroom'}</Button></form>:<>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
 {testing?<AdminTestLetter request={api} onBack={()=>setTesting(false)} onSessionExpired={()=>{setUser(null);setTesting(false);setError('Your admin session expired. Please sign in again.')}}/>:selection?<><button className="text-link admin-back" onClick={()=>{setSelection(null);setNotice('');setError('')}}><ArrowLeft size={16}/> All purchases</button><div className="admin-title"><div><span className="eyebrow">PURCHASE DETAILS</span><h1>{selection.order.buyer_email||'Guest purchase'}</h1><p><code>{selection.order.id}</code></p></div><span className="status-badge">{selection.order.status} · {state(selection.order)}</span></div>
 <div className="admin-detail-grid"><aside><section className="admin-box"><h2>Order details</h2><dl>{[['Purchased',date(selection.order.created_at)],['Amount',selection.order.amount_cents==null?'Not recorded':`US$${(selection.order.amount_cents/100).toFixed(2)}`],['Design',getDesign(selection.order.design).name],['Current version',selection.order.letter_version||'—'],['Accepted version',selection.order.accepted_version||'Not accepted'],['Email',selection.order.email_status],['Generation',selection.order.generation_status]].map(([label,value])=><React.Fragment key={label}><dt>{label}</dt><dd>{value}</dd></React.Fragment>)}</dl></section><section className="admin-box"><h2>Parent’s details</h2>{selection.order.child_details?<dl>{Object.entries(selection.order.child_details).map(([key,value])=><React.Fragment key={key}><dt>{({name:'Child’s name',wish:'Christmas wish',proud:'Proud moment',pet:'Pet or toy',message:'Original letter'})[key]||key}</dt><dd>{value||'Not provided'}</dd></React.Fragment>)}</dl>:<p>Original input was not retained for this older purchase.</p>}</section><section className="admin-box"><h2>Rewrite requests</h2>{selection.requests.length?selection.requests.map(request=><article className="request-item" key={request.id}><span className="status-badge">{request.status}</span><p>{request.instructions}</p><small>Leave out: {JSON.parse(request.avoid).join(', ')||'Nothing specified'}</small><small>{date(request.created_at)}</small></article>):<p>No rewrite requests yet.</p>}</section></aside>
 <div><form className="admin-box" onSubmit={save}><div className="admin-section-title"><h2>Edit the letter</h2><span>Version {selection.order.letter_version||0}</span></div><p>Saving creates a new version and asks the parent to approve it. Previous versions stay in the history.</p><label htmlFor="admin-letter">Letter text</label><textarea id="admin-letter" className="admin-letter-editor" required minLength={30} maxLength={6000} value={text} onChange={e=>setText(e.target.value)}/><Button href={null} type="submit" disabled={busy||selection.order.status!=='paid'||['queued','generating','retrying'].includes(selection.order.generation_status)||selection.order.email_status==='sending'||text===selection.order.letter}><Save size={16}/>{busy?'Saving…':'Save new version'}</Button></form>
 <details className="admin-box"><summary>Preview current edits</summary><LetterCard language={orderLanguage(selection.order)} text={text} design={selection.order.design}/></details><section className="admin-box"><h2>Every letter version</h2>{selection.versions.length?selection.versions.map(version=><details key={version.version}><summary><span>Version {version.version} · {version.source}{selection.order.accepted_version===version.version?' · Accepted':''}</span><small>{date(version.created_at)}</small></summary><pre className="version-text">{version.letter}</pre>{version.instructions&&<p>Request: {version.instructions}</p>}{version.editor&&<p>Edited by {version.editor}</p>}</details>):<p>No letters generated yet.</p>}</section></div></div></>:<>
 <div className="admin-title"><div><span className="eyebrow">A LOOK INSIDE THE MAILROOM</span><h1>Purchases & letters</h1><p>Every little wish, from payment to the final keepsake.</p></div><Button href={null} type="button" onClick={()=>{setTesting(true);setError('');setNotice('');window.scrollTo(0,0)}}><FlaskConical size={17}/> Generate test letter</Button></div>
 <div className="admin-stats">{[['Purchases',list?.summary.purchases],['Paid orders',list?.summary.paid],['Generated letters',list?.summary.letters],['Revenue',list?`US$${((list.summary.revenue||0)/100).toFixed(2)}`:null]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value??'—'}</strong></div>)}</div>
 <form className="admin-filters" onSubmit={e=>{e.preventDefault();setQuery(search);setPage(1)}}><label className="sr-only" htmlFor="order-search">Search purchases</label><input id="order-search" placeholder="Search email or order reference" value={search} onChange={e=>setSearch(e.target.value)}/><button type="submit"><Search size={17}/> Search</button><label className="sr-only" htmlFor="order-status">Payment status</label><select id="order-status" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All payments</option><option value="paid">Paid</option><option value="pending">Pending</option></select></form>
 <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Purchase</th><th>Design</th><th>Payment</th><th>Letter</th><th>Email</th><th>Action</th></tr></thead><tbody>{list?.orders.map(order=><tr key={order.id}><td><strong>{order.buyer_email||'Guest'}</strong><small>{order.id}</small><small>{date(order.created_at)}</small></td><td>{getDesign(order.design).name}</td><td><span className="status-badge">{order.status}</span></td><td>{state(order)}<small>{order.letter_version?`Version ${order.letter_version}`:'—'}</small></td><td>{order.email_status}</td><td><button className="link-button" disabled={busy} onClick={()=>open(order.id)}>View & edit</button></td></tr>)}</tbody></table>{list?.orders.length===0&&<p className="empty-state">No purchases match this search.</p>}</div><div className="admin-pagination"><button disabled={page===1} onClick={()=>setPage(page-1)}>← Previous</button><span>Page {page} · {list?.total||0} purchases</span><button disabled={!list||page*list.pageSize>=list.total} onClick={()=>setPage(page+1)}>Next →</button></div>
 </>}
 </>}</main></>;
}
