import React,{useEffect,useState,useRef} from 'react';
import {Download,RefreshCw,Link as LinkIcon} from 'lucide-react';
import {Logo,Button} from '@elf/shared/ui';
import {getDesign} from '@elf/shared';
import {languagePath} from '@elf/shared/seo';
import {useLocale,LanguagePicker,DigitalNotice} from '@elf/shared/i18n';
import PaidLetterPreview from './PaidLetterPreview';
import {orderApi,orderRequest} from './purchase-access';
export default function Purchase({id}){
 const{t,language}=useLocale();const[order,setOrder]=useState(null);const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[changes,setChanges]=useState('');const[avoid,setAvoid]=useState('');const[showRewrite,setShowRewrite]=useState(false);const[copied,setCopied]=useState(false);const polls=useRef(0);
 const working=order&&['queued','generating','retrying'].includes(order.generationStatus);
 async function refresh(){try{const next=await orderApi(id);setOrder(next);setError('');return next}catch(e){setError(e.message)}}
 useEffect(()=>{refresh()},[id]);useEffect(()=>{document.title=`${t('Personalised Santa Letter')} | Elf Mailroom`},[language]);
 useEffect(()=>{if(!order||error||polls.current>=150||!(working||order.status!=='paid'||['queued','sending','retrying'].includes(order.emailStatus)))return;const timer=setTimeout(()=>{polls.current++;refresh()},4000);return()=>clearTimeout(timer)},[order,error]);
 async function download(){const response=await orderRequest(id,'/pdf');if(!response.ok){const data=await response.json();throw new Error(data.error)}const url=URL.createObjectURL(await response.blob());const link=document.createElement('a');link.href=url;link.download='letter-from-santa.pdf';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}
 async function accept(){setBusy(true);setError('');try{if(!order.accepted)await orderApi(id,'/accept',{version:order.version});await refresh();await download()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function rewrite(e){e.preventDefault();setBusy(true);setError('');try{await orderApi(id,'/rewrite',{version:order.version,instructions:changes,avoid:avoid.split(/[\n,]/).map(s=>s.trim()).filter(Boolean)});polls.current=0;await refresh();setShowRewrite(false);setChanges('');setAvoid('')}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function copy(){try{await navigator.clipboard.writeText(order.purchaseUrl||location.href);setCopied(true)}catch{setError('Copy the private link from your browser’s address bar.')}}
 return <><header className="builder-header"><Logo/><div className="customer-nav"><LanguagePicker/><a href={languagePath(language)}>{t('Back to the mailroom')}</a></div></header><main className="purchase-page wrap"><div className="section-heading"><span className="eyebrow">{t('YOUR PRIVATE NORTH POLE DELIVERY')}</span><h1>{t('A little letter. Just for them.')}</h1><p>{t('Read it together, make it yours, then keep the magic.')}</p></div><DigitalNotice/>
 {error&&<div className="error" role="alert">{t(error)}<button className="link-button" onClick={refresh}>{t('Try again')}</button></div>}{!order&&!error&&<p role="status" className="centered">{t('Opening your purchase…')}</p>}{order&&<>
 <div className="purchase-meta"><span>{t(order.status==='paid'?'Payment confirmed':'Confirming payment')} · {t(getDesign(order.design).name)}{order.version>0?` · ${t('Version {version}',{version:order.version})}`:''}</span>{order.purchaseUrl&&<button className="link-button" onClick={copy}><LinkIcon size={13}/>{t(copied?'Private link copied':'Copy private link')}</button>}</div>
 {order.status!=='paid'?<div className="notice" role="status">{t('We’re checking your payment. There’s no need to pay again.')}</div>:<>
 {working&&<div className="notice" role="status"><RefreshCw size={16}/>{t(order.letter?'Santa is making your changes. Your previous version is below while you wait.':'Santa is writing your letter. It will appear here when it’s ready.')}</div>}
 {order.generationStatus==='failed'&&<div className="notice">{t('We couldn’t finish the latest request.')} {t(order.letter?'Your previous letter is still here to review and accept.':'Your paid order is saved; keep the order reference for support.')}</div>}
 {order.letter&&<div className="purchase-review"><PaidLetterPreview id={id} version={order.version} text={order.letter} language={order.language||'en'}/><section className="review-controls"><span className="eyebrow">{t('THE FINAL LITTLE TOUCH')}</span><h2>{t(order.accepted?'Ready to treasure.':'Does it feel just right?')}</h2><p>{t(order.accepted?'Your accepted version is saved. Download it again whenever you need it.':'Ask for a different tone or leave out a topic, then approve the version you love.')}</p><div className="review-actions"><Button href={null} disabled={busy||working||order.emailStatus==='sending'} onClick={accept}><Download size={17}/>{t(busy?'One little moment…':order.accepted?'Download PDF':'Accept & download PDF')}</Button><Button href={null} secondary disabled={busy||working||order.emailStatus==='sending'||!order.canRewrite||order.rewritesRemaining===0} onClick={()=>setShowRewrite(!showRewrite)}><RefreshCw size={16}/>{t('Request changes')}</Button></div>
 <p className="helper">{t('{count} rewrite requests remaining. Your letter’s history is safely saved.',{count:order.rewritesRemaining})}</p>
 {showRewrite&&<form onSubmit={rewrite} className="rewrite-form"><label htmlFor="rewrite">{t('What would you like Santa to change?')}</label><textarea id="rewrite" required minLength={3} maxLength={1500} value={changes} onChange={e=>setChanges(e.target.value)} placeholder={t('Make it more playful and shorter.')}/><label htmlFor="avoid">{t('Words or topics to leave out')} <small>· {t('optional')}</small></label><textarea id="avoid" maxLength={1600} value={avoid} onChange={e=>setAvoid(e.target.value)} placeholder={t('School grades, the bicycle, being watched')}/><p className="helper">{t('Separate topics with commas or new lines. Earlier exclusions carry forward.')}</p><Button href={null} type="submit" disabled={busy}>{t('Rewrite my letter')}</Button></form>}
 {order.accepted&&<p className="helper">{t(order.emailStatus==='sent'?'Your accepted PDF has been sent by email.':['queued','sending','retrying'].includes(order.emailStatus)?'Your accepted PDF is queued for email delivery.':order.emailStatus==='failed'?'Email delivery could not be confirmed. Download your PDF here.':'')}</p>}
 {!order.accepted&&order.emailStatus!=='not_requested'&&<p className="helper">{t('The final PDF email is sent only after you accept this version.')}</p>}
 </section></div>}
 </>}
 <div className="purchase-reference"><p>{t('Order reference')}: <code>{order.id}</code></p><p>{t('Keep your private link safe. Anyone with it can view and revise this letter.')}</p></div></>}
 </main></>;
}
